Add organization module to Import Project
PublicMapping/districtbuilder pull request #1003
Opened 2021-09-08 21:14 UTC by kevinearldenny

## Overview

- Allows a user to associate an imported project with an organization by linking it with an organization template

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

![image](https://user-images.githubusercontent.com/66973361/132586006-79d98de3-c29c-4192-a92f-045259819d82.png)

![image](https://user-images.githubusercontent.com/66973361/132586016-d5a1a330-9ba9-453c-9600-6a9b96e3b3cb.png)

### Notes

There is no way for a user to associate a project with an organization besides through a template, right? It seems like we may need some additional error checking here to ensure that projects are not imported that violate the rules of a project template.

## Testing Instructions

- Create an organization and a project template for that organization, for a region that is not PA
- Join the newly created organization with your user
- Import Project screen -> Begin importing a project for the region associated with the project template
- Expect: Only newly created organization appears in options for selecting an organization
- Select the project template you created, and create the new project from the import
- Expect: Project now appears in all organization projects list

Closes #971

2021-09-14 18:35 UTC, maurizi requested changes
We're also going to need changes to the backend for import - right now we look up the region based on the state FIPS code, filtering out `hidden` regions, which won't work for a major use-case for project templates - custom `hidden` regions in the same state.

https://github.com/PublicMapping/districtbuilder/blob/664a76c30f0d54b1ed50b8889fccfff9cc60f629/src/server/src/districts/controllers/districts.controller.ts#L62-L66

I think the best way to handle this is an option `RegionConfigId` query parameter to the `import` endpoint, which we can use to look up the region instead of using the FIPS code in the CSV if provided.

2021-09-14 18:35 UTC, maurizi commented on src/server/src/organizations/services/organizations.service.ts
> +    // Returns public data for organization screen
```suggestion
    // Returns public data for organization section of import screen
```

2021-09-14 18:35 UTC, maurizi commented on src/server/src/organizations/services/organizations.service.ts
> +      .leftJoinAndSelect("organization.users", "users", "users.id = :userId", { userId: userId })
We don't want to expose user emails here:
```suggestion
      .leftJoin("organization.users", "users", "users.id = :userId", { userId: userId })
      .addSelect(["users.id", "users.name"])
```

2021-09-14 18:35 UTC, maurizi commented on src/client/screens/ImportProjectScreen.tsx
> +                  )
Is there a reason to not have the above two cards be refactored into a shared component used by both this screen and the Create Project Screen? Superficially they seem like they look/behave identically.

Something like:
```tsx
<OrganizationWithTemplates organizations={organizationsInRegion} onTemplateChanged={onTemplateChanged} />
```

2021-09-14 18:35 UTC, maurizi commented on src/client/screens/ImportProjectScreen.tsx
> +  const [organizationSlug, setOrganizationSlug] = useState<string | undefined>(undefined);
Is there a reason to have the `organizationSlug` component state, and have changes to that trigger an API call to fetch organization details, instead of simply using the organization details available in `organizationsInRegion`?

Making that switch would also fix another relatively minor issue - if there is an organizations with templates that span multiple states we don't filter the templates shown bc we're requerying from the main endpoint w/o the region code filter (odd, but the test organization does that, and I could see reasons for having it setup that way).

2021-09-15 15:17 UTC, kevinearldenny commented on src/client/screens/ImportProjectScreen.tsx
> +                  )
I'm realizing after refactoring why I didn't do this originally - they _do not_ behave the same. The selection of a project template in the Create Project Screen is a component (`OrganizationTemplates`) that is also leveraged within the Organization screen that automatically creates a project after a template has been selected, whereas we also need to inject the plan from the imported project here.

![image](https://user-images.githubusercontent.com/66973361/133461273-06887994-0d1a-4af7-bc69-9efc2de5787e.png)

2021-09-15 16:33 UTC, kevinearldenny commented on src/shared/entities.d.ts
> +  readonly organization?: OrganizationSlug | null;
It seems that I'm getting a compile error after removing this.

2021-09-15 17:16 UTC, maurizi commented on src/server/src/districts/controllers/districts.controller.ts
> +    const regionConfig = regionConfigId
Shouldn't this be the other way around?
```suggestion
    const regionConfig = regionCode
```

2021-09-15 21:12 UTC, maurizi commented on src/client/components/OrganizationWithTemplates.tsx
> +    </React.Fragment>
Can't style a fragment - this is causing a warning in the console.
```suggestion
    <Box sx={style.container}>
      {organizations && organizations.length > 0 && (
        <Card sx={{ variant: "card.flat" }}>
          <legend sx={{ ...style.cardLabel, ...style.legend, ...{ flex: "0 0 100%" } }}>
            Organization
          </legend>
          <Box sx={style.cardHint}>
            Are you making a new map with an organization you&apos;ve joined?
          </Box>
          <div
            sx={{
              flex: "0 0 50%",
              "@media screen and (max-width: 770px)": {
                flex: "0 0 100%"
              }
            }}
            key="custom"
          >
            <Label>
              <Radio
                name="organization"
                value=""
                onChange={onOrgChanged}
                checked={currentOrganization === undefined}
              />
              <Flex as="span" sx={{ flexDirection: "column" }}>
                <div sx={style.radioHeading}>No organization</div>
                <div sx={style.radioSubHeading}>Continue without an organization</div>
              </Flex>
            </Label>
          </div>
          {organizations.map(org => (
            <Label
              key={org.slug}
              sx={{
                display: "inline-flex",
                "@media screen and (min-width: 750px)": {
                  flex: "0 0 48%",
                  "&:nth-of-type(even)": {
                    mr: "2%"
                  }
                }
              }}
            >
              <Radio name="organization" value={org.slug} onChange={onOrgChanged} />
              <Flex as="span" sx={{ flexDirection: "column", flex: "0 1 calc(100% - 2rem)" }}>
                <div sx={style.radioHeading}>{org.name}</div>
              </Flex>
            </Label>
          ))}
        </Card>
      )}
      {currentOrganization && (
        <Card sx={{ variant: "card.flat" }}>
          <legend sx={{ ...style.cardLabel, ...style.legend, ...{ flex: "0 0 100%" } }}>
            Template
          </legend>
          <Box sx={style.cardHint}>
            Which of {currentOrganization.name}&apos;s templates would you like to use?
          </Box>
          <div
            sx={{
              flex: "0 0 50%",
              "@media screen and (max-width: 770px)": {
                flex: "0 0 100%"
              }
            }}
            key="custom"
          >
            <Label>
              <Radio
                name="projectTemplate"
                value=""
                onChange={onTemplateChanged}
                checked={currentOrganization === undefined}
              />
            </Label>
          </div>
          {currentOrganization.projectTemplates.map(template => (
            <Label
              key={template.id}
              sx={{
                display: "inline-flex",
                "@media screen and (min-width: 750px)": {
                  flex: "0 0 48%",
                  "&:nth-of-type(even)": {
                    mr: "2%"
                  }
                }
              }}
            >
              <Radio name="projectTemplate" value={template.id} onChange={onTemplateChanged} />
              <Flex as="span" sx={{ flexDirection: "column", flex: "0 1 calc(100% - 2rem)" }}>
                <div sx={style.radioHeading}>{template.name}</div>
              </Flex>
            </Label>
          ))}
        </Card>
      )}
    </Box>
```

2021-09-15 21:12 UTC, maurizi commented on src/client/components/OrganizationWithTemplates.tsx
> +const OrganizationWithTemplates = ({
Since we _do_ have a `OrganizationTemplate` component already and we're _not_ combining them together, let's rename this file/component to indicate that it is specific to the `ImportScreen` - maybe `ImportOrganizationTemplates` ?

2021-09-15 21:52 UTC, maurizi requested changes

2021-09-15 21:52 UTC, maurizi commented on src/client/components/OrganizationWithTemplates.tsx
> +          </div>
I don't think we need a radio button for "no template selected"
```suggestion
```

2021-09-15 21:52 UTC, maurizi commented on src/client/components/OrganizationWithTemplates.tsx
> +    </React.Fragment>
Can't style a fragment - this is causing a warning in the console.
```suggestion
    <Box sx={style.container}>
      {organizations && organizations.length > 0 && (
        <Card sx={{ variant: "card.flat" }}>
          <legend sx={{ ...style.cardLabel, ...style.legend, ...{ flex: "0 0 100%" } }}>
            Organization
          </legend>
          <Box sx={style.cardHint}>
            Are you making a new map with an organization you&apos;ve joined?
          </Box>
          <div
            sx={{
              flex: "0 0 50%",
              "@media screen and (max-width: 770px)": {
                flex: "0 0 100%"
              }
            }}
            key="custom"
          >
            <Label>
              <Radio
                name="organization"
                value=""
                onChange={onOrgChanged}
                checked={currentOrganization === undefined}
              />
              <Flex as="span" sx={{ flexDirection: "column" }}>
                <div sx={style.radioHeading}>No organization</div>
                <div sx={style.radioSubHeading}>Continue without an organization</div>
              </Flex>
            </Label>
          </div>
          {organizations.map(org => (
            <Label
              key={org.slug}
              sx={{
                display: "inline-flex",
                "@media screen and (min-width: 750px)": {
                  flex: "0 0 48%",
                  "&:nth-of-type(even)": {
                    mr: "2%"
                  }
                }
              }}
            >
              <Radio name="organization" value={org.slug} onChange={onOrgChanged} />
              <Flex as="span" sx={{ flexDirection: "column", flex: "0 1 calc(100% - 2rem)" }}>
                <div sx={style.radioHeading}>{org.name}</div>
              </Flex>
            </Label>
          ))}
        </Card>
      )}
      {currentOrganization && (
        <Card sx={{ variant: "card.flat" }}>
          <legend sx={{ ...style.cardLabel, ...style.legend, ...{ flex: "0 0 100%" } }}>
            Template
          </legend>
          <Box sx={style.cardHint}>
            Which of {currentOrganization.name}&apos;s templates would you like to use?
          </Box>
          <div
            sx={{
              flex: "0 0 50%",
              "@media screen and (max-width: 770px)": {
                flex: "0 0 100%"
              }
            }}
            key="custom"
          >
            <Label>
              <Radio
                name="projectTemplate"
                value=""
                onChange={onTemplateChanged}
                checked={currentOrganization === undefined}
              />
            </Label>
          </div>
          {currentOrganization.projectTemplates.map(template => (
            <Label
              key={template.id}
              sx={{
                display: "inline-flex",
                "@media screen and (min-width: 750px)": {
                  flex: "0 0 48%",
                  "&:nth-of-type(even)": {
                    mr: "2%"
                  }
                }
              }}
            >
              <Radio name="projectTemplate" value={template.id} onChange={onTemplateChanged} />
              <Flex as="span" sx={{ flexDirection: "column", flex: "0 1 calc(100% - 2rem)" }}>
                <div sx={style.radioHeading}>{template.name}</div>
              </Flex>
            </Label>
          ))}
        </Card>
      )}
    </Box>
```

2021-09-15 21:52 UTC, maurizi commented on src/client/components/OrganizationWithTemplates.tsx
> +    e.currentTarget.value === "" && setCurrentOrganization(undefined);
Having identical component state & callbacks here as well as in the parent component is a good indication we should have the state moved out of this component into the parent one:

```diff
diff --git a/src/client/components/OrganizationWithTemplates.tsx b/src/client/components/OrganizationWithTemplates.tsx
index a77f6ee..c076a4a 100644
--- a/src/client/components/OrganizationWithTemplates.tsx
+++ b/src/client/components/OrganizationWithTemplates.tsx
@@ -1,9 +1,10 @@
 /** @jsx jsx */
 import { IOrganization } from "../../shared/entities";
 import { Box, Card, Flex, jsx, ThemeUIStyleObject, Label, Radio } from "theme-ui";
-import React, { useState } from "react";
+import React from "react";
 
 interface Props {
+  readonly currentOrganization?: IOrganization;
   readonly organizations: readonly IOrganization[];
 }
 
@@ -60,21 +61,11 @@ const style: ThemeUIStyleObject = {
 } as const;
 
 const OrganizationWithTemplates = ({
+  currentOrganization,
   organizations,
   onTemplateChanged,
   orgChanged
 }: Props & IProps) => {
-  const onOrgChanged = (e: React.ChangeEvent<HTMLInputElement>) => {
-    orgChanged(e);
-    const org =
-      e.currentTarget.value !== "" &&
-      organizations?.filter(o => o.slug === e.currentTarget.value)[0];
-    org && setCurrentOrganization(org);
-    e.currentTarget.value === "" && setCurrentOrganization(undefined);
-  };
-  const [currentOrganization, setCurrentOrganization] = useState<IOrganization | undefined>(
-    undefined
-  );
   return (
     <React.Fragment sx={style.container}>
       {organizations && organizations.length > 0 && (
@@ -98,7 +89,7 @@ const OrganizationWithTemplates = ({
               <Radio
                 name="organization"
                 value=""
-                onChange={onOrgChanged}
+                onChange={orgChanged}
                 checked={currentOrganization === undefined}
               />
               <Flex as="span" sx={{ flexDirection: "column" }}>
@@ -120,7 +111,7 @@ const OrganizationWithTemplates = ({
                 }
               }}
             >
-              <Radio name="organization" value={org.slug} onChange={onOrgChanged} />
+              <Radio name="organization" value={org.slug} onChange={orgChanged} />
               <Flex as="span" sx={{ flexDirection: "column", flex: "0 1 calc(100% - 2rem)" }}>
                 <div sx={style.radioHeading}>{org.name}</div>
               </Flex>
diff --git a/src/client/screens/ImportProjectScreen.tsx b/src/client/screens/ImportProjectScreen.tsx
index a1d68e7..6e86c6a 100644
--- a/src/client/screens/ImportProjectScreen.tsx
+++ b/src/client/screens/ImportProjectScreen.tsx
@@ -565,6 +565,7 @@ const ImportProjectScreen = ({ regionConfigs }: StateProps) => {
 
                 {organizationsInRegion && (
                   <OrganizationWithTemplates
+                    currentOrganization={currentOrganization}
                     organizations={organizationsInRegion}
                     onTemplateChanged={onTemplateChanged}
                     orgChanged={onOrgChanged}
```

2021-09-15 21:52 UTC, maurizi commented on src/client/components/OrganizationWithTemplates.tsx
> +    </React.Fragment>
Can't style a fragment - this is causing a warning in the console.
```suggestion
    <Box sx={style.container}>
      {organizations && organizations.length > 0 && (
        <Card sx={{ variant: "card.flat" }}>
          <legend sx={{ ...style.cardLabel, ...style.legend, ...{ flex: "0 0 100%" } }}>
            Organization
          </legend>
          <Box sx={style.cardHint}>
            Are you making a new map with an organization you&apos;ve joined?
          </Box>
          <div
            sx={{
              flex: "0 0 50%",
              "@media screen and (max-width: 770px)": {
                flex: "0 0 100%"
              }
            }}
            key="custom"
          >
            <Label>
              <Radio
                name="organization"
                value=""
                onChange={onOrgChanged}
                checked={currentOrganization === undefined}
              />
              <Flex as="span" sx={{ flexDirection: "column" }}>
                <div sx={style.radioHeading}>No organization</div>
                <div sx={style.radioSubHeading}>Continue without an organization</div>
              </Flex>
            </Label>
          </div>
          {organizations.map(org => (
            <Label
              key={org.slug}
              sx={{
                display: "inline-flex",
                "@media screen and (min-width: 750px)": {
                  flex: "0 0 48%",
                  "&:nth-of-type(even)": {
                    mr: "2%"
                  }
                }
              }}
            >
              <Radio name="organization" value={org.slug} onChange={onOrgChanged} />
              <Flex as="span" sx={{ flexDirection: "column", flex: "0 1 calc(100% - 2rem)" }}>
                <div sx={style.radioHeading}>{org.name}</div>
              </Flex>
            </Label>
          ))}
        </Card>
      )}
      {currentOrganization && (
        <Card sx={{ variant: "card.flat" }}>
          <legend sx={{ ...style.cardLabel, ...style.legend, ...{ flex: "0 0 100%" } }}>
            Template
          </legend>
          <Box sx={style.cardHint}>
            Which of {currentOrganization.name}&apos;s templates would you like to use?
          </Box>
          <div
            sx={{
              flex: "0 0 50%",
              "@media screen and (max-width: 770px)": {
                flex: "0 0 100%"
              }
            }}
            key="custom"
          >
            <Label>
              <Radio
                name="projectTemplate"
                value=""
                onChange={onTemplateChanged}
                checked={currentOrganization === undefined}
              />
            </Label>
          </div>
          {currentOrganization.projectTemplates.map(template => (
            <Label
              key={template.id}
              sx={{
                display: "inline-flex",
                "@media screen and (min-width: 750px)": {
                  flex: "0 0 48%",
                  "&:nth-of-type(even)": {
                    mr: "2%"
                  }
                }
              }}
            >
              <Radio name="projectTemplate" value={template.id} onChange={onTemplateChanged} />
              <Flex as="span" sx={{ flexDirection: "column", flex: "0 1 calc(100% - 2rem)" }}>
                <div sx={style.radioHeading}>{template.name}</div>
              </Flex>
            </Label>
          ))}
        </Card>
      )}
    </Box>
```

2021-09-15 21:52 UTC, maurizi commented on src/client/components/OrganizationWithTemplates.tsx
> +    <React.Fragment sx={style.container}>
Can't style a fragment - this is causing a warning in the console.
```diff
diff --git a/src/client/components/OrganizationWithTemplates.tsx b/src/client/components/OrganizationWithTemplates.tsx
index a77f6ee..010f2ec 100644
--- a/src/client/components/OrganizationWithTemplates.tsx
+++ b/src/client/components/OrganizationWithTemplates.tsx
@@ -76,7 +76,7 @@ const OrganizationWithTemplates = ({
     undefined
   );
   return (
-    <React.Fragment sx={style.container}>
+    <Box sx={style.container}>
       {organizations && organizations.length > 0 && (
         <Card sx={{ variant: "card.flat" }}>
           <legend sx={{ ...style.cardLabel, ...style.legend, ...{ flex: "0 0 100%" } }}>
@@ -175,7 +175,7 @@ const OrganizationWithTemplates = ({
           ))}
         </Card>
       )}
-    </React.Fragment>
+    </Box>
   );
 }; 
```

2021-09-15 21:52 UTC, maurizi commented on src/shared/entities.d.ts
> +  readonly organization?: OrganizationSlug | null;
The compiler error is bc of this line https://github.com/PublicMapping/districtbuilder/pull/1003/files#diff-6faec875147ec226df146c0cecc52430d6a8f2381d7bc19ab6205b2017e0f24bR151 which was added in this PR - but as far as I can tell the create project backend doesn't use this newly added parameter.

2021-09-16 14:31 UTC, maurizi commented
This is working correctly in my testing, with just a few cleanups left until its good to go.

Also Github posted one of my comments 4x times for some reason, sorry about that.

2021-09-16 19:13 UTC, kevinearldenny commented
The `organization` property in `CreateProjectData` is definitely being used [here](https://github.com/PublicMapping/districtbuilder/blob/5fd9c812cca361fee009d4e70e756ddfee8c228b/src/client/api.ts#L145)

2021-09-16 20:31 UTC, maurizi commented on src/client/components/ImportOrganizationTemplates.tsx
> +    width: "large",
```suggestion
    width: "100%",
```

2021-10-04 20:41 UTC, closed without merging