Add documentation on releasing new data
PublicMapping/districtbuilder pull request #1081
Opened 2021-12-06 13:30 UTC by ktohalloran

## Overview

There was no documentation on releasing new data. This PR adds documentation on both the data quality assurance and release processes and on configuring PG Admin for use with the project.

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

2021-12-06 19:42 UTC, maurizi requested changes
Thanks for the thorough writeup!

I left a few suggested comments - most of them are around making the docs a _little_ more vague by removing reference the "state" or the shared google sheet.

We use that state for our main 50 states data, _but_ we have several sub-state regions (county, town) as well as one hidden state region not from VEST / coordinated via the spreadsheet, so I don't want to confuse someone updating a non-state region when reading these docs in the future.

2021-12-06 19:42 UTC, maurizi commented on deployment/README.md
> +The list of states with new data can be found [here](https://docs.google.com/spreadsheets/d/1khiNAQp4UnfkgfvRSbfjDU9CU2zJrJ0pMRUeF5a4cuM/edit#gid=645349603) highlighted in yellow. Before applying the
A few suggested changes:
 - Added a preamble to explain why we're doing this
 - state -> region
 - removed references to the google sheet. Not all regions are VEST data / coordinated using the Google sheet, just the main 50 states - we also have county & municipal regions, as well as at least 1 alternative state region

```suggestion
## Updating Region Data

Careful steps need to be taken when adding or updating regions to prevent site downtime, and additionally when updating existing regions to avoid unintentionally storing stale data or breaking existing maps.

### Pre-update steps

Before applying changes to the staging database or S3 assets, you will need to make test maps of the affected regions. Open [staging](https://app.staging.districtbuilder.org/) and make a new map of each region being updated, adding both counties and blockgroups to a few districts.

### Database access
To release new data, you will need to access the staging & production databases. You may prefer to use a database administration desktop application for PostgreSQL like PG Admin. You can find information on configuring PG Admin for DistrictBuilder's databases [here](https://github.com/PublicMapping/districtbuilder/blob/develop/deployment/configure_pgadmin.md).

You will need to update both the staging and production databases, first staging and then production, in order to run quality assurance on the data before posting it to the production site.
```

2021-12-06 19:42 UTC, maurizi commented on deployment/README.md
> +Once you have updated the data, follow the instructions in the [Restart Services](https://github.com/PublicMapping/districtbuilder/tree/develop/deployment#restart-services) section below.
Mostly text tweaks here, expanded on the warning up top:

```suggestion
### Update process

For existing regions there are two ways to update the region to use new data: by using S3 to overwrite the existing data or by updating the database.

Note that updates to the `s3_uri` column on production for an existing region **will** cause API calls for that region as well as healthchecks to fail until data is loaded, potentially resulting in a production outage. For this reason, it is recommended to _only_ ever make updates to the `region_config.s3_uri` column on the staging database.

#### Overwriting data on S3

For existing regions, when updating data the best practice way is to overwrite the data on S3 and reload tasks once all data has been overwritten. To do so, for each region with updated data, do the following:

- Make a backup of the data by running `aws s3 –profile=district-builder cp -r <existing URI> <existing URI>-backup-<yyyy-mm-dd>`
- Copy the new data over the old with `aws s3 –profile=district-builder cp -r <new URI> <existing URI>`

#### Updating the database

The faster but less ideal way for use only in staging is to just update the URI in the `s3_uri` column of the database in PG Admin. Then save the database.

#### Reloading services

Once you have updated the data, follow the instructions in the [Restart Services](https://github.com/PublicMapping/districtbuilder/tree/develop/deployment#restart-services) section below.
```

2021-12-06 19:42 UTC, maurizi commented on deployment/README.md
> +Once you have restarted the services for staging, you will need to return to the test maps you made. Open each to check that it loads and then make an edit or two, both at a block group and county le
```suggestion
Once you have restarted the services for staging, you will need to return to the test maps you made. Open each to check that it loads and then make an edit or two, both at a block group and county level. If nothing breaks, that region's data is good to go up on production.
```

2021-12-06 19:42 UTC, maurizi commented on deployment/README.md
> +Once you have completed the data update for both staging and production, copy each updated state's URI listed in the production database to the `production s3 url` column in the Google Sheet to mark
```suggestion
Once you have completed the data update for both staging and production, copy each updated region's URI listed in the production database to the `production s3 url` column in the Google Sheet to mark it as complete.
```

2021-12-06 19:42 UTC, maurizi commented on deployment/README.md
> +If while monitoring the logs, you see _one_ error about topology failing to load, wait and it will try again (health check failures during this process are normal). If you see _multiple_ errors about
```suggestion
If while monitoring the logs, you see _one_ error about topology failing to load, wait and it will try again (health check failures during this process are normal). If you see _multiple_ errors about topology failing to load, check both that region's `s3_uri` in the database as well the contents of the file. Once a fix is made, you will need to kill the task following instructions from the Stopping Tasks section below and let it restart itself.
```

2021-12-06 19:42 UTC, maurizi commented on deployment/configure_pgadmin.md
> +From the fileshare location, save the `districtbuilder-stg.pem` file to somewhere PG Admin can be configured to find it but outside of the project directory, such as the `.ssh` folder in your user fo
```suggestion
From the fileshare location, save the `districtbuilder-stg.pem` file to somewhere PG Admin can be configured to find it, such as the `.ssh` folder in your home folder. Then return to PG Admin and use the file browser popup to find it.
```

2021-12-06 19:42 UTC, maurizi commented on deployment/configure_pgadmin.md
> +Username is ec2-user.
```suggestion
Username is `ec2-user`.
```

2021-12-06 19:42 UTC, maurizi commented on CHANGELOG.md
> +- Add instructions on configuring PG Admin and on releasing new state data [#1081](https://github.com/PublicMapping/districtbuilder/pull/1081)
```suggestion
- Add instructions on configuring PG Admin and on releasing new region data [#1081](https://github.com/PublicMapping/districtbuilder/pull/1081)
```

2021-12-07 14:01 UTC, ktohalloran commented
Thanks for your feedback! I've made the changes you suggested so this should be ready for re-review.

2021-12-07 18:15 UTC, maurizi approved these changes

2021-12-08 21:03 UTC, merged