Stop loading archived topology
PublicMapping/districtbuilder pull request #1132
Opened 2022-02-10 21:17 UTC by rachelekm

## Overview

This PR stops loading archived topology layers as part of `TopologyService`. While we initially retained the topology properties and let the larger geometries get garbage collected, loading the `topo.json` and keeping the properties in memory still takes up space that would be worth freeing up. Archived, read-only maps relied on topology properties for the following:

- Converting from 2010 to 2020 census data
- Exporting to csv
- Copying to account
- Fetching sorted county names used in Evaluate’s County Split metric

Now, users with archived map projects should no longer be able to convert census data, export to csv, or copy an archived, read-only project to their account. An error message will display if a user tries to import a csv with an archived region. However, archived region county names were added as a constant variable on the frontend and should display as before.

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo
![db_prdemo_archivedtopo_small](https://user-images.githubusercontent.com/36374797/153497765-0a1b28a4-5a58-4889-a6eb-a5bae05b737b.gif)

### Notes

- In addition to deleting the button to allow users to convert their 2010 census data to 2020 data, I got rid of its endpoint and any related code that was isolated to this functionality. This included the `Crosswalk` service/entity to map new blocks from old—however, I did not get rid of the crosswalk s3 folder `/crosswalk-files/` as this seemed like an action more difficult to reverse should we bring converting census data back.

- The County Split metric’s county names for archived regions are now displayed by referencing a `key: value` pair in the `archivedCountyNames` constant. The values were created for each archived region in the production database using the below command to mimic the topology properties resource generated from the backend (and preserve sorting): 

```
aws --profile district-builder s3 cp {S3_URI}/topo.json - | jq -r '[.objects.county.geometries | .[] | {"name": .properties.name}]' | pbcopy
```

- I had to update our server tests since we now can’t import and process csv files for archived regions. Ideally, the test would use a region with 2020 census data, but I ran into some trouble with the tests still failing after updating the test `region.s3URI` and the `de.csv` data. I can successfully import the same csv through the client and, for the time being, using 2010 data and defining the test region as `archived=false` seems to do the trick, so this may be a separate issue if we want to update the data for server tests. 

## Testing Instructions

- `scripts/server`

- Create a project for `DE`, since we have both 2010 and 2020 census data in our dev database

- Using `scripts/dbshell`, update `ARCHIVED = TRUE` for the region using 2020 data

- Your project should now have a small info box at the top-left of your map alerting you that you are using archived data

- Confirm the following:

  - The info box does not include a “Convert to 2020” button

  - On “export” an option to export to csv should no longer exist

  - There should no longer be a “Copy to account” button

  - On Evaluate confirm there is no toast error message 

  - Navigate to the County Split Evaluate detail and confirm that county names are displaying appropriately

  - Navigate back to the homepage and select the left-hand options menu for your archived project and confirm there is no option to export to csv
  
- Ensure the above features are still available for projects with non-archived regions

Closes #1118

2022-02-10 21:34 UTC, rachelekm commented on src/server/src/districts/services/topology.service.ts
> +        // Filter out archived regions
I wanted to chain the `filter` and `sortBy` lodash methods but couldn't quite figure it out without `sortedRegions` losing its structure, so ended up leaving these separate

2022-02-10 21:43 UTC, maurizi commented on src/server/src/districts/services/topology.service.ts
> -        return archived ? GeoUnitProperties.fromTopology(geoUnitTopology) : geoUnitTopology;
I think we can get rid of the `GeoUnitProperties` class in it's entirety now.

2022-02-10 21:59 UTC, maurizi requested changes
This is looking really good! Great job 👍 

The major thing that I think still needs to happen here is that there is more code we should be able to remove - the `GeoUnitProperties` class was only used for archived regions but I still see it referenced in a few places in the code.

2022-02-10 21:59 UTC, maurizi commented on src/server/src/districts/services/topology.service.ts
> +        const filteredRegions = _.filter(regionConfigs, ["archived", false]);
Sometimes you need explain what you're doing in a comment because it isn't immediately obvious what the code does, but usually when I see myself writing a "this is what the code does" comment I try and see if renaming some variables / rewriting the code to be more self-explanatory would remove the need for it.

```suggestion
        const unarchivedRegions = _.filter(regionConfigs, region => !region.archived]);
```

2022-02-10 21:59 UTC, maurizi commented on src/client/components/evaluate/ProjectEvaluateSidebar.tsx
> +          );
This is a nice simple way to handle this - I like it 😄

2022-02-11 19:45 UTC, rachelekm commented
Thanks, @maurizi! Implemented these changes and there shouldn't be any more references to the `GeoUnitProperties` class.

2022-02-14 20:58 UTC, maurizi approved these changes
Working great 👍

2022-02-14 21:56 UTC, merged