Add color picker to reference layer fly out
PublicMapping/districtbuilder pull request #1150
Opened 2022-02-21 19:57 UTC by ktohalloran

## Overview

This PR adds the ability to change a reference layer's color. This change is made via the reference layer flyout and is saved to the database.

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

![color_picker_demo](https://user-images.githubusercontent.com/77936689/155018853-85435c78-e21f-4185-9353-afd198249c12.gif)

## Testing Instructions

- Start the server and open a project with existing reference layers. Verify that those existing layers display as they should and that the color picker works to change their colors.
- Create new layer, toggle it on, change its color, and verify that both the color of the icon and the layer itself change to the new color. Also verify that the selection marker in the flyout has moved to the correct color.
- Verify that on color change the layers stay in alphabetical order that no flickering occurs.

Closes #998

2022-02-24 15:49 UTC, maurizi requested changes
Functionally this is looking really great & it matches the wireframes well. Great job 🎉 

I've left a few comments on things I think need to be updated before this is merged, primarily backend related but also one frontend issue re: how we update the layer colors on the map after saving them.

2022-02-24 15:49 UTC, maurizi commented on src/shared/constants.ts
> +}
We _don't_ want this. This ends up with the database storing `#17c42f` or other hex codes in the `color` column: https://github.com/PublicMapping/districtbuilder/pull/1150/files#diff-41f1bd333faff04c6cfda50343542e0c2ae21be090242270c30477bd025c45a6R7

Per the issue description:
> This should be an enum, with the actual RGB value for the colors defined in the frontend code, for flexibility in changing the styling in the future.

We should change this enum to not reference hex codes like so, and then recreate the migrations:
```suggestion
export enum ReferenceLayerColors {
  Green = "GREEN",
  Orange = "ORANGE",
  Purple = "PURPLE",
  Blue = "BLUE",
  Pink = "PINK",
  Red = "RED"
}
```

We can move the hex codes to `src/client/constants/colors.ts`; since the server should never need/use the color hex codes, putting them in `src/client` instead of `src/shared` ensures it _can't_ use them.

Something like this should work to get the color code from the enum value:
```typescript
const REFERENCE_LAYER_COLOR_CODES = {
  [ReferenceLayerColors.Green]: "#17c42f",
  [ReferenceLayerColors.Orange]: "#f3ad37",
  [ReferenceLayerColors.Purple]: "#7549f6",
  [ReferenceLayerColors.Blue]: "#0018ff",
  [ReferenceLayerColors.Pink]: "#eaa0bd",
  [ReferenceLayerColors.Red]: "#f62756"
};
```

2022-02-24 15:49 UTC, maurizi commented on src/server/src/reference-layers/entities/update-reference-layer.dto.ts
> +  readonly layer: ReferenceLayerGeojson;
We don't want to allow updates to these fields - there are no UI mechanisms to update them, and in any case we would never want to allow the user to change things like project ID, layer content or layer type without more careful validation than merely checking that it exists - otherwise a bug in our client code or a malicious user of the API could cause us to have invalid data stored in the database.

Since we're using `PATCH` we're only sending the `layer_color` field anyway.

```suggestion
```

2022-02-24 15:49 UTC, maurizi commented on src/server/src/reference-layers/entities/update-reference-layer.dto.ts
> +  readonly layer_color: ReferenceLayerColors;
See the comment above in create dto re: `@isEnum`

2022-02-24 15:49 UTC, maurizi commented on src/client/components/map/Map.tsx
> +      });
If I look at the developer network tools, changing the color triggers 4 API requests, each of which return the updated geojson.

It looks like that is this:
 - The initial PATCH, which returns the full geojson
 - Once for this line here https://github.com/PublicMapping/districtbuilder/pull/1150/files#diff-e83fa137620a096633593c2ac8c432be0fb237d97c96157a7ab3e4a03c5246f8R53
 - And then _twice_ for this call to `fetchOneReferenceLayer`
![image](https://user-images.githubusercontent.com/4432106/155556519-ea96800f-6f1e-4f30-afdb-1c802c66c872.png)

I think we can simplify things a good deal here:
 - Delete the above section
 - Delete the call to `projectReferenceLayersFetch` in `ReferenceLayerFlyout`
 - Move the `patchReferenceLayer` call into a new action/reducer, and use the data returned by the PATCH call to update the redux store - no further API calls needed
 
 As a bonus, moving the call to `patchReferenceLayer` into the `projectData` reducer along with the other reference layer related ones means it has ready access to the current project id from the redux store, so you don't need to thread it all the way down to `ReferenceLayerFlyout`

2022-02-28 18:59 UTC, ktohalloran commented
Ok, now that Jenkins built this again successfully, this is ready for re-review! Thanks for all the feedback and the assistance in making the edits along the way.

2022-03-01 18:45 UTC, maurizi approved these changes
Tested it out one last time and it's working great 👍

2022-03-01 19:50 UTC, merged