Add Creation and Login Dates to User
PublicMapping/districtbuilder pull request #1159
Opened 2022-02-28 23:13 UTC by rachelekm

## Overview

Adds a date to the database when a user first creates their account as well as a date for when the user last logs in. The `lastLoginDt` column updates at each log in.

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

## Testing Instructions

- `scripts/update`
- Create an account, log out, and then run `scripts/dbshell`
- Confirm new columns `createdDt` and `lastLoginDt` are part of the `user` table and populated with default date values (now) for your account
- Wait a few minutes then log back in
- Run `scripts/dbshell` again and confirm that the `lastLoginDt` column has an updated timestamp and `createdDt` remains unchanged

Closes #520

2022-03-01 20:08 UTC, maurizi requested changes
Testing and it's working great 👍 

The code changes here mostly look good, but I did have two suggestions for code cleanups that I'd like to see before this gets merged.

2022-03-01 20:08 UTC, maurizi commented on src/server/src/users/entities/user.entity.ts
> +    name: "user_created_dt",
I'm curious - is there a reason you went with `user_created_dt` instead of just `created_dt`, but named the field `createdDt` instead of `userCreatedDt`?
```suggestion
    name: "created_dt",
```

2022-03-01 20:08 UTC, maurizi commented on src/server/src/auth/controllers/auth.controller.ts
> +      await this.authService.updateLastLogin(login.email);
We can take advantage of the error checking above to avoid needing to query for `user` again inside the service, by passing in the `id` from `userOrError`:
```diff
diff --git a/src/server/src/auth/controllers/auth.controller.ts b/src/server/src/auth/controllers/auth.controller.ts
index e70d3e4..0a23fd3 100644
--- a/src/server/src/auth/controllers/auth.controller.ts
+++ b/src/server/src/auth/controllers/auth.controller.ts
@@ -30,6 +30,7 @@ import { RegisterDto } from "../entities/register.dto";
 import { ResetPasswordDto } from "../entities/reset-password.dto";
 import { AuthService } from "../services/auth.service";
 import { Organization } from "../../organizations/entities/organization.entity";
+import { User } from "../../users/entities/user.entity";
 
 /*
  * Authentication service that handles logins, account activiation and
@@ -63,8 +64,9 @@ export class AuthController {
           message: { password: ["Invalid password"] }
         } as Errors<LoginDto>);
       }
-      await this.authService.updateLastLogin(login.email);
-      return this.authService.generateJwt(userOrError);
+      const user: User = userOrError;
+      await this.authService.updateLastLogin(user.id);
+      return this.authService.generateJwt(user);
     } catch (error) {
       if (error instanceof HttpException) {
         throw error;
diff --git a/src/server/src/auth/services/auth.service.ts b/src/server/src/auth/services/auth.service.ts
index ae7d006..78b3736 100644
--- a/src/server/src/auth/services/auth.service.ts
+++ b/src/server/src/auth/services/auth.service.ts
@@ -58,13 +58,8 @@ export class AuthService {
     return LoginErrors.INVALID_PASSWORD;
   }
 
-  async updateLastLogin(email: string): Promise<void | LoginErrors> {
-    const user = await this.usersService.findOne({ email });
-    if (!user) {
-      return LoginErrors.NOT_FOUND;
-    }
-
-    return await this.usersService.updateLastLogin(user.id);
+  async updateLastLogin(userId: UserId): Promise<void | LoginErrors> {
+    return await this.usersService.updateLastLogin(userId);
   }
 
   generateJwt(user: User): JWT {
```

2022-03-01 20:26 UTC, rachelekm commented on src/server/src/users/entities/user.entity.ts
> +    name: "user_created_dt",
Ah, I thought since there were other tables with "created_dt"-named columns I should distinguish the column name to make it easier in the event of a join but now realizing that's mostly just confusing/irrelevant.

2022-03-07 18:05 UTC, maurizi approved these changes
👍

2022-03-07 20:22 UTC, merged