Update server node dependencies
PublicMapping/districtbuilder pull request #1168
Opened 2022-03-14 23:10 UTC by BryanQuigley

Was looking for updates to help with the memory usage. Didn't succeed, but these updates do fix some security notices.

@NestJS
@Type
@turf
@types (except node which set to 16)

Green updates - @nestjs-modules/mailer bcrypt eslint-plugin-import pg

Yellow - @typescript-eslint/eslint-plugin @typescript-eslint/parser aws-sdk
eslint eslint-config-prettier eslint-plugin-functional lru-cache rollbar
rxjs ts-node tsconfig-paths

Red
Passport, geojson2shp, eslint-plugin-jsdoc, class-transformer, jest

Dropped
@godaddy/terminus
ts-loader

2022-03-21 18:17 UTC, maurizi requested changes
Tested and working other than the the two regressions I found & left comments about.

As per my other comment, I'd prefer to either drop the `eslint` updates here or also include updates to `eslint` elsewhere in the project.

2022-03-21 18:17 UTC, maurizi commented on src/server/package.json
> +    "@nestjs-modules/mailer": "1.6.1",
This update broke sending emails.
I had to make the following change to get them working again with this version:
```diff
diff --git a/src/server/src/auth/services/auth.service.ts b/src/server/src/auth/services/auth.service.ts
index 3fe19b42..585a90fc 100644
--- a/src/server/src/auth/services/auth.service.ts
+++ b/src/server/src/auth/services/auth.service.ts
@@ -104,7 +104,7 @@ export class AuthService {
           ? `${process.env.CLIENT_URL}/activate/${emailToken}/${org}`
           : `${process.env.CLIENT_URL}/activate/${emailToken}`
       },
-      template: "./verify"
+      template: "verify"
     });
 
     this.logSentEmail(info);
@@ -123,7 +123,7 @@ export class AuthService {
         user,
         url: `${process.env.CLIENT_URL}/password-reset/${emailToken}`
       },
-      template: "./passwordreset"
+      template: "passwordreset"
     });
 
     this.logSentEmail(info);
```

2022-03-21 19:03 UTC, BryanQuigley commented on src/server/package.json
> +    "eslint-plugin-jsdoc": "38.0.3",
updated them all

2022-03-23 20:24 UTC, BryanQuigley commented
made eslint changes and condensed, but haven't tested locally yet.

2022-03-23 21:17 UTC, maurizi approved these changes
👍

2022-03-23 22:51 UTC, merged