Submit map button
PublicMapping/districtbuilder pull request #1179
Opened 2022-03-24 14:24 UTC by maurizi

## Overview

Adds workflow for submitting a map for a contest.

Two new fields have been added to `ProjectTemplate`:
 - `contestActive`: controls whether the "Submit" button is shown for maps connected to this template
 - `contestNextSteps`: HTML to display in the Next steps modal displayed after submission (optional, modal not shown if not set)
 
 Submission date is tracked on a new `Project.submittedDt` field, which also causes the submitted map to become read-only.

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

Submitting a map w/o next steps HTML set:
![submit-no-next-steps](https://user-images.githubusercontent.com/4432106/159934876-4fd2d1ff-971f-4d90-82f9-21ddb24bfba8.gif)

Submitting a map with next steps HTML set:
![submit-next-steps](https://user-images.githubusercontent.com/4432106/159934924-fae92c0d-ad70-4633-8c76-d4b82fbba726.gif)

## Testing Instructions

- Use `scripts/load-dev-data` to reload your test data (it should make a contest active on the PA House of Representatives template for the Azavea organization), or use `scripts/dbshell` to set up contest fields for a project template of your choice.
- Create a map for that template
  - There should be a "Submit" button in the upper-right. Submitting your map should display a success toast and open the Next steps modal. Clicking the "Submitted" button should display a link to re-open the next steps modal.
  - Using `scripts/dbshell`, update your project template to set the next steps HTML to be empty: `UPDATE project_template SET contest_next_steps = '';`
  - Submit another map - you should still see the toast, but not the Next steps modal, and there should no longer be a link to it.
  - Using `scripts/dbshell`, update your project template to set the contest to be inactive: `UPDATE project_template SET contest_active = FALSE;`. You should still see the "Submitted" button for maps that were already submitted, but should no longer see a "Submit" button for maps that were not yet submitted.
- A few minutes after submitting a map, go to the Evaluate > Competitiveness detail. The "View on PlanScore" link should be present, not the "Upload to PlanScore" button.

Closes #1170

2022-03-24 14:26 UTC, maurizi commented on src/client/components/ProjectHeader.tsx
> +          variant: "buttons.secondary",
@jfrankl do we want to switch the "Evaluate" button to _always_ use secondary colors, or should it get the primary blue color when the submit button isn't visible like it does now?

2022-03-29 21:29 UTC, KlaasH requested changes
The code looks good, and the testing steps all went as expected.  A couple small notes below (two capitalization/spacing notes and one weird warning window), and I also noticed one issue after I submitted: the "Submit" text says the map won't be editable after it's submitted, and the overlay in the corner of the map shows up saying it's read-only, but I can still edit it:
![image](https://user-images.githubusercontent.com/6598836/160710183-6e525692-5ee4-4651-9dee-1b9407f7da43.png)

If I reload the tab, the editing interface is gone, but submitting without reloading doesn't seem to be fully switching things over to read-only.

2022-03-29 21:29 UTC, KlaasH commented on src/client/components/map/SubmitMapButton.tsx
> +                  View{" "}
These two sentences are getting smashed together: 
![image](https://user-images.githubusercontent.com/6598836/160706283-57e8564b-8114-4424-a512-405bbf5dc66f.png)

2022-03-29 21:29 UTC, KlaasH commented on src/client/components/map/SubmitMapButton.tsx
> +                  </Themed.a>
When I click this link, it shows me this:
![image](https://user-images.githubusercontent.com/6598836/160706496-21fe32af-82d8-4be7-8889-94dbbb5828eb.png)

If I click the "Open xdg-open" button, it launches a new window in my default browser (which is not the one I was viewing the site in) with "void:0" in the address bar.

2022-03-29 22:40 UTC, rachelekm reviewed
This worked well for me and I was able to successfully submit and see the message/modal/html where appropriate. My maps were read-only after submitting, however I did find that I could submit while still editing a district. In that instance, it was still editable after submit until I hit "accept" for the district and then it went back to being a non-editable, read-only map. 
<img width="1050" alt="Screen Shot 2022-03-29 at 6 31 49 PM" src="https://user-images.githubusercontent.com/36374797/160718153-153ffe9a-57ab-4fdf-b201-d0a192dfc367.png">

2022-03-30 16:47 UTC, maurizi commented
@KlaasH thanks for the review! Somehow I hadn't even noticed the map was still interactable - my eyes just saw the tool selection buttons go away and assumed I was good 😳.

All issues should be addressed now.

2022-03-30 17:08 UTC, jfrankl commented
@maurizi looks good! One request: could you please reduce the padding on the bottom of this panel so it closely matches the padding at the top of the padding?

![image](https://user-images.githubusercontent.com/1809908/160892087-b7bf2723-280f-4b52-b7ba-d83fda7e75ee.png)

2022-04-01 20:51 UTC, KlaasH approved these changes
:+1: Looks good!

2022-04-05 15:58 UTC, merged