Hide last page button on Community Maps screen
PublicMapping/districtbuilder pull request #1208
Opened 2022-05-05 20:19 UTC by aaronxsu

## Overview

This PR adds a prop to the `PaginationFooter` component so that we configure the community maps UI to not show the last page button.

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Notes

Note that the linked issue's original scope was changed in the first comment.

## Testing Instructions

- Spin up app servers and frontend
- Log in to the home screen. Make sure the pagination footer shows the last page button
- Navigate to the "Community maps" page. Make sure the pagination footer does not show the last page button

Closes #1205

2022-05-06 13:33 UTC, maurizi requested changes

2022-05-06 13:33 UTC, maurizi commented on src/client/components/PaginationFooter.tsx
> +            ))}
We don't want to _always and unconditionally_ hide the link to the last page - it should still be possible to click through to the last page by going through the intervening pages first. We just don't want to show the link when you're not close to the last page.

I think this change should take care of that:
```diff
diff --git a/src/client/components/PaginationFooter.tsx b/src/client/components/PaginationFooter.tsx
index 6fbb7450..abc23221 100644
--- a/src/client/components/PaginationFooter.tsx
+++ b/src/client/components/PaginationFooter.tsx
@@ -45,7 +45,10 @@ const PaginationFooter = ({
 
   // We show a set of pages around the current page, as well as links for first & last page
   const startingPage = Math.max(1, currentPage - MAX_PAGES_AROUND_CURRENT);
-  const endingPage = Math.min(totalPages, currentPage + MAX_PAGES_AROUND_CURRENT);
+  const endingPage = Math.min(
+    showLastPageButton ? totalPages : totalPages + 1,
+    currentPage + MAX_PAGES_AROUND_CURRENT
+  );
   const pageNumbers = range(startingPage, endingPage);
 
   const PageLink = ({ number }: { readonly number: number }) => (
```

BTW you can create a bunch of test projects to have a lot of pages on the Community Maps page on your local database by using the [`./scripts/manage create-random-projects` command](https://github.com/PublicMapping/districtbuilder/blob/develop/src/manage/README.md#manage-create-random-projects-number-region) - that was helpful for me when testing this feature.

2022-05-06 19:23 UTC, aaronxsu commented on src/client/components/PaginationFooter.tsx
> +            ))}
Good point and agreed. It makes sense to show the last page button when the current page is close to the last one, and we don't show the last page if the current page is far away. I tried applying the suggested diff, but it did not work very well for me. I think the reason is that `endingPage` controls what is in the `pageNumbers`, which is the pages in between.

So I made the changes here: https://github.com/PublicMapping/districtbuilder/pull/1208/commits/55b5219d62a95984c33c4a76dd0f4e96d2928b31 : basically, if we want to conditionally hide the last page button, only when the `currentPage + 3` is no less than the `totalPages` do we show that button, i.e. the current page is approaching the last page. Hope this makes sense. What do you think?

2022-05-10 11:47 UTC, maurizi commented on src/client/components/PaginationFooter.tsx
> +            ))}
With these changes you're now always showing the "·" separator, even when the last page isn't being displayed:
![image](https://user-images.githubusercontent.com/4432106/167617198-46a352ca-a5f2-4b2c-b9e5-ea4aaf9effee.png)

That dot separator should only be visible when we're showing the first/last page with a _gap_, e.g.
1 · 3 4 5 6 7 · 8

> I tried applying the suggested diff, but it did not work very well for me. I think the reason is that endingPage controls what is in the pageNumbers, which is the pages in between.

Yes - getting the last page to appear in `pageNumbers` when `showLastPageButton = false` was my intention. We already have code to [not show the last page button when it's in `pageNumbers`](https://github.com/PublicMapping/districtbuilder/blob/8471abd79828c6bf7def780bcd41edaba0486d7b/src/client/components/PaginationFooter.tsx#L69) (which I think was effectively dead code until now?)

Can you explain what scenario you tested that the diff didn't work in? I made sure to test it myself before suggesting the change, and just tried it again in a variety of scenarios and didn't see any issues.

2022-05-12 14:43 UTC, maurizi commented on src/client/components/PaginationFooter.tsx
> +            ))}
@aaronxsu and I discussed this on a call - he thought he needed to change the lines above as well as apply the diff, it's working fine once we sorted that out.

2022-05-12 14:54 UTC, maurizi approved these changes

2022-05-12 14:57 UTC, merged