Add email opt-in option and T&C to registration page
PublicMapping/districtbuilder pull request #1210
Opened 2022-05-06 22:01 UTC by aaronxsu

## Overview

This PR:
- adds `isMarketingEmailOn` field to data models: `IUser`, `User`, and `RegisterDto`
- adds a migration to add the above mentioned field to the `public.user` table
- changes method return shape per data model update
- updates the register endpoint async method
- updates the registration UI according to the design
- adds an email opt-in field and T&C text/link to the registration component, updates the form validator

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

![Screen Shot 2022-05-06 at 5 54 03 PM](https://user-images.githubusercontent.com/16109558/167221616-0f1f5e3f-c9d1-4962-a98b-571f730cf62d.png)

## Testing Instructions

- Run migration
- Spin up servers and frontend
- Click on `Sign up for free` link on the home page
- Make sure the new email opt-in checkbox is there and is clickable
- Make sure the T&C text is there and the link can be clicked to open the T&C content in a new tab
- Fill in the form, make sure the form validator works as expected
- Submit the form. Open the dbshell and make sure the newly added field and value is correctly persisted

Closes #1123

2022-05-10 12:14 UTC, maurizi commented on src/client/components/RegisterContent.tsx
> +}
This seems to have been added by mistake?
```suggestion
```

2022-05-10 12:17 UTC, maurizi commented on src/server/src/users/entities/user.entity.ts
> +  @Column({ default: false, type: "boolean" })
We usually rename our columns to use snake_case instead of camelCase at the SQL level on this project:

```diff
diff --git a/src/server/migrations/1651868826475-AddIsMarketingEmailOnToUser.ts b/src/server/migrations/1651868826475-AddIsMarketingEmailOnToUser.ts
index cc111624..1ef2d6f2 100644
--- a/src/server/migrations/1651868826475-AddIsMarketingEmailOnToUser.ts
+++ b/src/server/migrations/1651868826475-AddIsMarketingEmailOnToUser.ts
@@ -4,11 +4,11 @@ export class AddIsMarketingEmailOnToUser1651868826475 implements MigrationInterf
     name = 'AddIsMarketingEmailOnToUser1651868826475'
 
     public async up(queryRunner: QueryRunner): Promise<void> {
-        await queryRunner.query(`ALTER TABLE "user" ADD "isMarketingEmailOn" boolean NOT NULL DEFAULT false`);
+        await queryRunner.query(`ALTER TABLE "user" ADD "is_marketing_email_on" boolean NOT NULL DEFAULT false`);
     }
 
     public async down(queryRunner: QueryRunner): Promise<void> {
-        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "isMarketingEmailOn"`);
+        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "is_marketing_email_on"`);
     }
 
 }
diff --git a/src/server/src/users/entities/user.entity.ts b/src/server/src/users/entities/user.entity.ts
index 88d04d1d..8fd0c166 100644
--- a/src/server/src/users/entities/user.entity.ts
+++ b/src/server/src/users/entities/user.entity.ts
@@ -52,7 +52,7 @@ export class User implements IUser {
   })
   lastLoginDt: Date;
 
-  @Column({ default: false, type: "boolean" })
+  @Column({ default: false, type: "boolean", name: "is_marketing_email_on" })
   isMarketingEmailOn: boolean;
 
   constructor(params?: {

```

2022-05-10 12:27 UTC, maurizi commented on src/client/components/RegisterContent.tsx
> +      </Box>
Moving this link into `RegisterContent` caused it to be duplicated when `RegisterContent` is used in it's other context from the organization page (you'll see this modal when you try and click "Join organization" or "Use template" while logged out):

![image](https://user-images.githubusercontent.com/4432106/167627669-1751a0d3-b1a0-4461-bfa5-ac73de41dc54.png)

2022-05-10 12:30 UTC, maurizi commented on src/client/components/RegisterContent.tsx
> +  const location = useLocation<AuthLocationState>();
This is unused?
```suggestion
```

2022-05-10 13:19 UTC, maurizi commented on src/client/components/RegisterContent.tsx
> +  const location = useLocation<AuthLocationState>();
Actually it looks like theres more lint than that on this screen. Not sure why it isn't being picked up by CI (maybe bc its a warning?), but you can see the warnings in the console output:
```
districtbuilder-client-1               | WARNING in src/client/components/RegisterContent.tsx
districtbuilder-client-1               |   Line 2:17:    'useEffect' is defined but never used          @typescript-eslint/no-unused-vars
districtbuilder-client-1               |   Line 3:51:    'Link' is defined but never used               @typescript-eslint/no-unused-vars
districtbuilder-client-1               |   Line 3:57:    'Themed' is defined but never used             @typescript-eslint/no-unused-vars
districtbuilder-client-1               |   Line 28:9:    'location' is assigned a value but never used  @typescript-eslint/no-unused-vars
districtbuilder-client-1               |   Line 148:10:  'validatePassword' is defined but never used   @typescript-eslint/no-unused-vars
districtbuilder-client-1               |   Line 148:27:  'password' is defined but never used           @typescript-eslint/no-unused-vars
districtbuilder-client-1               |   Line 148:37:  Unexpected any. Specify a different type       @typescript-eslint/no-explicit-any
districtbuilder-client-1               |   Line 148:42:  'arg1' is defined but never used               @typescript-eslint/no-unused-vars
```

2022-05-12 16:39 UTC, aaronxsu commented on src/client/components/RegisterContent.tsx
> +  const location = useLocation<AuthLocationState>();
Discussed this on Slack that the above warning should not show up if adding back the “Already have an account…” component.

2022-05-12 16:48 UTC, aaronxsu commented on src/client/components/RegisterContent.tsx
> +}
Yep, oops, this is removed in [here](https://github.com/PublicMapping/districtbuilder/pull/1210/commits/ecdc49a723e259118d342d67ccd2c1e57f297311#diff-3078fb287843d5943e64d2e52990a6f50abd6c53c12e7bb096e10d3cd794f389L158-L160)

2022-05-12 16:49 UTC, aaronxsu commented on src/server/src/users/entities/user.entity.ts
> +  @Column({ default: false, type: "boolean" })
Agreed. Updated in this commit: https://github.com/PublicMapping/districtbuilder/pull/1210/commits/e39f8d343d86ba62e670955c08ddcdd2f3687995. As we chatted on Slack, we could follow steps in [here](https://github.com/PublicMapping/districtbuilder/issues/88)  to revert the previous migration, and then run the migration again to test this change.

2022-05-12 16:50 UTC, aaronxsu commented on src/client/components/RegisterContent.tsx
> +      </Box>
Good call. Yea, the changes are reflected here: https://github.com/PublicMapping/districtbuilder/pull/1210/commits/ecdc49a723e259118d342d67ccd2c1e57f297311. I also got a chance to get a 👍🏼 from @jfrankl of the change.

2022-05-12 17:30 UTC, maurizi requested changes
Looking pretty good 🎉 
Just one more tiny tweak needed!

2022-05-12 17:30 UTC, maurizi commented on src/client/components/RegisterContent.tsx
> +import { useLocation } from "react-router-dom";
Tragically `react-router-dom` _also_ has a `Link` component that we need to use for internal links.
I've mixed these up before too...

```suggestion
import { Box, Button, Checkbox, Flex, jsx, Label, Themed } from "theme-ui";
import { toast } from "react-toastify";
import { connect } from "react-redux";
import { Link, useLocation } from "react-router-dom";
```

2022-05-12 19:37 UTC, maurizi approved these changes
👍

2022-05-12 19:51 UTC, jfrankl commented
Looking good!

2022-05-13 20:58 UTC, merged