Add user account page
PublicMapping/districtbuilder pull request #1230
Opened 2022-06-14 18:16 UTC by aaronxsu

## Overview

This PR:
- updates the `InputField` component to take more optional arguments
- adds a dropdown menu item `Account` to the avatar component in the app header
- updates the data model of the user `PATCH` so that it takes `isMarketingEmailOn` field
- adds a user account page
- updates the forgot password page so that it reads an optional route param to populate the email field

### Checklist

- [x] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

![Screen Shot 2022-06-14 at 2 14 36 PM](https://user-images.githubusercontent.com/16109558/173660373-c80d92a0-1e4e-4034-a44b-911e0ffc0cf9.png)

## Testing Instructions

- Run update script to install a new dependency
- Spin up local server and client
- Log in to the app
- Click the avatar from app topbar and select the `Account` menu item
- On the user account page, make sure all the fields are populated with existing info and email field cannot be edited
- Make sure it allows you to submit the form if you have changed the name field and/or the marketing email checkbox
- Make sure the data is persisted to the DB and the page fetches the new user account data after successful submission
- Make sure clicking on the `Reset password` link takes you to the forgot password page with your email pre-filled
- Go back to the user account page. Make sure the email link also works under the account deletion section

Closes #1169

2022-06-15 21:11 UTC, maurizi requested changes
Mostly looking pretty good, I was able to update my name and check/uncheck the marketing toggle, and the Forgot PW links and the mailto link both work 🎉  

There are some opportunities to clean up some of the front-end code, and I'd like to see us more gracefully handle errors.

2022-06-15 21:11 UTC, maurizi commented on src/client/screens/ForgotPasswordScreen.tsx
> +  }: Route = useRouter();
We can clean this up and eliminate the need to bring in the new `use-react-router` dependency by using the existing location state we get above with `useLocation`:

```diff
diff --git a/src/client/App.tsx b/src/client/App.tsx
index e3a9c658..a4b9f6f4 100644
--- a/src/client/App.tsx
+++ b/src/client/App.tsx
@@ -70,7 +70,7 @@ const App = () => (
           <Route path="/login" exact={true} component={LoginScreen} />
           <Route path="/maps" exact={true} component={PublishedMapsListScreen} />
           <Route path="/register" exact={true} component={RegistrationScreen} />
-          <Route path="/forgot-password/:email?" exact={true} component={ForgotPasswordScreen} />
+          <Route path="/forgot-password" exact={true} component={ForgotPasswordScreen} />
           <Route path="/activate/:token" exact={true} component={ActivateAccountScreen} />
           <Route
             path="/activate/:token/:organizationSlug"
diff --git a/src/client/screens/ForgotPasswordScreen.tsx b/src/client/screens/ForgotPasswordScreen.tsx
index ae97597a..1e2b9cf7 100644
--- a/src/client/screens/ForgotPasswordScreen.tsx
+++ b/src/client/screens/ForgotPasswordScreen.tsx
@@ -1,7 +1,6 @@
 /** @jsx jsx */
 import React, { useState } from "react";
-import { Link, useLocation, RouteComponentProps } from "react-router-dom";
-import useRouter from "use-react-router";
+import { Link, useLocation } from "react-router-dom";
 import { Box, Button, Card, Flex, Heading, jsx, Themed } from "theme-ui";
 import { ReactComponent as Logo } from "../media/logos/logo.svg";
 
@@ -15,23 +14,17 @@ import { AuthLocationState } from "../types";
 const isFormInvalid = (form: ForgotPasswordForm): boolean =>
   Object.values(form).some(value => value.trim() === "") || !form.email.includes("@");
 
-interface ForgotPasswordForm {
-  readonly email: string;
+export interface ResetPasswordLocationState {
+  readonly email?: string;
 }
 
-interface RouteProps {
-  email: string | undefined;
+interface ForgotPasswordForm {
+  readonly email: string;
 }
 
-type Route = RouteComponentProps<RouteProps>;
-
 const ForgotPasswordScreen = () => {
-  const location = useLocation<AuthLocationState>();
-  const {
-    match: {
-      params: { email }
-    }
-  }: Route = useRouter();
+  const location = useLocation<(AuthLocationState & ResetPasswordLocationState) | undefined>();
+  const { email } = location.state || {};
   const [emailResource, setEmailResource] = useState<WriteResource<ForgotPasswordForm, void>>({
     data: {
       email: email === undefined ? "" : email
diff --git a/src/client/screens/UserAccountScreen.tsx b/src/client/screens/UserAccountScreen.tsx
index 82759ef1..b10a8747 100644
--- a/src/client/screens/UserAccountScreen.tsx
+++ b/src/client/screens/UserAccountScreen.tsx
@@ -278,7 +278,7 @@ const UserAccountScreen = () => {
                   <Text>Forgot your password?</Text>{" "}
                   <Themed.a
                     as={RouterLink}
-                    to={{ pathname: `/forgot-password/${data.email}` }}
+                    to={{ pathname: `/forgot-password/`, state: { email: data.email } }}
                     sx={{ cursor: "pointer", color: "blue.5" }}
                   >
                     Reset password
```

2022-06-16 16:56 UTC, aaronxsu commented
@maurizi I agree with the suggestions. I believe they are addressed in the latest commit. Please feel free to re-review.

2022-06-16 17:34 UTC, maurizi approved these changes
Looks good 👍 

Just a few small changes I missed in the first review, but they're pretty trivial, feel free to merge this after addressing them.

2022-06-16 17:34 UTC, maurizi commented on src/client/screens/UserAccountScreen.tsx
> +      } catch (errors: any) {
Since we don't log or capture the error, we don't need to catch it (which will also get rid of a warning about using the `any` type).
```suggestion
      } catch {
```

2022-06-16 17:34 UTC, maurizi commented on src/client/screens/UserAccountScreen.tsx
> +                      districtbuilder@azavea.com
Let's make use of the constant here too:
```suggestion
                      {accountDeleteEmail}
```

2022-06-16 18:18 UTC, merged