Updates to data processing script docs
PublicMapping/districtbuilder pull request #1262
Opened 2022-08-30 18:01 UTC by lukemckinstry

## Overview

This PR makes additions to the docs for working with the data processing scripts. 

### Notes

The `description` for most of the data processing commands was being omitted from the docs by the auto-generated script, adding those back to the docs makes each command more clear. Beyond that, adding more contextual info or example use cases may be helpful, so ideally a developer with experience earlier in the project & using the processing scripts could take a pass and add that info (to the data processing docs and/or the main repo docs) if necessary.

## Testing Instructions

- Review updates to docs in [`src/manage/README.md`](https://github.com/PublicMapping/districtbuilder/tree/develop/src/manage#districtbuilder-command-line-interface)
- The [`Development Data`](https://github.com/PublicMapping/districtbuilder#development-data) section of the main repo docs ([`README.md`](https://github.com/PublicMapping/districtbuilder#districtbuilder)) should also be reviewed, adding additional contextual info or use case examples about the data processing scripts may be warranted.

Closes #1242

2022-09-01 21:26 UTC, aaronxsu reviewed
The docs added make sense to me. I will leave it to Mike to check with fuller context to see if the fields suffice for the input data.

2022-09-06 21:14 UTC, maurizi requested changes
Thanks for the documentation updates @lukemckinstry!

I left some feedback on where I'd like to see it expanded - mostly it centers around documenting use cases outside US state-level data (e.g. international data, municipal instead of state-level, custom geography).

2022-09-06 21:14 UTC, maurizi commented on README.md
> +When the GeoJSON is ready, use `process-geojson` to process the data and `publish-geojson` to publish the region to S3. In `process-geojson` the `--demographic` field specifies the columns to upload
Expanded on this a bit, but maybe the last section would work better w/ an example?

```suggestion
When the GeoJSON is ready, use `process-geojson` to process the data and `publish-geojson` to publish the region to S3. 

In `process-geojson` the `--demographic` field specifies the columns to upload as demographic data, and multiple groups of demographic data can be uploaded (e.g. CVAP, etc.).

The `--levels` field specifies properties in the GeoJSON containing identifiers for other levels of geographic details. For example `--levels block,blockgroup` should be used when the input GeoJSON is at the `block` level and you wish to generate a `blockgroup` layer in addition to the `block` layer by combining all Blocks w/ the same `blockgroup` ID. 
```

2022-09-22 20:34 UTC, lukemckinstry commented
Added examples for how to format GeoJSON that a user creates or acquires to be fed to `process-geojson`. The examples include a US state using census boundaries, and a region using precinct boundaries. I looked into the reapportionment/redistribution processes & data for several other countries (UK, Canada, Australia) but was unable to find a relevant example of public redistricting processes like the USA.

2022-09-22 21:25 UTC, maurizi approved these changes
Just one small typo but this is looking great otherwise 👍

2022-09-23 12:58 UTC, merged