Edit project name
PublicMapping/districtbuilder pull request #488
Opened 2020-10-23 13:13 UTC by maurizi

## Overview

Adds ability to edit project names inline in the project screen header

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

when the page is loaded:
![localhost_3003_projects_e1cb7dfc-eafb-4566-bbec-9c325aae58ce (4)](https://user-images.githubusercontent.com/4432106/97007373-4f0ee100-150f-11eb-937a-93dc6dde5591.png)

editing:
![localhost_3003_projects_e1cb7dfc-eafb-4566-bbec-9c325aae58ce (3)](https://user-images.githubusercontent.com/4432106/97007374-4f0ee100-150f-11eb-9925-397381f769ab.png)

save button disabled when name is empty:
![localhost_3003_projects_e1cb7dfc-eafb-4566-bbec-9c325aae58ce (5)](https://user-images.githubusercontent.com/4432106/97007370-4e764a80-150f-11eb-9058-ddec6a3dc5c9.png)

### Notes

This is based on top of #484, I'll retarget it to `develop` once that is merged.

## Testing Instructions

- `scripts/server`
- Ensure you can edit project names
- Ensure that reloading the project screen shows your changes have persisted
- Attempt to set a project name to an empty string - the save button should be disabled
- The project name should continue to be read-only and show the map creator's name when viewing another user's project

Closes #220

2020-10-26 15:09 UTC, pcaisse requested changes
I'm seeing some behavior that I don't quite understand. I'm not sure if I did something wrong, but I was on the `feature/mvm/persist-locked-districts` branch before this and had run `./scripts/update`. The patch request is failing for me, though apparently not all the time:

![db_rename](https://user-images.githubusercontent.com/2926237/97189990-9a2d2c00-177b-11eb-8ba0-1aa03514f8c0.gif)

2020-10-26 16:38 UTC, maurizi commented on src/client/components/ProjectName.tsx
> +              void patchProject(project.id, { name })
Yeah - I was trying to avoid a broader refactor to our Redux usage, but maybe that is unavoidable.

Maybe it would make sense to pair w/ `updateDistrictsDefinition` action an action for updating non-districts project data (which won't need to refetch geojson)? It could take a `Exclude<IProject, "districtsDefiniton">` as a parameter

2020-10-26 17:03 UTC, pcaisse commented on src/client/components/ProjectName.tsx
> +              void patchProject(project.id, { name })
Yeah, that makes sense to me!

2020-10-27 17:00 UTC, maurizi commented
@pcaisse this is ready for another look

2020-10-28 13:28 UTC, pcaisse approved these changes
Works like a dream! :cloud:

2020-10-30 13:21 UTC, merged