Show error page for 404 errors on project and organization screens
PublicMapping/districtbuilder pull request #582
Opened 2021-02-18 22:03 UTC by kevinearldenny

## Overview

Displays an error screen on the Project or Organization pages if a user attempts to navigate to an entity (project / organization) that does not exist. 

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

![image](https://user-images.githubusercontent.com/66973361/108427042-929e0100-720a-11eb-9b26-ce14d5811743.png)
![image](https://user-images.githubusercontent.com/66973361/108427091-a47fa400-720a-11eb-9b8e-c4018117ddcb.png)

### Notes

I'm not entirely sure about how to handle the current toast notification that appears when a fetch error occurs. It seems like if nothing else, the copy should be updated here - since refreshing will not change the fact that the organization or project does not exist. But, I imagine that we want this to be displayed in the event that there is an unexpected failure when fetching a project that _does_ exist...

Also, we may need a little finessing on the style here @jfrankl 

## Testing Instructions

- `./scripts/update`
- Attempt to navigate to a URL for a project that does not exist, e.g. [http://localhost:3003/projects/777](http://localhost:3003/projects/777)
- Attempt to navigate to a URL for an organization that does not exist, e.g. [http://localhost:3003/o/FAKE](http://localhost:3003/o/FAKE)

Closes #561

2021-02-19 20:05 UTC, jfrankl commented
Nice! I have a few design changes:

- Remove the "DistrictBuilder" logo from just above the "Page not found" box, since that information is in the header
- Left align all text
- @tgilcrest could you take a shot at the copy for this?

2021-02-23 22:25 UTC, maurizi requested changes
> I'm not entirely sure about how to handle the current toast notification that appears when a fetch error occurs. It seems like if nothing else, the copy should be updated here - since refreshing will not change the fact that the organization or project does not exist. But, I imagine that we want this to be displayed in the event that there is an unexpected failure when fetching a project that does exist...

The way this is implemented, _any_ error on an organization or project page will result in displaying a "not found" page - even an error _updating_ an existing project, like a transient server error.

We should only show this page specifically for 404 errors.

2021-02-23 22:35 UTC, maurizi commented on src/client/screens/PageNotFoundScreen.tsx
> +          The {"errorMessage" in organization ? "organization" : "project"} you are looking for
Rather than determining what to show here based on the Redux state, I think it might be less brittle to handle this via a prop when the component is used, e.g.
```
<PageNotFoundScreen model="organization" />
```

2021-02-24 20:01 UTC, kevinearldenny commented
> > I'm not entirely sure about how to handle the current toast notification that appears when a fetch error occurs. It seems like if nothing else, the copy should be updated here - since refreshing will not change the fact that the organization or project does not exist. But, I imagine that we want this to be displayed in the event that there is an unexpected failure when fetching a project that does exist...
> 
> The way this is implemented, _any_ error on an organization or project page will result in displaying a "not found" page - even an error _updating_ an existing project, like a transient server error.
> 
> We should only show this page specifically for 404 errors.

Hmmm, so malformed requests are currently returning a 400 error. Is it fair to handle these sorts of errors like:

"errorMessage" in state.project.projectData && state.project.projectData.errorMessage && `state.project.projectData.errorMessage === "Request failed with status code 400"`?

2021-02-24 20:22 UTC, maurizi commented
> Hmmm, so malformed requests are currently returning a 400 error. Is it fair to handle these sorts of errors like:
> `"errorMessage" in state.project.projectData && state.project.projectData.errorMessage && state.project.projectData.errorMessage === "Request failed with status code 400"?`

That seems brittle and likely to break if this automatically generated message were to change for some reason (e.g. a browser / library upgrade).

We should refactor the error data passed through to include the status code along with or instead of the existing `errorMessage`. I don't think we actually display the `errorMessage` anywhere right now just check for its presence, so that shouldn't be too hard.

2021-02-24 21:18 UTC, kevinearldenny commented
> > Hmmm, so malformed requests are currently returning a 400 error. Is it fair to handle these sorts of errors like:
> > `"errorMessage" in state.project.projectData && state.project.projectData.errorMessage && state.project.projectData.errorMessage === "Request failed with status code 400"?`
> 
> That seems brittle and likely to break if this automatically generated message were to change for some reason (e.g. a browser / library upgrade).
> 
> We should refactor the error data passed through to include the status code along with or instead of the existing `errorMessage`. I don't think we actually display the `errorMessage` anywhere right now just check for its presence, so that shouldn't be too hard.

Okay, I refactored for `errorMessage` to display the status code from the error response.

2021-02-24 23:44 UTC, kevinearldenny commented on src/client/screens/ProjectScreen.tsx
> +    ),
@maurizi I decided to leave this as 'working' with the Redux architecture that you proposed, and since there are a few other outstanding things on this page around error handling split up the 400 vs 404 error piece into a separate issue: https://github.com/PublicMapping/districtbuilder/issues/595

2021-02-25 14:45 UTC, maurizi approved these changes

2021-02-25 15:25 UTC, merged