Require users to confirm understanding before joining an organization
PublicMapping/districtbuilder pull request #593
Opened 2021-02-23 19:29 UTC by kevinearldenny

## Overview

- When a user has not joined an organization and they click on "Join Organization" on that organization's page, there is a confirmation modal that displays text and asks them to confirm joining the organization
- When a user has not joined an organization and they click on any "Use this template" button on that organization's page, there is a confirmation modal that displays text and asks them to confirm joining the organization.
-  The user cannot start a template map for an organization without joining

### Checklist

- [ x ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

![image](https://user-images.githubusercontent.com/66973361/108896349-cd28e480-75e2-11eb-830a-170453fdc62f.png)

### Notes

Does it make sense to possibly disable the 'Use Template' button and have a tooltip text indicating that the user must join and organization first? Like we did in #591 

## Testing Instructions

- Navigate to an organization page and attempt to join
- Expected: JoinOrganization modal should open. If you are logged in, there will be a confirmation dialog asking you to confirm your understanding of how organizations work

Closes #587

2021-02-23 19:37 UTC, tgilcrest commented
>Does it make sense to possibly disable the 'Use Template' button and have a tooltip text indicating that the user must join and organization first? Like we did in #591

Would this be a better approach than the current one that makes the modal appear?

2021-02-23 21:33 UTC, kevinearldenny commented
> > Does it make sense to possibly disable the 'Use Template' button and have a tooltip text indicating that the user must join and organization first? Like we did in #591
> 
> Would this be a better approach than the current one that makes the modal appear?

My thought is probably yes, since it doesn't seem wholly intuitive that a button titled 'Use Template' would trigger a modal to join an organization. @jfrankl , what do you think about this?

2021-02-23 21:55 UTC, jfrankl commented
> > > Does it make sense to possibly disable the 'Use Template' button and have a tooltip text indicating that the user must join and organization first? Like we did in #591
> > 
> > 
> > Would this be a better approach than the current one that makes the modal appear?
> 
> My thought is probably yes, since it doesn't seem wholly intuitive that a button titled 'Use Template' would trigger a modal to join an organization. @jfrankl , what do you think about this?

I'd like to stick with the proposed design, which invites the user to sign up for DistrictBuilder when they try to "Use the template". Clicking on a button in an application and having that trigger sign up is a common pattern, and I suspect users will understand what is going on. By jumping straight to the sign up, we are saving them from needing to think "okay, I need to join ... how do I do that?" and clicking a second button.

2021-02-23 22:32 UTC, maurizi commented on src/shared/entities.d.ts
> +}
Why did you add this new `IUserOrganization` type instead of just adding this to the `IUser` interface?

2021-02-23 22:39 UTC, kevinearldenny commented on src/shared/entities.d.ts
> +}
I initially tried adding this into `IUser`, I ended up encountering a number of circuitous type errors - which may have been a result of `IUser` being nested under `IOrganization` already

2021-02-23 22:45 UTC, maurizi commented on src/client/components/JoinOrganizationModal.tsx
> +import ConfirmJoinOrganization from "./ConfirmJoinOrganization";
This file doesn't seem to have been committed,

2021-02-23 22:48 UTC, maurizi commented on src/shared/entities.d.ts
> +}
I ran into one type error but it was pretty easy to sort out?
```diff
diff --git a/src/server/src/auth/services/auth.service.ts b/src/server/src/auth/services/auth.service.ts
index 7840a50..b383ab2 100644
--- a/src/server/src/auth/services/auth.service.ts
+++ b/src/server/src/auth/services/auth.service.ts
@@ -65,7 +65,8 @@ export class AuthService {
       name: user.name,
       email: user.email,
       isEmailVerified: user.isEmailVerified,
-      hasSeenTour: user.hasSeenTour
+      hasSeenTour: user.hasSeenTour,
+      organizations: user.organizations
     };
     return this.jwtService.sign(payload);
   }
diff --git a/src/server/src/users/entities/user.entity.ts b/src/server/src/users/entities/user.entity.ts
index 5977297..dab4527 100644
--- a/src/server/src/users/entities/user.entity.ts
+++ b/src/server/src/users/entities/user.entity.ts
@@ -1,11 +1,11 @@
 import bcrypt from "bcrypt";
 import { Exclude } from "class-transformer";
 import { Column, Entity, PrimaryGeneratedColumn, ManyToMany } from "typeorm";
-import { IUserOrganization } from "../../../../shared/entities";
+import { IUser } from "../../../../shared/entities";
 import { BCRYPT_SALT_ROUNDS } from "../../common/constants";
 import { Organization } from "../../organizations/entities/organization.entity";
 @Entity()
-export class User implements IUserOrganization {
+export class User implements IUser {
   @PrimaryGeneratedColumn("uuid")
   id: string;
 
diff --git a/src/shared/entities.d.ts b/src/shared/entities.d.ts
index 8d7c17f..c5bb9fc 100644
--- a/src/shared/entities.d.ts
+++ b/src/shared/entities.d.ts
@@ -4,17 +4,14 @@ export type UserId = string;
 
 export type PublicUserProperties = "id" | "name";
 
+export type OrganizationNest = Pick<IOrganization, "slug" | "id">;
+
 export interface IUser {
   readonly id: UserId;
   readonly email: string;
   readonly name: string;
   readonly isEmailVerified: boolean;
   readonly hasSeenTour: boolean;
-}
-
-export type OrganizationNest = Pick<IOrganization, "slug" | "id">;
-
-export interface IUserOrganization extends IUser {
   readonly organizations: readonly OrganizationNest[];
 }
 
```

2021-02-24 15:55 UTC, maurizi commented on src/shared/entities.d.ts
> +}
A few small typing issues but nothing big - you forgot to update wrap one of your variables w/ `Resource` (this was an issue w/ `IUserOrganization` too and is causing CI to fail) and I needed to update the JWT code on the backend:
```diff
diff --git a/src/client/actions/user.ts b/src/client/actions/user.ts
index b708a6b..cfd6e2d 100644
--- a/src/client/actions/user.ts
+++ b/src/client/actions/user.ts
@@ -1,6 +1,6 @@
 import { createAction } from "typesafe-actions";
-import { IUserOrganization } from "../../shared/entities";
+import { IUser } from "../../shared/entities";
 
 export const userFetch = createAction("User fetch")();
-export const userFetchSuccess = createAction("User fetch success")<IUserOrganization>();
+export const userFetchSuccess = createAction("User fetch success")<IUser>();
 export const userFetchFailure = createAction("User fetch failure")<string>();
diff --git a/src/client/api.ts b/src/client/api.ts
index a465ee1..51559fb 100644
--- a/src/client/api.ts
+++ b/src/client/api.ts
@@ -7,7 +7,6 @@ import {
   IProject,
   IRegionConfig,
   IUser,
-  IUserOrganization,
   JWT,
   OrganizationSlug,
   ProjectId,
@@ -51,7 +50,7 @@ export async function authenticateUser(email: string, password: string): Promise
   });
 }
 
-export async function fetchUser(): Promise<IUserOrganization> {
+export async function fetchUser(): Promise<IUser> {
   return new Promise((resolve, reject) => {
     apiAxios
       .get("/api/user")
diff --git a/src/client/components/JoinOrganizationModal.tsx b/src/client/components/JoinOrganizationModal.tsx
index adfb0e3..6ee2ed1 100644
--- a/src/client/components/JoinOrganizationModal.tsx
+++ b/src/client/components/JoinOrganizationModal.tsx
@@ -7,6 +7,7 @@ import { Box, jsx, ThemeUIStyleObject } from "theme-ui";
 import { IOrganization, IUser } from "../../shared/entities";
 import { showCopyMapModal } from "../actions/districtDrawing";
 import { State } from "../reducers";
+import { Resource } from "../resource";
 import store from "../store";
 import { AuthModalContent } from "./AuthComponents";
 import ConfirmJoinOrganization from "./ConfirmJoinOrganization";
@@ -41,7 +42,7 @@ const JoinOrganizationModal = ({
 }: {
   readonly organization: IOrganization;
   readonly showModal: boolean;
-  readonly user: IUser;
+  readonly user: Resource<IUser>;
 }) => {
   const hideModal = () => store.dispatch(showCopyMapModal(false));
 
diff --git a/src/client/reducers/user.ts b/src/client/reducers/user.ts
index 93f6ad2..f661605 100644
--- a/src/client/reducers/user.ts
+++ b/src/client/reducers/user.ts
@@ -4,12 +4,12 @@ import { getType } from "typesafe-actions";
 import { Action } from "../actions";
 import { userFetch, userFetchFailure, userFetchSuccess } from "../actions/user";
 
-import { IUserOrganization } from "../../shared/entities";
+import { IUser } from "../../shared/entities";
 import { fetchUser } from "../api";
 import { showResourceFailedToast } from "../functions";
 import { Resource } from "../resource";
 
-export type UserState = Resource<IUserOrganization>;
+export type UserState = Resource<IUser>;
 
 export const initialState = {
   isPending: false
diff --git a/src/server/src/auth/services/auth.service.ts b/src/server/src/auth/services/auth.service.ts
index 7840a50..b383ab2 100644
--- a/src/server/src/auth/services/auth.service.ts
+++ b/src/server/src/auth/services/auth.service.ts
@@ -65,7 +65,8 @@ export class AuthService {
       name: user.name,
       email: user.email,
       isEmailVerified: user.isEmailVerified,
-      hasSeenTour: user.hasSeenTour
+      hasSeenTour: user.hasSeenTour,
+      organizations: user.organizations
     };
     return this.jwtService.sign(payload);
   }
diff --git a/src/server/src/users/entities/user.entity.ts b/src/server/src/users/entities/user.entity.ts
index 5977297..dab4527 100644
--- a/src/server/src/users/entities/user.entity.ts
+++ b/src/server/src/users/entities/user.entity.ts
@@ -1,11 +1,11 @@
 import bcrypt from "bcrypt";
 import { Exclude } from "class-transformer";
 import { Column, Entity, PrimaryGeneratedColumn, ManyToMany } from "typeorm";
-import { IUserOrganization } from "../../../../shared/entities";
+import { IUser } from "../../../../shared/entities";
 import { BCRYPT_SALT_ROUNDS } from "../../common/constants";
 import { Organization } from "../../organizations/entities/organization.entity";
 @Entity()
-export class User implements IUserOrganization {
+export class User implements IUser {
   @PrimaryGeneratedColumn("uuid")
   id: string;
 
diff --git a/src/shared/entities.d.ts b/src/shared/entities.d.ts
index 8d7c17f..c5bb9fc 100644
--- a/src/shared/entities.d.ts
+++ b/src/shared/entities.d.ts
@@ -4,17 +4,14 @@ export type UserId = string;
 
 export type PublicUserProperties = "id" | "name";
 
+export type OrganizationNest = Pick<IOrganization, "slug" | "id">;
+
 export interface IUser {
   readonly id: UserId;
   readonly email: string;
   readonly name: string;
   readonly isEmailVerified: boolean;
   readonly hasSeenTour: boolean;
-}
-
-export type OrganizationNest = Pick<IOrganization, "slug" | "id">;
-
-export interface IUserOrganization extends IUser {
   readonly organizations: readonly OrganizationNest[];
 }
 ```

2021-02-25 14:30 UTC, maurizi requested changes
This is looking really good 🎉 

One piece that wasn't spelled out in the acceptance criteria that I think we want as part of this change - after the modal appears when I click "Use this template" and then clicking "Join Organization", I wasn't expecting to need to click "Use this template" again.

2021-02-25 16:56 UTC, maurizi approved these changes
Working great! 🎉

2021-02-25 18:47 UTC, merged