Add verify and join org link to verification email
PublicMapping/districtbuilder pull request #616
Opened 2021-03-08 16:51 UTC by kevinearldenny

## Overview

When a new user attempts to sign up for an account and join an organization from an organization's page, they are automatically added to the Organization as an 'unverified user'. If an unverified user views their organization's page before confirming their email, they are prompted to confirm their email.

### Checklist

- [x] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

![image](https://user-images.githubusercontent.com/66973361/110352853-681eb700-8004-11eb-96c3-70bb4460e91b.png)

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

- Ensure that you are not logged in with an existing user account
- Navigate to an organization page (e.g., http://localhost:3003/o/mikes-maps)
- Click 'Join Organization' and fill in credentials not associated with an existing user

Closes #586

2021-03-08 16:59 UTC, maurizi commented on src/client/screens/OrganizationScreen.tsx
> +      )}
Refactoring this banner was supposed to be tackled by https://github.com/PublicMapping/districtbuilder/issues/609 but in any case, we should just copy/paste the markup here - we're already sharing the `SiteHeader` component between the two pages, we should just _move_ [this code in `HomeScreen`](https://github.com/PublicMapping/districtbuilder/blob/develop/src/client/screens/HomeScreen.tsx#L78-L120) into `SiteHeader` as well and we won't need these changes.

2021-03-08 22:23 UTC, kevinearldenny commented on src/client/screens/OrganizationScreen.tsx
> +      )}
Gotcha, okay - guess it probably makes sense to pull #609 into this PR as well

2021-03-09 18:08 UTC, kevinearldenny commented
@maurizi Merge conflicts are now resolved here, ready for review

2021-03-09 18:27 UTC, maurizi requested changes

2021-03-09 18:27 UTC, maurizi commented on src/client/screens/OrganizationScreen.tsx
> +                <div></div>
I don't think you meant to get rid of the Join button for logged out users?
```suggestion
                joinButton
```

2021-03-09 18:27 UTC, maurizi commented on src/client/screens/OrganizationScreen.tsx
> +                  </Box>
This is not correct - the tooltip should be wrapped around the `<Button>`, not the `<TemplateCard>` component created in #615.

2021-03-12 14:58 UTC, maurizi requested changes
The main functionality of storing intent to join an organization as part of registering is working, and I was able to activate my account and was a part of the organization.

This is still missing the feature to redirect to the organization upon activation, as per the wireframes on Abstract:
![image](https://user-images.githubusercontent.com/4432106/110956746-f0f56580-8318-11eb-9a33-ed25ea2ee356.png)

As we discussed offline that will likely require some kind of new flag on `User` so we don't show that modal again, or thinking about it a bit more - storing a separate FK field on `User` for organization(s)-to-join instead of reusing the existing `organizations` M2M field could serve this purpose as well (I think you originally suggested this).

2021-03-15 15:46 UTC, maurizi approved these changes

2021-03-15 19:44 UTC, merged