Display featured projects on Org screen
PublicMapping/districtbuilder pull request #633
Opened 2021-03-18 15:24 UTC by kevinearldenny

## Overview

Displays all of an Organization's featured projects in cards on the Organization screen, including thumbnail maps showing the outlines of all of the districts created within the project. 

- Move OrgProject type and refactor references
- Add featured projects cards
- format
- Clean up lint

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

![image](https://user-images.githubusercontent.com/66973361/111651015-3e237c80-87dc-11eb-9af3-33b541d7d1e7.png)

## Testing Instructions

- Ensure that you have a user, organization, and a project associated with the organization's template
- Navigate to the organization's admin page, and set the project as featured
- Go back to the main organization page - expect that district plans are displayed in cards underneath the organization's templates

Closes #565

2021-03-18 15:30 UTC, kevinearldenny commented on src/client/components/FeaturedProjectCard.tsx
> +      center: [-75.16, 39.95],
I'm wondering if this should be removed, or if there is some way that we could dynamically compute the center... there is a weird flicker of sorts currently when loading the maps

2021-03-18 15:32 UTC, kevinearldenny commented on docker-compose.yml
> +      - 5432:5432
@maurizi It looks like this is throwing a build error

2021-03-18 15:42 UTC, maurizi commented on docker-compose.yml
> +      - 5432:5432
Yes - it is probably causing port conflicts on CI, which has its own PSQL database running. We take care to not have port conflicts for this reason (https://github.com/azavea/geospatial-apps/blob/master/project_ports.md).

I only recommended you add this for temporary debugging purposes - if you want to expose the database locally for development/testing long-term you should set up a non-standard port that won't conflict, document it on our ports page, and configure your local SQL tool to use that port.

2021-03-18 15:52 UTC, maurizi commented on src/client/components/FeaturedProjectCard.tsx
> +      "pk.eyJ1IjoiZGlzdHJpY3RidWlsZGVyIiwiYSI6ImNrZXZzeXlvMjIxb2QycW1yeGpuMDJ2ZGwifQ.FdOGNk3y1BPkGvF_yCjjGQ";
We shouldn't duplicate this `accessToken` constant that is also defined in `Map.tsx` - we should move it to a common location (maybe a new `constants/map.ts` file)?

2021-03-18 15:52 UTC, maurizi commented on src/client/components/FeaturedProjectCard.tsx
> +      style: "mapbox://styles/districtbuilder/ckexc26lz0d3k19owrswhxz9o",
Similar to `accessToken` above - lets not duplicate this constant.

2021-03-18 15:54 UTC, maurizi commented on src/client/screens/OrganizationScreen.tsx
> +}
Since this is identical to the function in `OrganizationAdminScreen.tsx`, you should refactor this so they both use the _same_ helper function.

2021-03-18 17:41 UTC, maurizi requested changes

2021-03-19 21:22 UTC, kevinearldenny commented on src/client/screens/OrganizationScreen.tsx
> +import { organizationFeaturedProjectsFetch } from "../actions/organizationProjects";
Organization screen now only fetches Featured Projects

2021-03-19 21:23 UTC, kevinearldenny commented on src/server/src/organizations/services/organizations.service.ts
> +  async getOrgAndProjectTemplates(slug: string): Promise<Organization | undefined> {
Renamed service to reflect what is actually getting returned here

2021-03-19 21:26 UTC, kevinearldenny commented on src/server/src/project-templates/controllers/project-templates.controller.ts
> +  }
Hopefully this is an acceptable admin guard? I was debating implementing this with a NestJS 'guard', but this seems to do the job fine and I'm not sure that we're going to need to reuse Admin gating across any other components

2021-03-19 21:28 UTC, kevinearldenny commented on src/server/src/project-templates/services/project-templates.service.ts
> +        "projects.districts",
```suggestion
```

Should this be removed?

2021-03-23 13:32 UTC, maurizi commented on src/server/src/project-templates/services/project-templates.service.ts
> +        "projects.districts",
Hmmm - so I'm of two minds here - ideally I'd say to go through the `/api/projects/:id/export/geojson` endpoint to get these districts for the map preview, for a few reasons:
 - To abstract away our caching mechanism
 - We can't cleanly type this field in our shared interface, bc of #179.
 - We'd like to make the map preview component reusable in situations where directly getting the `districts` from the backend along w/ the project might be undesirable (e.g. the admin featured projects list, the home screen of an extremely prolific mapper, etc.).
 
 That said, it seems _fine_ here for now where we have at most 12 projects, so if you want to leave a larger refactor of this to when we try and reuse this map component in a later PR that's OK by me.

2021-03-23 13:32 UTC, maurizi commented on src/client/components/FeaturedProjectCard.tsx
> +    // eslint-disable-next-line
We got rid of the "no ifs" rule:
```suggestion
```

2021-03-23 13:32 UTC, maurizi commented on src/client/components/FeaturedProjectCard.tsx
> +      center: [-75.16, 39.95],
You can just pass `bounds` in to the `Map` constructor (also added in `interactive: false` here as well, which will prevent panning/zooming/etc.):
```diff
diff --git a/src/client/components/FeaturedProjectCard.tsx b/src/client/components/FeaturedProjectCard.tsx
index 81b4e70..ea9f6ce 100644
--- a/src/client/components/FeaturedProjectCard.tsx
+++ b/src/client/components/FeaturedProjectCard.tsx
@@ -5,6 +5,7 @@ import MapboxGL from "mapbox-gl";
 import { useEffect, useRef, useState } from "react";
 import bbox from "@turf/bbox";
 import { MAPBOX_STYLE, MAPBOX_TOKEN } from "../constants/map";
+import { BBox2d } from "@turf/helpers/lib/geojson";
 
 const style = {
   featuredProject: {
@@ -33,7 +34,6 @@ const FeaturedProjectCard = ({ project }: { readonly project: OrgProject }) => {
   const [mapLoaded, setMapLoaded] = useState<boolean>(false);
 
   useEffect(() => {
-    // eslint-disable-next-line
     if (mapRef.current === null) {
       return;
     }
@@ -41,12 +41,15 @@ const FeaturedProjectCard = ({ project }: { readonly project: OrgProject }) => {
     // eslint-disable-next-line
     MapboxGL.accessToken = MAPBOX_TOKEN;
 
+    const bounds = project.districts && (bbox(project.districts) as BBox2d);
     const map = new MapboxGL.Map({
       container: mapRef.current,
       style: MAPBOX_STYLE,
+      bounds,
       fitBoundsOptions: { padding: 20 },
       minZoom: 5,
-      maxZoom: 5
+      maxZoom: 5,
+      interactive: false
     });
 
     map.on("load", function() {
@@ -64,10 +67,6 @@ const FeaturedProjectCard = ({ project }: { readonly project: OrgProject }) => {
           "line-color": "#000"
         }
       });
-      const bounds = project.districts && bbox(project.districts);
-
-      // @ts-ignore
-      bounds && map.fitBounds(bounds);
 
       setMapLoaded(true);
     });
```

2021-03-23 13:35 UTC, maurizi requested changes
A few small cleanups left to make here (in re: to https://github.com/PublicMapping/districtbuilder/pull/633/files#discussion_r599546755 its fine if you if you want to leave it as-is now for now and we can refactor further in https://github.com/PublicMapping/districtbuilder/issues/537)

2021-03-23 16:00 UTC, kevinearldenny commented on src/server/src/project-templates/services/project-templates.service.ts
> +        "projects.districts",
I am using `districtsDefinition` here in the context of https://github.com/PublicMapping/districtbuilder/issues/608

2021-03-23 16:00 UTC, kevinearldenny commented on src/server/src/project-templates/services/project-templates.service.ts
> +        "projects.districtsDefinition",
I am using `districtsDefinition` in the context of https://github.com/PublicMapping/districtbuilder/issues/608

2021-03-23 16:28 UTC, maurizi commented on src/server/src/project-templates/services/project-templates.service.ts
> +        "projects.districts",
But Evaluate mode's county split isn't getting it's project data from this endpoint, surely? We fetch directly from `/api/projects/:id` on the Project page. I'm not sure I understand.

2021-03-23 17:35 UTC, maurizi commented on src/server/src/projects/controllers/projects.controller.ts
> +    });
I don't actually think we want these changes - all `getReadOnlyView()` really does is obscure the contents of `lockedDistricts` which we want to do for Organizaton administrators as well.

2021-03-23 17:37 UTC, maurizi approved these changes
Ok, one last change (which is just a revert of a change you just made, so no need for another review cycle) and this is good to go.

2021-03-23 18:30 UTC, merged