Allow a user to create a project from an organization's template from the Create Project screen
PublicMapping/districtbuilder pull request #638
Opened 2021-03-19 21:46 UTC by kevinearldenny

## Overview

- Refactors `OrganizationTemplates` and `TemplateCard` into a new component outside of `OrganizationScreen`
- Renders `OrganizationTemplates` component in `CreateProjectScreen` to allow users to create a project from a template

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

![image](https://user-images.githubusercontent.com/66973361/111845229-d142dc00-88da-11eb-9aae-7ff98597799e.png)
![image](https://user-images.githubusercontent.com/66973361/111845254-dd2e9e00-88da-11eb-8f60-7bb442ca275b.png)

### Notes

- I still haven't tested this with multiple templates / multiple organizations, but I see no reason why it shouldn't work, conceptually. May need to do a bit of styling fix-up, but I think it's in the right direction currently.
- There are gonna be some gnarly merge conflicts with #633 here on `OrganizationScreen`. Am wondering which way it will be easier to resolve these - since the refactor of `OrganizationTemplates` is in this branch, it might make sense to merge this one in first?

## Testing Instructions

- With a user who has joined an organization that has at least one template - click 'New Map' from the home screen
- Expect: list of organizations you are a part of to be displayed
- Select the radio button for one of your organizations
- Expect: organization project templates displayed
- Click on a template to create a new project
- Expect: new project created from template

Closes #598

2021-03-25 17:38 UTC, maurizi requested changes
Sorry for the delayed review on this!

This is mostly looking great, just missing a few pieces 🎉

2021-03-25 17:38 UTC, maurizi commented on src/client/screens/CreateProjectScreen.tsx
>      store.dispatch(regionConfigsFetch());
We need to fetch the user when this page loads now, or the organization section won't appear on a page refresh:
```diff
diff --git a/src/client/screens/CreateProjectScreen.tsx b/src/client/screens/CreateProjectScreen.tsx
index 4629779..c4f3d95 100644
--- a/src/client/screens/CreateProjectScreen.tsx
+++ b/src/client/screens/CreateProjectScreen.tsx
@@ -20,6 +20,7 @@ import { ReactComponent as Logo } from "../media/logos/mark-white.svg";
 import { IProject, IRegionConfig, IChamber, OrganizationSlug } from "../../shared/entities";
 import { regionConfigsFetch } from "../actions/regionConfig";
 import { organizationFetch } from "../actions/organization";
+import { userFetch } from "../actions/user";
 import { createProject } from "../api";
 import { InputField, SelectField } from "../components/Field";
 import FormError from "../components/FormError";
@@ -66,6 +67,7 @@ interface InvalidForm extends ProjectForm {
 const CreateProjectScreen = ({ regionConfigs, user, organization }: StateProps) => {
   useEffect(() => {
     store.dispatch(regionConfigsFetch());
+    store.dispatch(userFetch());
   }, []);
   const [createProjectResource, setCreateProjectResource] = useState<
     WriteResource<ProjectForm, IProject>
```

2021-03-25 17:38 UTC, maurizi commented on src/client/screens/CreateProjectScreen.tsx
> +                <Radio name="organization" value="" onChange={onOrgChanged} />
We should default to "No organization " being checked, rather than having neither radio selected:
```diff
diff --git a/src/client/screens/CreateProjectScreen.tsx b/src/client/screens/CreateProjectScreen.tsx
index 4629779..3f0a018 100644
--- a/src/client/screens/CreateProjectScreen.tsx
+++ b/src/client/screens/CreateProjectScreen.tsx
@@ -254,7 +254,12 @@ const CreateProjectScreen = ({ regionConfigs, user, organization }: StateProps)
               key="custom"
             >
               <Label>
-                <Radio name="organization" value="" onChange={onOrgChanged} />
+                <Radio
+                  name="organization"
+                  value=""
+                  onChange={onOrgChanged}
+                  checked={organizationSlug === undefined}
+                />
                 <Flex as="span" sx={{ flexDirection: "column" }}>
                   <div sx={style.radioHeading}>No organization</div>
                   <div sx={style.radioSubHeading}>Continue without an organization</div>
```

2021-03-25 17:38 UTC, maurizi commented on src/client/screens/CreateProjectScreen.tsx
>          <Flex sx={style.formContainer}>
As per the wireframes, we shouldn't show the main form if the user opts to create a project from an organization template - we should _only_ show the template section in that case.

2021-03-30 13:45 UTC, maurizi commented
@kevinearldenny now that #649 has been merged do you think you'd be up for reworking this to match the existing styling on this page?

2021-03-30 19:40 UTC, kevinearldenny commented
@maurizi @jfrankl Does this component look right in both of these places?

![image](https://user-images.githubusercontent.com/66973361/113046573-3b2a7380-916e-11eb-8cce-039a2c5bcd75.png)

![image](https://user-images.githubusercontent.com/66973361/113046612-441b4500-916e-11eb-93d2-fee8228e0781.png)

2021-03-30 20:38 UTC, maurizi commented
@kevinearldenny Just a few small tweaks for this to match the wireframes:
 - Have the Organization section use the same `<Card />` component for styling as all of the other components on the `CreateProjectScreen`
 - Add a border to the top of the templates section

[![image](https://user-images.githubusercontent.com/4432106/113052751-83995f80-9175-11eb-9242-ebe330c269f3.png)](https://app.abstract.com/projects/9f988240-1dad-11e8-9a40-cba930331af7/branches/master/commits/7d5ef3ffd47c24a2d1fa966f5f90f9a67ce2f253/files/DCA38482-FC7F-4F48-BECD-44E07D9F7443/layers/31632AA6-357A-4F45-ADFB-8FEFDBEFE040)

2021-03-30 20:43 UTC, maurizi commented on src/client/screens/CreateProjectScreen.tsx
> +                  <div sx={style.radioSubHeading}>{org.slug}</div>
I don't think we want to show the `slug` here
```suggestion
```

2021-03-31 21:01 UTC, maurizi approved these changes

2021-03-31 21:05 UTC, merged