Refactor evaluate mode
PublicMapping/districtbuilder pull request #642
Opened 2021-03-23 15:47 UTC by kevinearldenny

## Overview

- Move files for Project Evaluate mode into the `evaluate` folder
- Splits the `ProjectEvaluateSidebar` component into a wrapper component, and puts info display from sidebar into new `ProjectEvaluateSummary` component
- Displays computed County Split metric in `ProjectSummary` to show an example of the computation / flow of data within these components

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

## Testing Instructions

- ./scripts/server
- Prefer bulleted description
- Start after checking out this branch
- Include any setup required, such as bundling scripts, restarting services, etc.
- Include test case, and expected output

2021-03-23 15:51 UTC, kevinearldenny commented on src/client/components/evaluate/ProjectEvaluateSummary.tsx
> +  readonly projectMetricValues: any;
@pcaisse Not entirely sure what the type should be here, since it's a keyed object with a fairly flexible structure

2021-03-23 19:52 UTC, pcaisse requested changes

2021-03-23 19:52 UTC, pcaisse commented on src/client/screens/ProjectScreen.tsx
> +import ProjectEvaluateView from "../components/evaluate/ProjectEvaluateSidebar";
Should this still be called `ProjectEvaluateSidebar`?

2021-03-23 19:52 UTC, pcaisse commented on src/client/components/evaluate/ProjectEvaluateSidebar.tsx
> +        ></ProjectEvaluateSummary>
```suggestion
        />
```

2021-03-23 19:52 UTC, pcaisse commented on src/client/components/evaluate/ProjectEvaluateSidebar.tsx
> +  const projectMetricValues = {
I think `projectMetricValues` could serve as our source of truth now (possibly with dummy data still included for the metrics for which do not yet have real values). That way we can avoid doing the key lookup which may return undefined if we make a mistake and then we have to deal with the undefined case. (In practice this may actually shake out as getting rid of `projectMetricValues` and keeping `requiredMetrics` and `optionalMetrics` with real data in them since we care about the required/optional distinction for display purposes.) The overall point is I think we should avoid doing the lookup by key and instead have the data and metadata together in one object so that if we have a metric key we'll also have the data associated with it. It seems to me that should be workable since this component is both deriving the real data from the project and also currently injecting the dummy data so we should have everything we need.

2021-03-23 19:52 UTC, pcaisse commented on src/client/components/evaluate/ProjectEvaluateSummary.tsx
> +  readonly projectMetricValues: any;
See above comment

2021-03-24 14:32 UTC, kevinearldenny commented on src/shared/entities.d.ts
> +  readonly splitCounties?: readonly (GeoUnitCollection | undefined)[] | undefined;
@pcaisse Does this seem sustainable to imagine all of the different permutations for the 6 evaluation metrics to be coerced into `EvaluateMetric` like this? Or is there another way you would recommend structuring this to be more extensible?

2021-03-24 15:36 UTC, pcaisse commented on src/shared/entities.d.ts
> +  readonly splitCounties?: readonly (GeoUnitCollection | undefined)[] | undefined;
So with the placeholder data it's a little tricky to imagine what is actually required for the summary and list views. It seems like `EvaluateMetric` is pulling double duty for both of those views here. It's definitely possible in TS to say "allow any other stuff you want" for an interface like so where the "other stuff" would be what's required for the detail view:
```ts
export type EvaluateMetric = {
  readonly key: string;
  readonly name: string;
  readonly type?: "fraction" | "percent" | "count";
  readonly value?: number;
  readonly status?: boolean;
  readonly description: string;
  [key: string]: any;
};
```
That way the fields that are explicitly called out in `EvaluateMetric` are required for summary and we know they'll be there, so that covers our bases for the summary. For the detail view, it seems like each metric will require different pieces of data, or possibly different components that could be stuffed into `EvaluateMetric`, but we can figure that out when we come to it.

2021-03-24 16:41 UTC, kevinearldenny commented on src/shared/entities.d.ts
> +  readonly splitCounties?: readonly (GeoUnitCollection | undefined)[] | undefined;
Hmmm, this appears to be giving me two lint errors:

```
  28:3   error    Only the same kind of members allowed in types  functional/no-mixed-type
  28:27  warning  Unexpected any. Specify a different type        @typescript-eslint/no-explicit-any
```

2021-03-24 17:10 UTC, pcaisse commented on src/shared/entities.d.ts
> +  readonly splitCounties?: readonly (GeoUnitCollection | undefined)[] | undefined;
You can just throw an `// eslint-disable-next-line` on the line before it for now.

2021-03-24 17:19 UTC, pcaisse approved these changes

2021-03-24 17:21 UTC, merged