Add Project Evaluate view for compactness
PublicMapping/districtbuilder pull request #646
Opened 2021-03-25 18:08 UTC by kevinearldenny

## Overview

Adds project evaluate mode view for compactness.

- Computes the average compactness and displays it in `ProjectEvaluateSummary`
- Display list of districts and their compactness score in metric detail view
- Display chloropleth map in `Map`
- Add legend for chloropleth map

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

Optional. Screenshots, examples, etc.

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

- `./scripts/server`
- Open a project and click evaluate
- Click 'Compactness'
- Expect: Compactness view is rendered as pictured

Closes #607

2021-03-25 20:09 UTC, kevinearldenny commented on src/client/components/evaluate/detail/Compactness.tsx
> +  }
Is there a more typescript-y way to do this?

2021-03-25 20:10 UTC, kevinearldenny commented on src/client/components/map/Map.tsx
> +        // Make the county layer the only layer visible
```suggestion
        // Remove all geolayers from view
```

2021-03-26 19:41 UTC, pcaisse requested changes
I found a couple of issues with functionality and then added a bunch of comments with suggestions mostly related to type safety.

2021-03-26 19:41 UTC, pcaisse commented on src/client/components/map/index.ts
> +    [0.6, "#006d2c"]
I think the last stop should be up to 1 like so (without this my 78% compactness district wasn't showing up as dark green):
```suggestion
    [1.0, "#006d2c"]
```

2021-03-26 19:41 UTC, pcaisse commented on src/client/components/evaluate/detail/Compactness.tsx
> +        {Number(metric.value) ? ` ${Math.floor(Number(metric.value) * 100)}%` : " "}
See previous comment about casting the potentially undefined `metric.value` to a number

2021-03-26 21:57 UTC, kevinearldenny commented on src/client/components/map/Map.tsx
> +            map.setLayoutProperty(levelToSelectionLayerId(geoLevel.id), "visibility", "visible");
@pcaisse The bug encountered with the map not working after switching back to regular Project mode from the Project Evaluate view was due to previously having only added the line layer and not the selection layer

2021-03-26 22:26 UTC, kevinearldenny commented on src/client/components/evaluate/detail/Compactness.tsx
> +const CompactnessMetricDetail = ({
Should be fixed now - was unrelated to this table structure error (which is also fixed)

2021-03-29 20:05 UTC, pcaisse approved these changes
LGTM! :tada:

2021-03-29 20:29 UTC, merged