Add Project Evaluate view for contiguity
PublicMapping/districtbuilder pull request #648
Opened 2021-03-25 21:52 UTC by kevinearldenny

## Overview

Adds project evaluate mode view for contiguity.

- Add Contiguity detail
- Display contiguity on map
- Add map legend for contiguity

### Checklist

- [x] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

![image](https://user-images.githubusercontent.com/66973361/112548477-b072fe80-8d92-11eb-8fc1-397b9e3469ed.png)

## Testing Instructions

- ./scripts/server
- Open a project and click evaluate
- Click 'Contiguity'
- Expect: Contiguity view is rendered as pictured

Closes #605

2021-03-25 22:20 UTC, kevinearldenny commented on src/client/reducers/districtDrawing.ts
> +        evaluateMetric: undefined,
I added in this logic here to clear the selected metric when evaluate mode is toggled off, but I'm not totally sure this is how it's supposed to be. @maurizi , any thoughts here?

2021-03-30 17:21 UTC, maurizi commented
@kevinearldenny it looks like this has a lot of conflicts both with `develop` and likely also quite a few w/ #644 - I'm going to hold off on review for now. Let me know when its ready to review.

2021-04-02 13:49 UTC, maurizi requested changes
Looking pretty good, just a few small cleanups needed 👍

2021-04-02 13:49 UTC, maurizi commented on src/client/components/evaluate/ProjectEvaluateSidebar.tsx
> +          : false,
In general, any code of the type `let my_var = some_boolean_expression ? true : false` can **always** be simplified to just `let my_var = some_boolean_expression`.

This is a similar code smell to things like:
```
if (some_boolean_expression) {
  return true;
} else {
  return false;
}
```

Which can always be simplified to simply: `return some_boolean_expression;`.


So in this specific case:
```suggestion
        geojson?.features.filter(f => f.properties.contiguity === "non-contiguous").length === 0,
```

2021-04-02 13:49 UTC, maurizi commented on src/client/components/map/Map.tsx
> +  // }
?

```suggestion
```

2021-04-02 13:49 UTC, maurizi commented on src/client/reducers/districtDrawing.ts
> +        evaluateMetric: undefined,
I'm honestly not sure - @jfrankl What do you think?

If I go into Evaluate mode, go into a detail screen like Contiguity, and then I toggle Evaluate Mode off and then on again what do I see?
 - The Evaluate Summary view
 - The Evaluate Contiguity detail view

2021-04-02 13:49 UTC, maurizi commented on src/client/components/evaluate/detail/Contiguity.tsx
> +      <Flex sx={{ flexDirection: "column", width: "60%" }}>
This looked better for me (why would we want 40% of the sidebar to be blank?):
```suggestion
      <Flex sx={{ flexDirection: "column", width: "100%" }}>
```

2021-04-02 13:49 UTC, maurizi commented on src/client/components/map/Map.tsx
> +              }}
You should extract these shared styles to make things a little more DRY:
```typescript
              sx={{
                ...style.legendColorSwatch,
                backgroundColor: CONTIGUITY_FILL_COLOR
              }}
```

2021-04-02 13:49 UTC, maurizi commented on src/client/components/evaluate/detail/Contiguity.tsx
> +                      </Box>
We should handle empty districts as well:
```suggestion
                      {feature.properties.contiguity ? (
                        <React.Fragment>
                          <Box
                            sx={{
                              display: "inline-block",
                              mr: "40px",
                              width: "20px",
                              height: "20px",
                              opacity: "0.9",
                              backgroundColor: computeRowFill(feature.properties)
                            }}
                          ></Box>
                          <Box sx={style.compactnessItem}>
                            {feature.properties.contiguity === "contiguous"
                              ? "Contiguous"
                              : "Non-contiguous"}
                          </Box>
                        </React.Fragment>
                      ) : (
                        <Box sx={style.compactnessItem}>Empty</Box>
                      )}
```

2021-04-02 15:24 UTC, jfrankl commented on src/client/reducers/districtDrawing.ts
> +        evaluateMetric: undefined,
Thank you for checking in, this is a great question. I think we should have the user get dropped back in the section they were in. So, in your case, they would see the "The Evaluate Contiguity detail view" when they re-enter evaluate mode. My thinking is that this would allow a user to toggle back and forth between the two modes more seamlessly; you could see a particular metric, go back to editing your maps, and then quickly get back to the same metric.

2021-04-02 19:37 UTC, maurizi commented on src/client/reducers/districtDrawing.ts
> +        evaluateMetric: undefined,
@kevinearldenny it sounds like answer is we don't want to include this change:
```suggestion
```

2021-04-02 19:52 UTC, maurizi approved these changes
_edit_ nevermind

2021-04-02 19:54 UTC, maurizi requested changes

2021-04-02 19:54 UTC, maurizi commented on src/client/components/map/Map.tsx
> +              }}
@kevinearldenny Why did you mark this as resolved?

2021-04-02 20:42 UTC, kevinearldenny commented on src/client/components/map/Map.tsx
> +              }}
Whoops... I think I made this refactor on the other branch but not here. Should be fixed now.

2021-04-05 14:24 UTC, maurizi approved these changes

2021-04-05 14:35 UTC, merged