Whitelist isFeatured field from triggering change to Project.updatedDt
PublicMapping/districtbuilder pull request #676
Opened 2021-04-05 19:16 UTC by maurizi

## Overview

We want to track the most recently updated date for users projects, but organization admins setting the `isFeatured` flag should not be considered an update.

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

## Testing Instructions

- On `develop`, toggling the Featured/Unfeatured flag will also update the `Project.updatedDt` field. On this branch it should not.
- Editing other project fields (name, districts, visibility, etc.) should continue to update the `updatedDt` field

Closes #668

2021-04-05 19:18 UTC, maurizi commented on src/server/src/projects/controllers/projects.controller.ts
> +    const whitelistedFields = ["isFeatured", "districts", "updatedDt"];
@tgilcrest are there any other fields we want to whitelist here? `visibility` (updating the Share menu option)?

2021-04-05 19:33 UTC, tgilcrest commented on src/server/src/projects/controllers/projects.controller.ts
> +    const whitelistedFields = ["isFeatured", "districts", "updatedDt"];
Yeah, visibility should not update it. I don't know all the other fields, but I'm mainly thinking just district definition and name are the relevant ones. I don't know if this would be updated by lock/unlock also, but I'm thinking we don't care about that action either.

2021-04-05 20:47 UTC, kevinearldenny requested changes
The core fix looks good here, but there is a little bit of lint to clean up:

```
diff --git a/src/server/src/projects/entities/project.entity.ts b/src/server/src/projects/entities/project.entity.ts
index 7af8000..0bc5a48 100644
--- a/src/server/src/projects/entities/project.entity.ts
+++ b/src/server/src/projects/entities/project.entity.ts
@@ -4,8 +4,7 @@ import {
   Entity,
   JoinColumn,
   ManyToOne,
-  PrimaryGeneratedColumn,
-  UpdateDateColumn
+  PrimaryGeneratedColumn
 } from "typeorm";
```

2021-04-05 21:00 UTC, kevinearldenny commented
Also while testing this, I encountered two bugs around table sorting that are now more visible as a result of this fix and wrote them up in #678

2021-04-06 12:57 UTC, maurizi commented on src/server/src/projects/controllers/projects.controller.ts
> +    const whitelistedFields = ["isFeatured", "districts", "updatedDt"];
Updated to explicitly only change `updatedDt` on changes to districts or name in https://github.com/PublicMapping/districtbuilder/pull/676/commits/928665ee2796e91d3b9a2a769f9cfc8db540f2e2

2021-04-06 17:21 UTC, kevinearldenny approved these changes
👍

2021-04-06 17:35 UTC, merged