Update index of locked districts to make the last district lockable
PublicMapping/districtbuilder pull request #677
Opened 2021-04-05 20:10 UTC by kevinearldenny

## Overview

Fixes a bug identified in #666 where the last district in the list cannot be locked by updating the IDs of districts in the list. Previously, the ø / unassigned district was associated with the first value in the locked districts list, when in reality it should never be lockable. By updating the indices of the locked districts in the sidebar and map to be n-1, all districts are now able to be locked. 

Also, the ability to lock the unassigned district was removed.

### Checklist

- [x] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

![image](https://user-images.githubusercontent.com/66973361/113621206-5cd1a200-9629-11eb-997f-e58299ae4026.png)

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

- Create a map with a full set of districts, and attempt to lock all of the districts individually. All of the districts should be lockable, and their lock state should be reflected in the map as well as the sidebar

Closes #666

2021-04-05 20:25 UTC, maurizi commented on CHANGELOG.md
> +- Allow last district to be locked [#677](https://github.com/PublicMapping/districtbuilder/pull/677)
I think this belongs under `### Fixed`?

2021-04-05 20:57 UTC, maurizi requested changes
We should add a data migration to this PR, to adjust the existing `locked_districts` column - otherwise this change will effectively change the locked districts of every project.

The following SQL command should do it I think: ` UPDATE project SET locked_districts = locked_districts[2:] || false;`

2021-04-06 17:02 UTC, kevinearldenny commented on src/server/migrations/1617656641073-locked-districts.ts
> +    }
@maurizi Do we need to add anything in the `down` section to potentially reverse this migration?

2021-04-06 17:16 UTC, maurizi commented on src/server/migrations/1617656641073-locked-districts.ts
> +    }
I think this would work?
```suggestion
    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`UPDATE project SET locked_districts = false || locked_districts[:cardinality(locked_districts) - 1];`, undefined);
    }
```

2021-04-06 17:35 UTC, maurizi approved these changes
👍

2021-04-06 18:00 UTC, maurizi approved these changes

2021-04-06 18:57 UTC, merged