Add Evaluate Mode view for Equal Population
PublicMapping/districtbuilder pull request #685
Opened 2021-04-09 19:52 UTC by kevinearldenny

## Overview

Adds Evaluate Mode view for Equal Population

- Add new screen
- Compute population deviation on backend and add to GeoJSON so we can style the map based on it
- Add diverging scale on map to display the deviation from the the expected population for a district

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

### Notes

It seems like the choropleth stops are getting a little messed up in some instances - but _only_ in the map, not the sidebar view. 

## Testing Instructions

- How to test this PR
- Prefer bulleted description
- Start after checking out this branch
- Include any setup required, such as bundling scripts, restarting services, etc.
- Include test case, and expected output

Closes #606

2021-04-13 14:42 UTC, kevinearldenny commented
Worked with @jfrankl to update the color ramp:

![image](https://user-images.githubusercontent.com/66973361/114571884-ff4ede00-9c44-11eb-914a-3288a20bbb2b.png)

2021-04-14 14:14 UTC, maurizi requested changes

2021-04-14 14:14 UTC, maurizi commented on src/server/src/districts/entities/geo-unit-topology.entity.ts
> +    );
Why are we adding these properties to the backend districts geojson when we _also_ calculate this on the frontend?

I had assumed we would continue to calculate these variables on the frontend (bonus to this approach - it avoids the question of how to migrate existing cached `districts` geojson for now if we don't make changes to it).

If there is some reason we need to calculate these on the backend now though, we should migrate our existing frontend code to rely on that and stop redundantly recalculating this for the normal sidebar.

https://github.com/PublicMapping/districtbuilder/blob/e39dc0fff9dee832539684a26ea5422325064d84/src/client/components/ProjectSidebar.tsx#L458

https://github.com/PublicMapping/districtbuilder/blob/e39dc0fff9dee832539684a26ea5422325064d84/src/client/components/ProjectSidebar.tsx#L474-L479

2021-04-14 14:14 UTC, maurizi commented on src/server/src/districts/entities/geo-unit-topology.entity.ts
> +                : undefined,
This may be rendered moot by the above comment, but out of curiousity why put `popDeviation` under `properties.demographics` but `percentDeviation` under `properties`?

2021-04-14 14:16 UTC, maurizi commented
@kevinearldenny my color ramp doesn't look like your screenshot - did you forget to push your changes?
![image](https://user-images.githubusercontent.com/4432106/114725373-700bfe00-9d0a-11eb-93f1-f03d9aaa2859.png)

2021-04-14 14:24 UTC, kevinearldenny commented on src/server/src/districts/entities/geo-unit-topology.entity.ts
> +                : undefined,
We need to access `percentDeviation` in the mapbox style expression, and from what I could tell it seems like we are not able to access nested elements in the GeoJSON for styling purposes.

2021-04-14 16:53 UTC, kevinearldenny commented on src/client/components/ProjectSidebar.tsx
> +            : feature.properties.demographics.popDeviation;
Now using the computed `popDeviation` field from the geojson

2021-04-14 16:58 UTC, maurizi commented on src/server/src/districts/entities/geo-unit-topology.entity.ts
> +    );
>[...] the question of how to migrate existing cached districts geojson for now if we don't make changes to it

@kevinearldenny I saw you went with the approach of consolidating this to be calculated on the server. Reminder that we also need to handle the above scenario in that case (i.e. what happens if I have a map with `districts` cached from before this code change was introduced, and I enter evaluate mode w/o making any changes? what triggers us to recalculate such that we get `popDeviation` added to our cached data?)

2021-04-20 00:19 UTC, maurizi approved these changes
👍 Working well

2021-04-20 00:19 UTC, maurizi commented on src/client/components/map/Map.tsx
> +      feature.properties.populationDeviation = populationDeviation;
You could clean up this a bit by disabling eslint for this section and explicitly telling TypeScript we're going to treat `feature.properties` as `any`:
```diff
diff --git a/src/client/components/map/Map.tsx b/src/client/components/map/Map.tsx
index b90ed84..e94bb5c 100644
--- a/src/client/components/map/Map.tsx
+++ b/src/client/components/map/Map.tsx
@@ -222,30 +222,23 @@ const DistrictsMap = ({
     const avgPopulation = getTargetPopulation(geojson, project);
     // Add a color property to the geojson, so it can be used for styling
     geojson.features.forEach((feature, id) => {
-      // @ts-ignore
-      // eslint-disable-next-line
-      feature.properties.outlineColor =
+      /* eslint-disable */
+      const properties: any = feature.properties;
+      properties.outlineColor =
         (findTool === FindTool.Unassigned && id === 0) ||
         (findTool === FindTool.NonContiguous &&
           id !== 0 &&
           feature.geometry.coordinates.length >= 2)
           ? "#F25DFE"
           : "transparent";
-      // @ts-ignore
-      // eslint-disable-next-line
-      feature.properties.color = getDistrictColor(id);
-      // @ts-ignore
+      properties.color = getDistrictColor(id);
       const populationDeviation = feature.properties.demographics.population - avgPopulation;
-      // @ts-ignore
-      // eslint-disable-next-line
-      feature.properties.percentDeviation =
-        // @ts-ignore
+      properties.percentDeviation =
         feature.properties.demographics.population > 0 && feature.id !== 0
           ? populationDeviation / avgPopulation
           : undefined;
-      // @ts-ignore
-      // eslint-disable-next-line
-      feature.properties.populationDeviation = populationDeviation;
+      properties.populationDeviation = populationDeviation;
+      /* eslint-enable */
     });
 
     const districtsSource = map && map.getSource(DISTRICTS_SOURCE_ID);
```

2021-04-20 00:24 UTC, maurizi commented on src/client/components/map/Map.tsx
> +      feature.properties.populationDeviation = populationDeviation;
Actually on second thought in light of the changes in https://github.com/PublicMapping/districtbuilder/pull/688 you might want to just hold off on this

2021-04-20 00:29 UTC, maurizi commented on CHANGELOG.md
> +- Add project evaluate view for Equal Population [#685](https://github.com/PublicMapping/districtbuilder/pull/685)
This should go under the `Unreleased` section

2021-04-20 15:08 UTC, merged