Toggle map pan tool with spacebar
PublicMapping/districtbuilder pull request #687
Opened 2021-04-13 14:19 UTC by kevinearldenny

## Overview

Toggles between map pan ('grab') tool and rectangle / paintbrush select tool when the spacebar is pressed.

- Prevent toggle when the user is actively selecting new elements with the rectangle tool

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

## Testing Instructions

- `./scripts/server`
- Start selecting elements with the rectangle selection or paintbrush
- Hit spacebar - expect cursor to become map pan tool
- Hit spacebar again - expect cursor to return to rectangle select
- Continue selecting more elements, and hit the spacebar as you are selecting more elements. Expect - nothing happens

Closes #429

2021-04-13 14:29 UTC, tgilcrest commented
Based on the description, it sounds like hitting spacebar toggles this on and off. I think it should be that holding spacebar activates the pan tool, so it's only active while spacebar is pressed, but goes back to the drawing tool when released. The issue description is ambiguous, sorry about that.

@jfrankl can you confirm which is the intended action?

2021-04-13 16:33 UTC, jfrankl commented
Thank you for asking this clarifying question. Holding the spacebar should allow the user to pan. Releasing the spacebar should allow them to resume drawing.

2021-04-13 16:57 UTC, kevinearldenny commented
Okay, the pan toggle should now only occur when the user is holding down the spacebar. Ready for review

2021-04-15 21:27 UTC, pcaisse requested changes

2021-04-15 21:27 UTC, pcaisse commented on src/client/components/map/Map.tsx
> +  const [currentTool, setCurrentTool] = useState<SelectionTool | undefined>();
I'm not sure I understand why `currentTool` and `setCurrentTool` are needed at the component level since we have `selectionTool` in Redux. Can we avoid adding to the component state here?

2021-04-15 21:27 UTC, pcaisse commented on src/client/components/map/Map.tsx
> +  const [rectangleActive, setRectangleActive] = useState<boolean>();
It seems like the paintbrush tool suffers from the same panning-when-in-use-messes-up-cursor issue as the rectangle selection tool:
![db_paint_pan](https://user-images.githubusercontent.com/2926237/114938530-3243ce00-9e0d-11eb-8e91-d22332b8ff0b.gif)

As such, it might make sense to generalize this component state and update function to something like:
 ```suggestion
   const [selectionInProgress, setSelectionInProgress] = useState<boolean>();
 ```

And then have the paintbrush tool also call `setActive` similarly to the rectangle selection tool.

2021-04-15 21:27 UTC, pcaisse commented on src/client/components/map/RectangleSelectionTool.ts
> +    setActive: (isActive: boolean) => {}
We want to [return void](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#return-types-of-callbacks) here:
```suggestion
    setActive: (isActive: boolean) => void
```

2021-04-15 21:28 UTC, pcaisse commented on src/client/components/map/Map.tsx
> +  const upHandler = ({ key }) => {
See previous comment

2021-04-16 21:02 UTC, kevinearldenny commented on src/client/components/map/Map.tsx
>        PaintBrushSelectionTool.disable(map);
@pcaisse I figured it out! We needed to first _disable everything_ before re-enabling the correct tool

2021-04-19 18:24 UTC, pcaisse commented on src/client/components/map/Map.tsx
> +    // setSelectionInProgress(false);
Should this be commented out?

2021-04-19 18:24 UTC, pcaisse commented on src/client/components/map/Map.tsx
> +        setCurrentTool(selectionTool);
I'm still having trouble understanding what `currentTool` means exactly... Is it the currently-selected-but-not-in-use pannable tool? Maybe renaming it or adding comments would help.

2021-04-19 18:24 UTC, pcaisse commented on src/client/components/map/Map.tsx
> +          DefaultSelectionTool.disable(map);
Does the default selection tool need to be disabled here?

2021-04-19 18:24 UTC, pcaisse commented on src/client/components/map/Map.tsx
> +          setCurrentTool(undefined);
Does this need to happen for only the rectangle and paint tools and not the default selection tool? If we could avoid  disabling the default selection tool within each if block and could instead do it outside of the if blocks it would be DRY-er.

2021-04-19 18:24 UTC, pcaisse commented on src/client/components/map/Map.tsx
> +        setCurrentTool(selectionTool);
So here we're setting `currentTool` which is a dependency for this effect. Setting `currentTool` then causes the effect function to be revaluated which then affects the `else` block below... I'm having trouble following the flow here.

I don't fully understand what's happening here, but I think in the interest of keeping our state as simple as we can, only enabling/disabling the selection tools in one place is desirable and we're already doing that in the effect function on line 527. Is that possible? The more places we enable/disable the more places we could forget to do that properly. I'm not sure if that's possible here but may be something to consider.

2021-04-19 19:31 UTC, kevinearldenny commented on src/client/components/map/Map.tsx
> +          setCurrentTool(undefined);
My understanding is that we explicitly do not want this effect to run on the default selection tool. Since it's cursor already has a pan functionality associated with it, the only thing this would do is remove the ability to select - so, the spacebar toggle should have no impact when the default selection tool is enabled. 

@tgilcrest - can you confirm here?

2021-04-19 19:49 UTC, kevinearldenny commented on src/client/components/map/Map.tsx
> +        setCurrentTool(selectionTool);
Yes, as we discussed when we were pairing on Friday - `currentTool` is preserving the state of the tool that is currently selected with the toggle buttons. If we were to try to use `selectionTool` in lines 595 and 607 instead, this effect would run every time `selectionInProgress` changes making the rectangle selection tool appear while the spacebar is held down.

2021-04-19 19:49 UTC, kevinearldenny commented on src/client/components/map/Map.tsx
> +          DefaultSelectionTool.disable(map);
Nope - removed now.

2021-04-19 19:58 UTC, kevinearldenny commented on src/client/components/map/Map.tsx
> +        setCurrentTool(selectionTool);
I renamed this to `preserveTool`, which I personally think is a little bit _less_ explanatory... but I'm at a loss for a better name here. Open to any suggestions that you have for a better name

2021-04-19 22:21 UTC, pcaisse commented
Thanks for the comments. They helped me understand what was going on better.

I think I have a suggestion that will allow us to simplify things. It seems to be functionally equivalent based on my testing but is less code. Here's the commit which you can cherry pick onto your branch if you like: https://github.com/PublicMapping/districtbuilder/commit/882605117f28ac6a2580d4caf00b68e7ebd580fd

2021-04-20 00:29 UTC, maurizi commented on CHANGELOG.md
> +- Toggle map pan tool when holding down spacebar in rectangle / paintbrush select mode [#687](https://github.com/PublicMapping/districtbuilder/pull/687)
This needs to be moved to the `Unreleased` section

2021-04-20 00:29 UTC, maurizi commented on CHANGELOG.md
> +- Toggle map pan tool when holding down spacebar in rectangle / paintbrush select mode [#687](https://github.com/PublicMapping/districtbuilder/pull/687)
This needs to be moved to the `Unreleased` section

2021-04-20 14:34 UTC, kevinearldenny commented
> Thanks for the comments. They helped me understand what was going on better.
> 
> I think I have a suggestion that will allow us to simplify things. It seems to be functionally equivalent based on my testing but is less code. Here's the commit which you can cherry pick onto your branch if you like: [8826051](https://github.com/PublicMapping/districtbuilder/commit/882605117f28ac6a2580d4caf00b68e7ebd580fd)

I like this solution a lot, definitely much cleaner 👍  I should have released this sooner, especially after noting that the two effects were conflicting with each other...

2021-04-20 15:42 UTC, pcaisse approved these changes

2021-04-20 16:59 UTC, merged