Feature/ked/limit drawing within county
PublicMapping/districtbuilder pull request #698
Opened 2021-04-16 20:48 UTC by kevinearldenny

## Overview

- Add new checkbox in MapHeader dropdown menu, 'Limit selection to county'
- Enables end users to reduce county splits by limiting the selection of the rectangle / paintbrush tools to only select geounits from within a certain county in a single mouse drag*

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

![image](https://user-images.githubusercontent.com/66973361/115082262-9f219b80-9ed3-11eb-902d-f767dceb9ee6.png)

### Notes

* It _is_ possible to create a selection that spans multiple counties, if you do so in multiple distinct drags. This is the same as the [protoype](https://dbtwo.netlify.app/), however

## Testing Instructions

- Open up an editable project, and click the tool icon in the header and select "Limit selection to county"
- Select the paintbrush tool at the block or block group level, and drag an area in one county. Attempt to continue drag into another county
- Expect: Geounits in the adjacent county are not selected
- Select the rectangle tool at the block or block group level, and drag an area in one county. Attempt to continue drag into another county
- Expect: Geounits in the adjacent county are not selected

Closes #216

2021-04-20 00:30 UTC, maurizi commented on CHANGELOG.md
> +- Limit drawing to within starting county [#698](https://github.com/PublicMapping/districtbuilder/pull/698)
This needs to be moved to the `Unreleased` section

2021-04-21 00:46 UTC, pcaisse requested changes
Tested well! Left some comments.

2021-04-21 00:46 UTC, pcaisse commented on src/client/components/map/index.ts
> +        return g[1][0] === county;
Could you please use longer variable names here for `o` and `g`?

2021-04-21 14:41 UTC, kevinearldenny commented on src/client/components/map/index.ts
> +export function filterGeoUnitsByCounty(units: GeoUnits, county: number) {
My understanding was that we did not want this functionality to be active for Dane County - although if this is true, we probably should hide the button in the header when the largest geounit is not `county`. @maurizi can you please confirm?

2021-04-21 14:47 UTC, maurizi commented on src/client/components/map/index.ts
> +export function filterGeoUnitsByCounty(units: GeoUnits, county: number) {
> My understanding was that we did not want this functionality to be active for Dane County

This would be news to me.

I agree with @pcaisse it would be better to at least acknowledge the possibility via a comment the `county` might actually be a ward (or maybe even something else like a _state_ in a _multi-state_ region - technically there is nothing in the code preventing us from setting up a region that works this way) - and make sure we don't do something weird / broken in that case like hardcode the text "county".

2021-04-21 19:56 UTC, kevinearldenny commented
@jfrankl Can you take a look at the styling for this when you have a second? Couple of outstanding design items here:

1. What icon should we use for the dropdown?
2. Styling / positioning for the dropdown
3. Copy for the UI for Dane County / the potential multi-state regions that Mike mentioned in the above comment

2021-04-21 20:02 UTC, maurizi commented
> Copy for the UI for Dane County / the potential multi-state regions that Mike mentioned in the above comment

Just like for the Evaluate mode county split, you should replace hard-coded references to "county" in the UI with the top-most geolevel: https://github.com/PublicMapping/districtbuilder/pull/644#issuecomment-810585676 - otherwise I wasn't sugesting any copy changes.

2021-04-21 21:09 UTC, kevinearldenny commented on src/client/components/map/PaintBrushSelectionTool.ts
> +        currentCounty = getCurrentCountyFromGeoUnits(staticMetadata, geoUnits);
Not sure that I'm totally understanding this correctly - my initial understanding was that you wanted the bits above the highlighted selection removed, since they were more or less redundant with the logic that exists within `getCurrentCountyFromGeoUnits`. Can you confirm that this has been fixed?

2021-04-22 13:33 UTC, pcaisse commented on src/client/components/map/PaintBrushSelectionTool.ts
> +        currentCounty = getCurrentCountyFromGeoUnits(staticMetadata, geoUnits);
Yeah, this seems fine to me now :+1:

2021-04-22 13:57 UTC, pcaisse commented on src/client/components/MapHeader.tsx
> +  }, [metadata]);
So we don't actually need to introduce more component-level state or effects here. We really just want a value that's derived from `metadata` so we can just assign a variable:
```suggestion
  const topGeoLevelName = metadata
    ? metadata.geoLevelHierarchy[metadata.geoLevelHierarchy.length - 1].id
    : undefined;
```
`topGeoLevelName` will be updated whenever `metadata` is since the component will re-render whenever `metadata` changes.

In general we should try to avoid introducing state/effects whenever possible (our ideal components are just stateless render functions that take in props as input and return JSX since that keeps them as easy to reason about as possible).

2021-04-23 14:06 UTC, kevinearldenny commented on src/client/components/MapSelectionOptionsFlyout.tsx
> +    <Wrapper
@pcaisse I paired with @jfrankl yesterday, this should be good to go styling wise now

2021-04-26 19:46 UTC, pcaisse reviewed
I just had the one outstanding comment re: "county" but otherwise this looks good to go!

2021-04-26 19:56 UTC, kevinearldenny commented
> I just had the one outstanding comment re: "county" but otherwise this looks good to go!

Okay, I added in one comment at the function that you explicitly referenced in the aforementioned comment. Do you feel that this is necessary in any other places?

2021-04-26 20:38 UTC, pcaisse commented
> > I just had the one outstanding comment re: "county" but otherwise this looks good to go!
> 
> Okay, I added in one comment at the function that you explicitly referenced in the aforementioned comment. Do you feel that this is necessary in any other places?

Nah, I think it's fine

2021-04-26 20:39 UTC, pcaisse approved these changes
Works like a dream!

2021-04-26 20:53 UTC, merged