Import plan error warnings
PublicMapping/districtbuilder pull request #708
Opened 2021-04-23 16:46 UTC by kevinearldenny

## Overview

Displays file errors and row flags when importing a block equivalency CSV in `ImportProjectScreen`

File errors
- File too large (based on a newly added constant, `MaxUploadFileSize`
- Invalid file format (although I don't think this is really possible)
- File with no rows

Row-level flags
- Invalid BLOCKID
- Blocks from multiple different states
- Duplicate BLOCKIDs
- Invalid district IDs (currently assuming that any numeric value is valid, and any non-numeric value is invalid)

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

![image](https://user-images.githubusercontent.com/66973361/115903177-48ffab80-a431-11eb-9c9c-44d94c2a6a76.png)

![image](https://user-images.githubusercontent.com/66973361/115903207-4f8e2300-a431-11eb-9557-8daf05ab1dd5.png)

![image](https://user-images.githubusercontent.com/66973361/115903245-59b02180-a431-11eb-894b-2155e8b882c3.png)

### Notes

This definitely needs some styling work on the modal from @jfrankl 😬 

## Testing Instructions

- Test the attached CSVs at http://localhost:3003/import-project
- Expect: Errors are displayed as indicated in screenshots

[Bad_FIPS.csv](https://github.com/PublicMapping/districtbuilder/files/6366874/Bad_FIPS.csv)
[Blanky.csv](https://github.com/PublicMapping/districtbuilder/files/6366875/Blanky.csv)

Closes #629

2021-04-23 17:48 UTC, maurizi commented on CHANGELOG.md
> ->>>>>>> Update changelog
@kevinearldenny looks like you had a bad merge/rebase

2021-04-23 17:59 UTC, kevinearldenny commented on CHANGELOG.md
> ->>>>>>> Update changelog
Hmmm, weird... seems like this may have something to do with the GitHub issues you mentioned earlier?

2021-04-23 21:27 UTC, maurizi requested changes
This is looking great so far 👍 

I left a few inline comments.

In addition, aone other error case I'd like to check for:
 - If your file has a row with something that _looks like_ a valid blockid, but isn't actually (for example I sorted my file by block id and then incremented the highest number block id by 1), we won't flag that row, but also it won't get used. That seems like 💯 something we should flag

2021-04-23 21:27 UTC, maurizi commented on src/client/screens/ImportProjectScreen.tsx
> +          file.type !== "text/csv" && setFileError("File must be a .csv");
By continuing on afterwards, these more specific errors are getting swallowed by the generic "File must have at least one record".

```suggestion
          if (file.size > MaxUploadFileSize) {
            setFileError("File must be less than 25mb");
            return;
          }
```

Separately, not sure why you had the `// @ts-ignore` there - I was able to remove it w/ no compilation issues.

As for how you could have a `file.type` that isn't "text/csv"
 - In Chrome at least I can switch the pre-selected `.csv` file extension to "Any files"
 
_However_ from my testing relying on `file.type` isn't fool-proof - the CSV file I downloaded from Dave's Redistricting App had an empty string for it's `file.type` when I uploaded it to our site (it seems to be a property of the file?? not sure on this). I think we could still use `file.type` if it is present, but we'd maybe want to fall back to checking if `file.name` ends with `.csv` otherwise.

2021-04-26 19:12 UTC, kevinearldenny commented
> In addition, one other error case I'd like to check for:
> 
> * If your file has a row with something that _looks like_ a valid blockid, but isn't actually (for example I sorted my file by block id and then incremented the highest number block id by 1), we won't flag that row, but also it won't get used. That seems like 💯 something we should flag

@maurizi good catch here 👍  I added in logic to check for invalid block IDs and return them as flags.

2021-04-26 19:23 UTC, kevinearldenny commented on src/server/test/districts.controller.e2e-spec.ts
> +        .expect({ districtsDefinition: [2, 1, 3] });
I added a new test, and it looks like it _should_ be returning as a success... but for some reason is being displayed as a failure. Any idea what's going on here?

```
DistrictsController › import plan from block equivalency CSV with invalid block id in first row › should return a flag

    expected {
      districtsDefinition: [ 2, 1, 3 ],
      rowFlags: [
        {
          rowNumber: 0,
          errorText: 'Invalid block ID',
          rowValue: [Array],
          field: 'BLOCKID'
        }
      ]
    } response body, got {
      districtsDefinition: [ 2, 1, 3 ],
      rowFlags: [
        {
          rowNumber: 0,
          errorText: 'Invalid block ID',
          rowValue: [Array],
          field: 'BLOCKID'
        }
      ]
    }
```

2021-04-27 14:30 UTC, maurizi commented on src/server/test/districts.controller.e2e-spec.ts
> +              rowValue: [100059900000024, 3],
This should fix the tests:
```suggestion
              rowValue: ["100059900000024", "3"],
```

2021-04-27 14:30 UTC, maurizi commented on src/server/test/districts.controller.e2e-spec.ts
> +        .expect({ districtsDefinition: [2, 1, 3] });
Left a comment on [the relevant line](https://github.com/PublicMapping/districtbuilder/pull/708/files#r621265820)

2021-04-27 15:42 UTC, maurizi requested changes
Some fairly simple cleanups left here, but functionally this is looking good 👍

2021-04-27 15:42 UTC, maurizi commented on src/server/src/districts/controllers/districts.controller.ts
> +    let flaggedRows: ImportRowFlag[] = [];
You can clean things up in this method by consolidating these two variables together and switching from an object type to an array (don't worry about the performance implications of an array w/ lots of empty elements, most modern JS implementations handle sparse arrays fairly well).

This also eliminates the need for the `FlaggedRows` and `MatchingRows` types in `shared/entities` (which probably shouldn't have been there to begin with, as they were exclusively used by this method, and were also **wrong** in using `string` as the type for `rowNumber`).

```diff
diff --git a/src/server/src/districts/controllers/districts.controller.ts b/src/server/src/districts/controllers/districts.controller.ts
index 925122f..5a2aff7 100644
--- a/src/server/src/districts/controllers/districts.controller.ts
+++ b/src/server/src/districts/controllers/districts.controller.ts
@@ -15,10 +15,8 @@ import {
   DistrictsDefinition,
   GeoUnitHierarchy,
   ImportRowFlag,
-  FlaggedRows,
   DistrictsImportApiResponse,
-  DistrictImportField,
-  MatchingRows
+  DistrictImportField
 } from "../../../../shared/entities";
 import { FIPS } from "../../../../shared/constants";
 import {} from "../../../../shared/entities";
@@ -41,11 +39,9 @@ export class DistrictsController {
     // Seemingly the simplest way of getting all the records into an array is to iterate in a for-loop :(
     /* eslint-disable */
     let records = [];
-    // Store object of row flags by row ID
-    let rowFlags: FlaggedRows = {};
     // Array of flagged rows to be returned
     let flaggedRows: ImportRowFlag[] = [];
-    let matchingRows: MatchingRows = {};
+    let matchingRows: boolean[] = [];
 
     function setFlag(
       row: string[],
@@ -54,9 +50,7 @@ export class DistrictsController {
       errorText: string
     ) {
       const flag = { rowNumber: rowNumber, errorText: errorText, rowValue: row, field: field };
-      flaggedRows.push(flag);
-      // @ts-ignore
-      rowFlags[rowNumber] = flag;
+      flaggedRows[rowNumber] = flag;
     }
 
     for await (const record of parser) {
@@ -84,21 +78,21 @@ export class DistrictsController {
       }
 
       // Check to see if rows match state fips
-      if (rowFips !== stateFips && !rowFlags[i]) {
+      if (rowFips !== stateFips && !flaggedRows[i]) {
         setFlag(record, i, "BLOCKID", "All geounits in an import must be within the same state");
       }
 
       // Check for duplicate block IDs
-      if (blockIdCounts[blockId] > 1 && !rowFlags[i]) {
+      if (blockIdCounts[blockId] > 1 && !flaggedRows[i]) {
         setFlag(record, i, "BLOCKID", "Duplicate BLOCKID included in import");
       }
 
-      if (isNaN(record[1]) && !rowFlags[i]) {
+      if (isNaN(record[1]) && !flaggedRows[i]) {
         setFlag(record, i, "DISTRICT", "Invalid district ID, must be numeric");
       }
     });
 
-    const unflaggedRows = records.filter((record, i) => !rowFlags[i]);
+    const unflaggedRows = records.filter((record, i) => !flaggedRows[i]);
 
     const blockToDistricts = Object.fromEntries(unflaggedRows);
 
@@ -140,21 +134,16 @@ export class DistrictsController {
     const districtsDefinition = mapToDefinition(geoCollection.getGeoUnitHierarchy());
     // Find unmatched records
     records.forEach((record, i) => {
-      if (!matchingRows[record[0]] && !rowFlags[i]) {
+      if (!matchingRows[record[0]] && !flaggedRows[i]) {
         setFlag(record, i, "BLOCKID", "Invalid block ID");
       }
     });
 
+    const rowFlags = flaggedRows.filter(r => !!r);
+
     return {
       districtsDefinition: districtsDefinition,
-      // Sort row flags by row number ascending
-      rowFlags:
-        flaggedRows.length > 0
-          ? // eslint-disable-next-line
-            flaggedRows.sort((a, b) => {
-              return a.rowNumber - b.rowNumber;
-            })
-          : undefined
+      rowFlags: rowFlags.length > 0 ? rowFlags : undefined
     };
   }
 }
diff --git a/src/shared/entities.d.ts b/src/shared/entities.d.ts
index 120789f..90605be 100644
--- a/src/shared/entities.d.ts
+++ b/src/shared/entities.d.ts
@@ -287,15 +287,6 @@ export interface ImportRowFlag {
   readonly rowValue: readonly string[];
 }
 
-export interface FlaggedRows {
-  readonly [rowNumber: string]: ImportRowFlag;
-}
-
-export interface MatchingRows {
-  // eslint-disable-next-line
-  [rowNumber: string]: boolean;
-}
-
 export interface DistrictsImportApiResponse {
   readonly districtsDefinition?: DistrictsDefinition;
   readonly rowFlags?: readonly ImportRowFlag[];
```

2021-04-27 15:42 UTC, maurizi commented on src/server/src/districts/controllers/districts.controller.ts
>            // TODO (GH#629) error handling could be more comprehensive here
error handling now more comprehensive ✔️  
```suggestion
```

2021-04-28 14:50 UTC, maurizi commented on src/client/screens/ImportProjectScreen.tsx
> +          // @ts-ignore
You can remove this `// @ts-ignore` by changing the type of the function from `Blob` to `File` (a subclass of `Blob`)

2021-04-28 14:55 UTC, maurizi requested changes
Just realized there is one more error we need to check for - we need to validate the specified number of districts is not less than the max district # in the supplied file (it's ok to be larger).

We should probably handle this error visually in a manner similar to how we do other validations on the number of districts field:
![image](https://user-images.githubusercontent.com/4432106/116425281-2d6d1a00-a810-11eb-9bb9-3a267e10abab.png)

2021-04-29 19:06 UTC, maurizi requested changes
Looking pretty good - just a few small cleanups to the most recent changes

2021-04-29 19:06 UTC, maurizi commented on src/client/screens/ImportProjectScreen.tsx
> +                                    : undefined
Having this in the `onChange` event caused it to be susceptible to a race condition similar to https://github.com/PublicMapping/districtbuilder/issues/652 when you change the number of districts before the API call is complete 

Moving this to a `useEffect` that takes place when _either_ `numberOfDistricts` or `maxDistrictId` changes fixes the issue:
```diff
diff --git a/src/client/screens/ImportProjectScreen.tsx b/src/client/screens/ImportProjectScreen.tsx
index 0354153..92bc976 100644
--- a/src/client/screens/ImportProjectScreen.tsx
+++ b/src/client/screens/ImportProjectScreen.tsx
@@ -253,6 +253,27 @@ const ImportProjectScreen = ({ regionConfigs }: StateProps) => {
     [regionConfigs, importNumberRef]
   );
 
+  useEffect(() => {
+    // Set error if number of districts less than max district ID
+    if (
+      formData.numberOfDistricts !== null &&
+      maxDistrictId !== undefined &&
+      formData.numberOfDistricts < maxDistrictId
+    ) {
+      setCreateProjectResource({
+        data: formData,
+        errors: {
+          error: "Invalid number of districts",
+          message: {
+            numberOfDistricts: [
+              `Number of districts must be at least the maximum district ID in the CSV, ${maxDistrictId} `
+            ]
+          }
+        }
+      });
+    }
+  }, [formData, maxDistrictId]);
+
   function resetForm() {
     // eslint-disable-next-line
     importNumberRef.current += 1;
@@ -420,20 +441,7 @@ const ImportProjectScreen = ({ regionConfigs }: StateProps) => {
                                 data: {
                                   ...formData,
                                   numberOfDistricts
-                                },
-                                errors:
-                                  maxDistrictId &&
-                                  numberOfDistricts !== null &&
-                                  numberOfDistricts < maxDistrictId
-                                    ? {
-                                        error: "Invalid number of districts",
-                                        message: {
-                                          numberOfDistricts: [
-                                            `Number of districts must be at least the maximum district ID in the CSV, ${maxDistrictId} `
-                                          ]
-                                        }
-                                      }
-                                    : undefined
+                                }
                               });
                             }
                           }}
```

2021-04-29 19:06 UTC, maurizi commented on src/client/screens/ImportProjectScreen.tsx
> +    setCreateProjectResource({ data: blankForm });
```suggestion
    setCreateProjectResource({ data: blankForm });
    setMaxDistrictId(undefined);
```

2021-04-29 20:50 UTC, maurizi approved these changes
Looks good 👍

2021-04-29 21:37 UTC, merged