Fix handling of switching into block editing when using keyboard shortcut
PublicMapping/districtbuilder pull request #758
Opened 2021-05-13 18:19 UTC by maurizi

## Overview

I moved most of the business logic into a helper function, which is called both by `MapHeader.tsx` as it used to be, as well as by the redux action, which allows the keyboard event handler to continue to be very simple.

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

## Testing Instructions

Switching between geolevels using S / F should behave _exactly_ as it does when clicking the buttons in the header

Scenarios to check:
 - A read-only map (I used an incognito window)
 - A map where you haven't done block editing before, as well as one where you have
 - How it behaves when there are pending changes

Closes #747

2021-05-13 21:48 UTC, kevinearldenny commented on src/client/actions/districtDrawing.ts
> +export const setGeoLevelIndex = createAction("Set geoLevel index")<readonly [number, boolean]>();
Might be helpful to add a comment here explaining what the params are, since it isn't super obvious what the boolean var is here

2021-05-13 21:50 UTC, kevinearldenny commented on src/client/reducers/districtDrawing.ts
> +          : isReadOnly || advancedEditingEnabled
```suggestion
          : isReadOnly || advancedEditingEnabled || index < geoLevelHierarchy.length - 1
```

Currently, if you attempt to toggle to a smaller geounit (e.g., `county` -> `blockGroup`), the modal is displayed even if you are not toggling to `block`. This modal should only be displayed toggling to `block`.

2021-05-13 21:56 UTC, kevinearldenny requested changes
I noticed a few bugs here - the Advanced Editing modal appears to get triggered when toggling from County -> Block Group, which shouldn't happen although this seems to be a fairly easy fix.

I also noticed that clicking `Start block editing` in the AdvancedEditingModal doesn't seem to set the current geolevel to `Blocks`, which seems like it could potentially be confusing for users.

2021-05-17 18:58 UTC, maurizi commented on src/client/actions/districtDrawing.ts
> +export const setGeoLevelIndex = createAction("Set geoLevel index")<readonly [number, boolean]>();
I decided to rework this to use an interface instead of a tuple for clarity.

2021-05-18 14:28 UTC, kevinearldenny approved these changes
LGTM 👍

2021-05-19 20:59 UTC, merged