Add configurable population deviation to project
PublicMapping/districtbuilder pull request #762
Opened 2021-05-17 20:52 UTC by kevinearldenny

## Overview

- Add `populationDeviation` field to Project defaulting to 0.05 for existing projects
- Add field to CreateProjectScreen for `populationDeviation`
- Leverage `populationDeviation` field for Evaluate Mode equal population view

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

![image](https://user-images.githubusercontent.com/66973361/118554814-ecda2f80-b72f-11eb-8591-5496ae9864bc.png)
![image](https://user-images.githubusercontent.com/66973361/118554989-26ab3600-b730-11eb-943c-2cc5450cf3db.png)

### Notes

- My gut feeling said to use decimal (0.05) instead of percentage (5) for _storing_ the data - but this would make things a little trickier to get the frontend to work as specified in the design.
- I couldn't get the % to line up properly in `CreateProjectForm` - seems like there is probably an easy solution here @jfrankl 
- Do we need to update the symbology / legend in the map here as well?

## Testing Instructions

- `./scripts/update`
- Create a new project, and set the `populationDeviation` to be something other than 0.05
- Add some area to a district to get it close to the specified `populationDeviation` threshold
- Open evaluate mode - expect Equal Population metric to be 

Closes #599

2021-05-17 21:10 UTC, kevinearldenny commented on src/client/screens/CreateProjectScreen.tsx
> +                      </Box>
@jfrankl Can you help with CSS to make the % appear inline with the `InputField`?

2021-05-17 21:11 UTC, kevinearldenny commented on src/server/migrations/1620920619830-project-population-deviation.ts
> +}
We might want to squash this into the other migration, but I left it separate in the event we wanted to revert it

2021-05-19 17:26 UTC, maurizi commented on src/client/components/evaluate/ProjectEvaluateSidebar.tsx
> +    (project && project.populationDeviation ? project.populationDeviation : 5) / 100.0;
Can we find all the places where we are using `5` as a literal value and move it to a `DEFAULT_POP_DEVIATION` (or similarly named) constant in `src/shared/constants.ts`?

We might want to change the default value in the future, it would be nice to not need to hunt it down everywhere.

2021-05-19 20:37 UTC, maurizi requested changes
Found a few bugs (setting deviation to `0` or a non-number just sets it to `5`, the API is returning deviation as a string not a number) as well as some suggested type cleanups

2021-05-19 20:37 UTC, maurizi commented on src/server/migrations/1620920619830-project-population-deviation.ts
> +}
I say squash em

2021-05-19 20:37 UTC, maurizi commented on src/server/src/projects/entities/project.entity.ts
> +  @Column({ type: "numeric", default: 5 })
A few issues here (and identical issues for `project-template.entity`)
 - If you look at the JSON response, it is returning `populationDeviation` as a string, not a number
 - If you look at the default value in the DB migration, it is setting it to the _string_ `'5'` not the number `5`.
  - We've _generally_ strived to use `camel_case` in the SQL schema by using the `name` option of `@Column({ ... })` to rename the columns (see `lockedDistricts` for an example)
  
Some small tweaks to the options will fix that
 - `"numeric"` is for arbitrary-precision numbers, `"double precision"` is what you want - that matches the underlying number type used by Javascript (https://www.postgresql.org/docs/13/datatype-numeric.html)
  - Using the lambda form of setting the default got it to make the default a number instead of a string cast to a number (which I guess would also work, but while you're updating this / reworking the migrations anyways you might as well change, it seems cleaner)
```suggestion
  @Column({ type: "double precision", name: "population_deviation", default: () => "5" })
```

2021-05-19 21:11 UTC, kevinearldenny commented on src/client/screens/CreateProjectScreen.tsx
> +                    populationDeviation: validatedForm.populationDeviation || 5,
@maurizi Is a deviation of 0 acceptable? It seems improbable that this would be something that someone would actually want to do, since it would be very difficult to _exactly_ match the expected population for all districts

2021-05-19 21:18 UTC, maurizi commented on src/client/screens/CreateProjectScreen.tsx
> +                    populationDeviation: validatedForm.populationDeviation || 5,
It is very much something people want to do - it's a legal requirement for Congressional districts within a state to have exactly equal populations (or as close to it as possible, off-by-one is allowed when needed), and it's a selling point of DistrictBuilder that we make it easy to work at the block-level to produce legal 0-deviation maps.

See this explainer from our partners Public Mapping http://www.publicmapping.org/what-is-redistricting/redistricting-criteria-equal-population

2021-05-19 21:24 UTC, kevinearldenny commented on src/server/src/projects/entities/project.entity.ts
> +  @Column({ type: "numeric", default: 5 })
@maurizi Should this be:

```
  @Column({ type: "double precision", name: "population_deviation", default: () => DEFAULT_POPULATION_DEVIATION })
```

or does it need to be cast to a string first?

```
  @Column({ type: "double precision", name: "population_deviation", default: () => `${DEFAULT_POPULATION_DEVIATION}` })
```

2021-05-20 00:03 UTC, maurizi commented on src/server/src/projects/entities/project.entity.ts
> +  @Column({ type: "numeric", default: 5 })
The latter is what we want, from looking at the SQL migrations generated after trying both options.

2021-05-21 18:40 UTC, jfrankl commented on src/client/screens/CreateProjectScreen.tsx
> +                      </Box>
![Screen Shot 2021-05-21 at 2 40 16 PM](https://user-images.githubusercontent.com/1809908/119183743-81030a00-ba42-11eb-8d85-fef457eb4d4f.png)

I just pushed a commit changing up the design slightly and addressing this.

2021-05-24 20:15 UTC, maurizi requested changes

2021-05-24 20:15 UTC, maurizi commented on src/client/components/evaluate/ProjectEvaluateSidebar.tsx
> +        avgPopulation && geojson && popThreshold
```suggestion
        avgPopulation && geojson && popThreshold !== undefined
```

2021-05-24 20:15 UTC, maurizi commented on src/client/components/map/Map.tsx
> +        project && project.populationDeviation ? project.populationDeviation : undefined
```suggestion
        project?.populationDeviation
```

2021-05-24 20:15 UTC, maurizi commented on src/client/components/map/index.ts
> +      : getChoroplethStops(metricKey);
This can be simplified:
```suggestion
  const steps = getChoroplethStops(metricKey, populationDeviation);
```

2021-05-24 20:15 UTC, maurizi commented on src/server/src/projects/entities/create-project.dto.ts
> +  @Max(100, { message: "Population deviation must be between 0% and 100%" })
We don't want to allow a negative deviation.
```suggestion
  @Max(100, { message: "Population deviation must be between 0% and 100%" })
  @Min(0, { message: "Population deviation must be between 0% and 100%" })
```

2021-05-24 20:15 UTC, maurizi commented on src/server/src/projects/entities/update-project.dto.ts
> +  @IsPositive({ message: "Population deviation must be positive" })
This won't work for `0`.
```suggestion
```

2021-05-24 20:15 UTC, maurizi commented on src/server/src/projects/entities/update-project.dto.ts
> +  @Max(100, { message: "Population deviation must be between 0% and 100%" })
As above in `create-project.dto`:
```suggestion
  @Max(100, { message: "Population deviation must be between 0% and 100%" })
  @Min(0, { message: "Population deviation must be between 0% and 100%" })
```

2021-05-24 20:15 UTC, maurizi commented on src/client/components/evaluate/ProjectEvaluateSidebar.tsx
> +          popThreshold &&
```suggestion
          popThreshold !== undefined &&
```

2021-05-24 20:15 UTC, maurizi commented on src/client/components/evaluate/detail/EqualPopulation.tsx
> -    const choroplethStops = getChoroplethStops(metric.key);
Another issue with a `0` deviation below here:

```diff
diff --git a/src/client/components/evaluate/detail/EqualPopulation.tsx b/src/client/components/evaluate/detail/EqualPopulation.tsx
index bd9e64a..c3264fc 100644
--- a/src/client/components/evaluate/detail/EqualPopulation.tsx
+++ b/src/client/components/evaluate/detail/EqualPopulation.tsx
@@ -90,7 +90,7 @@ const EqualPopulationMetricDetail = ({
       <Heading as="h2" sx={{ variant: "text.h5", mt: 4 }}>
         {metric.value?.toString() || " "} of {metric.total} districts are within{" "}
         {"popThreshold" in metric &&
-          metric.popThreshold &&
+          metric.popThreshold !== undefined &&
           ` ${Math.floor(metric.popThreshold * 100)}%`}{" "}
         of the target ({metric.avgPopulation && Math.floor(metric.avgPopulation).toLocaleString()})
       </Heading>
```

2021-05-26 17:12 UTC, maurizi commented on src/client/screens/CreateProjectScreen.tsx
> +      display: "flex"
This change is causing a styling regression when errors are displayed
```suggestion
```

2021-05-26 17:12 UTC, maurizi requested changes
Left 1 inline comment re: a styling regression

2021-05-27 16:10 UTC, maurizi approved these changes

2021-05-27 16:21 UTC, merged

2021-07-19 14:46 UTC, maurizi commented on src/client/screens/CreateProjectScreen.tsx
> +                        trying to make the exercise as realistic as possible
Let's have this match the new text used in https://github.com/PublicMapping/districtbuilder/pull/848/files