Update race column to handle different race categories
PublicMapping/districtbuilder pull request #766
Opened 2021-05-20 20:13 UTC by kevinearldenny

## Overview

- Adds fields for `nativeAmerican` and `pacificIslander` to demographics chart
- Allows for the existing split (with `Other`) to still be read and displayed

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

![image](https://user-images.githubusercontent.com/66973361/119042675-299f6400-b986-11eb-84a8-c4df57cdc2f1.png)
![image](https://user-images.githubusercontent.com/66973361/119042698-31f79f00-b986-11eb-8425-f6cd23f84ad4.png)

### Notes

I've noticed a few instances where `pacificIslander` is displayed as 0% - does it make sense to display this instead as "< 1%"?

## Testing Instructions

- Process the attached geojson for Delaware: `./scripts/manage process-geojson data/input/de.geojson -o data/output/Delaware -n 12,4,4 -x 12,12,12 -d "population:population,white:white,black:black,asian:asian,hispanic:hispanic,native:nativeAmerican,pacific:pacificIslander"`
- Add it to the database

Closes #764

2021-05-20 20:24 UTC, kevinearldenny commented on src/client/constants/colors.ts
> +  pacificIslander: "#89A53A",
@tgilcrest I just chose these kinda randomly, let me know once you have the correct colors decided upon

2021-05-20 20:48 UTC, tgilcrest commented on src/client/constants/colors.ts
> +  pacificIslander: "#89A53A",
I worked the colors out with Jeff. Let's use these for all the colors:

```
White - #FC8D62
Black - #66C2A5
Asian - #E78AC3
Hispanic - #8DA0CB
Native American - #A6D854
Pacific Islander - #FFD92F
```

2021-05-20 20:49 UTC, tgilcrest commented on src/client/constants/colors.ts
> +  pacificIslander: "#89A53A",
(This updates all of them to a palette from colorbrewer that is approved.)

2021-05-21 14:44 UTC, maurizi requested changes
Left one comment as just an FYI, but I think we need to fix the 2nd one that I left suggested changes for.

2021-05-21 14:44 UTC, maurizi commented on src/client/components/DemographicsTooltip.tsx
> +    .filter(race => percentages[race])
We want to continue to show the row if the field is there but the value is `0`
```suggestion
    .filter(race => percentages[race] !== undefined)
```

2021-05-21 15:00 UTC, maurizi commented
> Process the attached geojson for Delaware: `./scripts/manage process-geojson data/input/de.geojson -o data/output/Delaware -n 12,4,4 -x 12,12,12 -d "population:population,white:white,black:black,asian:asian,hispanic:hispanic,native:nativeAmerican,pacific:pacificIslander"`

FYI you can simplify that command a bit (you only need to provide key-value pairs if you're renaming): `./scripts/manage process-geojson data/input/de.geojson -o data/output/Delaware -n 12,4,4 -x 12,12,12 -d "population,white,black,asian,hispanic,native:nativeAmerican,pacific:pacificIslander"`

2021-05-21 16:10 UTC, maurizi approved these changes

2021-05-21 19:51 UTC, merged