List all published maps
PublicMapping/districtbuilder pull request #796
Opened 2021-05-26 21:07 UTC by kevinearldenny

## Overview

- Adds a new endpoint, `api/globalProjects` with server-side pagination
- Adds a new page in the frontend `/global` containing a display of all projects paginated with a limit of 10 projects per page
- Created a new reusable `PaginationFooter` component 

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

![image](https://user-images.githubusercontent.com/66973361/119730839-328bac00-be44-11eb-890b-08937a322caf.png)
![image](https://user-images.githubusercontent.com/66973361/119730869-39b2ba00-be44-11eb-8826-c58a60bd1434.png)

### Notes

I struggled a bit with the pagination implementation in Redux - initially, I was thinking that `globalProjectsFetchPage` should trigger `globalProjectsFetch`, but ended up having this handled through a param function + `useEffect` in `PaginationFooter`. After further reflection, this actually might not be a bad thing as far as making the component modular for usage in other pagination implementations - but we probably should clean up / rename the actions if we want to stick with this method.

## Testing Instructions

- Go to http://localhost:3003/global
- Make sure that you have at least 11 maps; expect pagination footer to be displayed
- Click on page 2 in the pagination footer; expect maps displayed on screen to change

Closes #719

2021-05-26 21:08 UTC, kevinearldenny commented on src/client/components/PaginationFooter.tsx
> +  }, [currentPage]);
Does this feel clunky?

2021-05-26 21:10 UTC, kevinearldenny commented on src/client/reducers/projects.ts
> +        );
Think I just figured out why this isn't working - it should be `Cmd.action` instead of `Cmd.run`, right?

That being said... do you like chaining these together better? Or would it be better to take the chained action out and rename this to `globalProjectsSetPage`?

2021-05-26 21:16 UTC, kevinearldenny commented on src/client/types.d.ts
> +
Reusable type created for any other places we decide to use `nestjs-typeorm-paginate`

2021-05-26 21:40 UTC, kevinearldenny commented on src/client/reducers/projects.ts
> +        );
```suggestion
      case getType(globalProjectsSetPage):
        return {
            ...state,
            globalProjectsPagination: { ...state.globalProjectsPagination , currentPage: action.payload }
          };
```

In the current solution (where `PaginationFooter` is watching for a change in `pagination.currentPage` and then calling `globalProjectsFetch()` in `onPageChange`, this is unnecessary. However, I'm going back and forth on whether I like the current architecture more than what I was _originally_ thinking here of `globalProjectsFetchPage`. Curious your thoughts, @maurizi

2021-05-27 20:57 UTC, maurizi commented on src/client/screens/PublishedMapsListScreen.tsx
> +          <Box sx={style.projects}>
Using `as const` for `style` will fix the typing issues.

```suggestion
} as const;

const PublishedMapsListScreen = ({ globalProjects, user, pagination }: StateProps) => {
  useEffect(() => {
    !globalProjects && store.dispatch(globalProjectsFetch());
  }, [globalProjects]);

  return (
    <Flex sx={{ height: "100%", flexDirection: "column" }}>
      <SiteHeader user={user} />
      <Box>
        {globalProjects ? (
          <Box sx={style.projects}>
```

2021-05-27 20:57 UTC, maurizi commented on src/server/src/projects/controllers/globalProjects.controller.ts
> +@Crud({
Why are we using `@Crud()` at all for this controller? Do we even use any of it's features? It doesn't look like `getAllGlobalProjects` does.

2021-05-27 20:57 UTC, maurizi commented on yarn.lock
> +
Similar to above - Why is this in the `client` `yarn.lock`?

2021-05-27 20:57 UTC, maurizi commented on package.json
> +    "nestjs-typeorm-paginate": "^2.5.1",
Isn't this a server-side library? Why is it in the `package.json` for `client`?

2021-05-27 20:57 UTC, maurizi commented on src/client/screens/PublishedMapsListScreen.tsx
> +        {globalProjects ? (
In practice I find it very difficult to interact with this UI element when it is switched to a loading icon after I click the pagination button.

Can we follow the strategy used in https://github.com/PublicMapping/districtbuilder/pull/675/files and keep a copy of `globalProjects` to keep this from happening?

2021-05-27 20:57 UTC, maurizi commented on src/client/components/PaginationFooter.tsx
> +        </li>
```suggestion
        <li
          key={number}
          id={number.toString()}
          sx={number === currentPage ? style.paginationSelected : style.pagination}
        >
          <Button disabled={number === currentPage} onClick={() => setPage(number)}>{number}</Button>
        </li>
```

2021-05-27 20:57 UTC, maurizi commented on src/client/components/PaginationFooter.tsx
> +    /* eslint-enable */
Consider replacing this with [`_.range(1, totalPages)`](https://lodash.com/docs/4.17.15#range)

2021-05-27 20:57 UTC, maurizi commented on src/client/components/PaginationFooter.tsx
> +  }, [currentPage]);
Yes - I think your initial instinct to have `globalProjectsFetchPage` trigger `globalProjectsFetch` was the right one.

2021-05-27 21:11 UTC, maurizi requested changes
In general this is functional (and I like `nestjs-typeorm-paginate`, that made the backend very simple 😄 ), but could use some polish - I left a few comments with changes I'd like to see.

Also, can you open an issue to do a style pass on this page + label it `design`?

2021-05-27 21:11 UTC, maurizi commented on src/client/components/PaginationFooter.tsx
> +  const [startingPage, setStartingPage] = useState<number | undefined>(undefined);
`pageNumbers` is just a simple transformation of the provided parameters, there is no need to keep these in component state - you can just directly assign it:

```typescript
  const pageNumbers = _.range(1, totalPages);
```

2021-05-28 16:20 UTC, kevinearldenny commented
> In general this is functional (and I like `nestjs-typeorm-paginate`, that made the backend very simple 😄 ), but could use some polish - I left a few comments with changes I'd like to see.
> 
> Also, can you open an issue to do a style pass on this page + label it `design`?

Added a new design issue #799

2021-06-02 14:01 UTC, maurizi requested changes
This is looking really nice, just needs some lint cleanup as well as the comment I left a suggestion for addressed.

2021-06-03 14:01 UTC, maurizi approved these changes
Looking good 👍

2021-06-03 14:41 UTC, merged