Add tooltip for population deviation in project sidebar
PublicMapping/districtbuilder pull request #819
Opened 2021-06-14 16:58 UTC by kevinearldenny

## Overview

Adds a tooltip to the population deviation display in the project sidebar to help users to more easily identify the necessary changes to the district for compliance with the population deviation threshold.

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

![image](https://user-images.githubusercontent.com/66973361/121930170-0f9c3b80-cd10-11eb-9aea-0edd32ba267a.png)

## Testing Instructions

- Create districts that are under the population threshold, within the population threshold tolerance, and above it
- Hover over population deviation displays - expect tooltips to be displayed for all districts

Closes #802

2021-06-14 18:54 UTC, maurizi commented
@jfrankl What do we want the tooltip to say for the unassigned district? Mentioning the 5% population threshold there seems odd since the goal for the unassigned district is always 0, regardless of the population threshold.

Or should we just skip the tooltip for the unassigned district?

2021-06-14 19:18 UTC, jfrankl commented
Good question. @tgilcrest any thoughts?

2021-06-15 12:49 UTC, tgilcrest commented
When deviation >0:
>This is the population "unassigned" to any district. Make sure all population is assigned to a district to complete your map.

When deviation =0:
>All population has been assigned to a district.

Thoughts?

2021-06-15 16:49 UTC, kevinearldenny commented
> When deviation >0 (edited):
> 
> > This population is not assigned to any district. Make sure all population is assigned to a district to complete your map.
> 
> When deviation =0:
> 
> > All population has been assigned to a district.
> 
> Thoughts?

Makes sense to me. I've implemented this as suggested: 
![image](https://user-images.githubusercontent.com/66973361/122092558-10000980-cdd8-11eb-859d-5af52c02455b.png)

2021-06-15 17:03 UTC, jfrankl commented
Looks good to me. Thanks @tgilcrest for the suggestion and @kevinearldenny for the implementation.

2021-06-17 20:37 UTC, maurizi requested changes
Just one small tweak needed

2021-06-17 20:37 UTC, maurizi commented on src/client/components/ProjectSidebar.tsx
> +                    Add {Math.floor(intermediateDeviation + popDeviationThreshold).toLocaleString()}{" "}
We don't want a negative number here:
```suggestion
                    Add {Math.floor(Math.abs(intermediateDeviation) + popDeviationThreshold).toLocaleString()}{" "}
```

2021-06-23 15:19 UTC, maurizi approved these changes
Looks good to me 👍

2021-06-23 15:21 UTC, merged