Add evaluate mode view for competitiveness
PublicMapping/districtbuilder pull request #824
Opened 2021-06-15 19:42 UTC by kevinearldenny

## Overview

- Adds a newly computed metric for Competitiveness, computed as the average PVI for all districts that have population
- Adds a new page for Competitiveness metric including a map and sidebar

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

![image](https://user-images.githubusercontent.com/66973361/122113325-f2d73500-cdef-11eb-985b-41de270514dc.png)

### Notes

Per my Slack conversation earlier with @maurizi , there is still some ambiguity about whether we want to allow a switch for PVI / election margin to display both metrics here. These will likely be very similar, 

## Testing Instructions

- Create a map in a region that has voting data
- Create districts
- Go to evaluate mode - Competitiveness and review. Expect the PVI computations to match those included in the Project Sidebar

Closes #810

2021-06-23 17:22 UTC, maurizi requested changes
Left a few comments w/ suggested changes, but functionally this seems to be working well 👍 .

2021-06-24 20:45 UTC, maurizi requested changes
I was ready to 👍 but a last minute check revealed a bug: when I go to the Competitiveness page for a project w/ districts assigned yet, the page locks up

2021-06-29 16:43 UTC, kevinearldenny commented
The bug that Mike identified should be fixed now

2021-07-06 16:46 UTC, pcaisse requested changes
Tested well! Left some comments.

2021-07-06 16:46 UTC, pcaisse commented on src/client/functions.ts
> +export function calculatePVI(voting: DemographicCounts, year?: ElectionYear): number | undefined {
Could we add a docstring to this function describing what the output of this function means? It took me a sec to realize that a positive number means `D+` and negative means `R+`

It might also be good to add a link explaining how the index is calculated (eg. https://cookpolitical.com/pvi-0)

2021-07-06 19:25 UTC, kevinearldenny commented on src/client/components/evaluate/detail/Competitiveness.tsx
> +  }
@pcaisse I'm running into some challenges with the type here - when trying out the type that you suggested, I'm receiving the following error which I'm having some trouble figuring out. Any suggestions on how to fix?

```
TypeScript error in /home/node/app/src/client/components/evaluate/detail/Competitiveness.tsx(101,70):
client_1    | Argument of type '(string | number)[][]' is not assignable to parameter of type 'readonly (readonly [number, string])[]'.
client_1    |   Type '(string | number)[]' is missing the following properties from type 'readonly [number, string]': 0, 1  TS2345
```

2021-07-06 19:41 UTC, kevinearldenny commented on src/client/types.d.ts
> +export type ElectionYear = "16" | "20" | "0";
`combined` works fine here.

2021-07-06 19:48 UTC, kevinearldenny commented on src/client/components/evaluate/detail/Competitiveness.tsx
> +  }
Nevermind - I was actually able to fix this by explicitly defining the types in `index.ts` 😄

2021-07-06 19:48 UTC, pcaisse commented on src/client/components/evaluate/detail/Competitiveness.tsx
> +  }
So the type `(string | number)[][]` would be an array of an array of strings _or_ numbers, which is what the type checker thinks is the type being returned by `getPviSteps`, instead of an array of 2-item tuples like `[number, string]`. To resolve the issue, we need to tell the type checker more precisely what the type is.

I would first create a type in `src/client/types.d.ts` like so:
```ts
export type ChoroplethStops = readonly (readonly [number, string])[];
```

And then modify the functions that return stops in `src/client/components/map/index.ts` (`getCompactnessStops`, `getPviSteps`, and `getEqualPopulationStops`) to return a `ChoroplethStops` and also have `computeRowFill` take a `ChoroplethStops`.

2021-07-06 19:53 UTC, kevinearldenny commented on src/client/functions.ts
> +export function calculatePVI(voting: DemographicCounts, year?: ElectionYear): number | undefined {
This is mentioned [a few lines up ](https://github.com/PublicMapping/districtbuilder/blob/ff5ce6f38cecc1517ca604c17820a250badfbbe9/src/client/functions.ts#L66), and all of the code in between is related to PVI computation. But, I added a docstring here if you feel that is important

2021-07-06 20:02 UTC, kevinearldenny commented on src/client/components/evaluate/detail/Competitiveness.tsx
> +  }
Looks like we arrived at the [same solution here at the same time](https://github.com/PublicMapping/districtbuilder/pull/824/commits/f904381431f9c42db7d6d5b22b51df59be967612) 😄

2021-07-06 21:28 UTC, kevinearldenny commented
@pcaisse In the process of refactoring `computeRowFill()`, I identified two things:

1. The process of computing fills is different for Equal Population, since we are using an interval fill
2. We really should be using an interval fill for Competitiveness as well - the map display was previously displaying inaccurately!

These should be fixed now in the commit I am pushing shortly

2021-07-07 15:49 UTC, pcaisse approved these changes
This is looking good! I went ahead and approved but I did see one thing that we should fix:

![db_lorem_ipsum](https://user-images.githubusercontent.com/2926237/124787952-eccc0400-df16-11eb-9a75-3878d1bbab5c.png)

It looks like the competitiveness metric is missing `shortText` and `longText` which is causing the placeholder Latin text to be shown (we should probably make those no longer be optional on `BaseEvaluateMetric` at this point and delete the Latin from the component).

Also, one workflow thing I noticed is that you pasted error messages from the log output of the running services. What I like to do for fast feedback for frontend development is to run `yarn watch` on the host from within `src/client` (or `./scripts/yarn client watch` to run it in the container). That way I can see all the errors and chip away at them until it compiles successfully and _then_ run the app to test in the browser. The more you leverage types, the more "if it compiles, it works" is true! I tend to 1) think about the shape of my data, 2) encode that in my types, 3) and then write functions to manipulate the data in that order, rinse & repeat, and then manually test at the end. (This tends to work less well for UX/design/CSS heavy work.)

2021-07-07 16:11 UTC, kevinearldenny commented
> This is looking good! I went ahead and approved but I did see one thing that we should fix:
> 
> ![db_lorem_ipsum](https://user-images.githubusercontent.com/2926237/124787952-eccc0400-df16-11eb-9a75-3878d1bbab5c.png)
> 
> It looks like the competitiveness metric is missing `shortText` and `longText` which is causing the placeholder Latin text to be shown (we should probably make those no longer be optional on `BaseEvaluateMetric` at this point and delete the Latin from the component).
> 

I don't believe that we have any copy written for this - I'm opening a new issue to write copy for `shortText` and `longText` and assigning to @dmcglone so that we can merge and this doesn't hold up progress on dev issues.

2021-07-07 16:27 UTC, merged