Add Majority Minority evaluate view
PublicMapping/districtbuilder pull request #839
Opened 2021-06-25 15:37 UTC by kevinearldenny

## Overview

Adds an evaluate mode view for Majority Minority

- Majority race computed and displayed in sidebar
- Demographics chart included in sidebar
- Majority race and psuedo-choropleth (darker colors for greater share of majority race) included in map

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

![image](https://user-images.githubusercontent.com/66973361/123449266-7f7cb280-d5a9-11eb-9661-e136ae740460.png)

### Notes

I cribbed the colors from the wireframe, but I think we might be able to put a bit more thought into them. If a district is _not_ majority-minority (i.e., is majority white), the fact that it is displayed in green seems a little weird to me. I think we could probably improve the overall color scheme a bit to more effectively communicate the info that we want users to focus on @jfrankl @tgilcrest 

## Testing Instructions

- Create a map with districts that are majority-minority
- Open evaluate mode - expect districts to be included in count in summary
- Open Majority-Minority detail page - expect districts to be identified as majority-minority in sidebar and displayed on map

Closes #750

2021-06-25 15:42 UTC, kevinearldenny commented on src/client/components/evaluate/detail/MajorityRace.tsx
> +                        {/* {isMinorityMajority && <span sx={style.minorityMajorityFlag}>*</span>} */}
Wasn't sure if we wanted to persist the majority-minority flag implemented in #763 here next to the demographics chart as well @tgilcrest

2021-07-13 21:05 UTC, ddohler requested changes
This is working well and the code is looking pretty good, but I had a number of comments / suggestions for cleanup in various areas. They're all relatively minor, I think, so hopefully it should be fairly quick to do a cleanup pass and knock them all out, but by the same token, if time is of the essence, we could push them off onto other tasks, since some of them involve changes to existing code that's outside the immediate scope of this task.

2021-07-13 21:26 UTC, kevinearldenny commented on src/client/components/evaluate/detail/MajorityRace.tsx
> +            (feature, id) =>
Hmmm, I'm not entirely sure that I follow this suggestion insofar in the context of the `MajorityRace` component - however, the logic for `isMajorityMinority` is duplicated across `ProjectSidebar` and `ProjectEvaluateSidebar`, so I took your advice as it relates to that logic. 

The difference here in the `MajorityRace` component is that we are not concerned with _if_ it is a majority-minority district, we are concerned what the majority race _is_ - and this is being computed as a new field on the geojson.

2021-07-13 21:28 UTC, kevinearldenny commented on src/client/components/map/Map.tsx
> +        const demographics = Object.keys(feature.properties.demographics);
The `DemographicCounts` type is a generic key-value object, so the type checking is less strict here I believe. However, you're right in that I should add an `&& feature.properties.demographics.population > 0` here

2021-07-13 21:33 UTC, kevinearldenny commented on src/client/components/map/Map.tsx
> +              // eslint-disable-next-line
Hmmm, I'm getting a compiler error when trying this: `Definition for rule 'functional/immutable-data' was not found`

2021-07-14 12:26 UTC, ddohler commented on src/client/components/map/Map.tsx
> +              // eslint-disable-next-line
Oh interesting. I tried that on my end and I thought it had worked, but perhaps I didn't get the suggestion quite right. If you remove the `// eslint-disable-next-line` comment entirely, you should start seeing an error when you run `./scripts/yarn client lint`, and then you should be able to put that error name into the comment to re-ignore it. Does that work?

2021-07-14 12:30 UTC, ddohler commented on src/client/components/map/Map.tsx
> +        const demographics = Object.keys(feature.properties.demographics);
Ohhh, I see what's happening now, the use of `feature.properties.demographics.population` in the `if`-statement made me see that everywhere but it's totally not, it's `feature.properties.demographics` used elsewhere, which is definitely an Object, not a number. Ignore me 🤦

2021-07-14 12:53 UTC, ddohler commented on src/client/components/evaluate/detail/MajorityRace.tsx
> +            (feature, id) =>
My point here was that all of the constituent checks in `isMajorityMinority()` (that is, `f.properties.majorityRace && f.properties.majorityRace !== "white" && f.id !== 0`) also happen in this file:
- `f.id !== 0` [occurs on line 88](https://github.com/PublicMapping/districtbuilder/pull/839/files#diff-b0b757bc8bfe9d2b4368a93166cc9394428cc4a8860a28279ef1eaa7e3c3e401R88)
- `feature.properties.majorityRace &&` occurs on [line 93](https://github.com/PublicMapping/districtbuilder/pull/839/files#diff-b0b757bc8bfe9d2b4368a93166cc9394428cc4a8860a28279ef1eaa7e3c3e401R93) (as `f.properties.majorityRace !== undefined`)
- `f.properties.majorityRace !== "white"` used to be on line 118, but it has been replaced with the call to `isMajorityMinority()`. And the reason it was able to be just `f.properties.majorityRace !== "white"` and not include the other checks is because it was nested inside the two checks above that accounted for the rest of the condition already.

So my suggestion was to pull out the checks at lines 88, 93, and 118 into a single call to `isMajorityMinority()` at the top, like this:
```
{geojson?.features.map(
            (feature) => {isMajorityMinority(feature) ? ... : ... }
)}

Anyway, that's all just to try to explain the suggestion more clearly. I think the way you've changed it is good -- my way would have collapsed a couple of the nesting levels, but at the cost of duplication in the JSX. This way keeps the nesting but doesn't duplicate anything, which is also fine and probably better. 👍

2021-07-14 17:57 UTC, kevinearldenny commented on src/client/components/map/Map.tsx
> +              // eslint-disable-next-line
No, I'm actually still seeing `functional/immutable-data` as the rule that is being violated - but it doesn't seem to like the idea of me ignoring just that rule in an inline comment `// eslint-disable-next-line functional/immutable-data` and is giving me compiler error

2021-07-14 18:00 UTC, kevinearldenny commented on src/client/components/map/Map.tsx
> +              <Box sx={{ display: "inline-block" }} key={race}>
I talked to @jfrankl about this, and he proposed using a table - should be fixed up now though:

![image](https://user-images.githubusercontent.com/66973361/125670293-21be6c61-a1db-477b-9dad-58d9000e8336.png)

2021-07-14 18:01 UTC, kevinearldenny commented on src/client/components/map/Map.tsx
> +      {evaluateMode && evaluateMetric && evaluateMetric.key === "majorityMinority" && (
Okay, opened an issue: https://github.com/PublicMapping/districtbuilder/issues/849

2021-07-15 16:38 UTC, ddohler commented on src/client/components/evaluate/detail/MajorityRace.tsx
> +                        {/* {isMinorityMajority && <span sx={style.minorityMajorityFlag}>*</span>} */}
Has this been resolved? Does @dmcglone need to weigh in?

2021-07-15 16:41 UTC, ddohler approved these changes
This looks good to me; it looks like there were one or two outstanding questions at the time this was written (about color ramp and whether to preserve the flag from #763 ) but once those are answered this is good to go.

2021-07-15 16:41 UTC, ddohler commented on src/client/components/map/index.ts
> +    [-1.0 * avgPopulation, "#c1e5f0"],
Nice to unify the capitalization across the file.

2021-07-15 17:04 UTC, dmcglone commented on src/client/components/evaluate/detail/MajorityRace.tsx
> +                        {/* {isMinorityMajority && <span sx={style.minorityMajorityFlag}>*</span>} */}
Thanks. In my understanding, this view is *only* displaying the majority-minority districts it seems we don't really need that flag to persist in the list view of districts on this page.

2021-07-15 19:32 UTC, merged