Add populationDeviation and Chamber selection to Import Project screen
PublicMapping/districtbuilder pull request #845
Opened 2021-07-08 19:07 UTC by kevinearldenny

## Overview

- Add populationDeviation and Chamber selection to Import Project screen
- Create chambers in `./scripts/load-dev-data` so that chambers are available for PA and IL

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

![image](https://user-images.githubusercontent.com/66973361/124976911-d8af0200-dffd-11eb-85a2-9f4fcbe851b4.png)

### Notes

To test this, we need to have chambers in the DB - I thought we had these, but they seem to have been removed from `load-dev-data` at some point. I added back in SQL to create chambers for PA and IL

## Testing Instructions

- `./scripts/load-dev-data`
- Import Project - drag a CSV (such as one attached)
- Expect: Chambers listed for PA or IL, population deviation box displayed
- Select a chamber, and a populationDeviation that is something other than 5
- Expect: Project is imported with the specified parameters

Closes #628

2021-07-19 13:49 UTC, maurizi commented on scripts/load-dev-data
> +
🎆

2021-07-19 14:42 UTC, maurizi requested changes
Thanks for the changes to `load-dev-data`, that's a nice productivity-improvement.

I left a few comments re: cleaning up the types and making sure we post the correct data (we're not handling deviation = 0 correct, and we're not including the selected Chamber).

2021-07-19 14:42 UTC, maurizi commented on src/client/screens/ImportProjectScreen.tsx
> +  const populationDeviation = form.populationDeviation || DEFAULT_POPULATION_DEVIATION;
```suggestion
  const populationDeviation = form.populationDeviation;
```

2021-07-19 14:42 UTC, maurizi commented on src/client/screens/ImportProjectScreen.tsx
> +    populationDeviation &&
```suggestion
    populationDeviation !== null &&
```

2021-07-19 14:42 UTC, maurizi commented on src/client/screens/ImportProjectScreen.tsx
> +  readonly populationDeviation: number;
You should match the existing style of the surrounding code - it uses `null` for missing data, not `undefined` (which is what using `?` implies).
Additionally
 - it is possible for someone to leave the population deviation field empty, so we should represent that state in our `InvalidForm` type.
 - `isCustom` shouldn't be optional
```suggestion
  readonly chamber: IChamber | null;
  readonly districtsDefinition: DistrictsDefinition | null;
  readonly numberOfDistricts: number | null;
  readonly isCustom: boolean;
  readonly populationDeviation: number | null;
```

2021-07-19 14:42 UTC, maurizi commented on src/client/screens/ImportProjectScreen.tsx
> +  readonly isCustom?: boolean;
```suggestion
  readonly isCustom: boolean;
```

2021-07-19 14:42 UTC, maurizi commented on src/client/screens/ImportProjectScreen.tsx
> +  readonly isCustom?: boolean;
I don't think `isCustom` should ever be `null` / `undefined` right? - the checkbox is either checked or not.
```suggestion
  readonly isCustom: boolean;
```

2021-07-19 14:42 UTC, maurizi commented on src/client/screens/ImportProjectScreen.tsx
> +  readonly chamber?: IChamber;
The code you added actually uses `null` not undefined.

```suggestion
  readonly chamber: IChamber | null;
```

2021-07-19 14:42 UTC, maurizi commented on src/client/screens/ImportProjectScreen.tsx
> +    : { numberOfDistricts, regionConfig, districtsDefinition, populationDeviation, valid: false };
Note that this function needs to add `chamber` to the returned data here as well, which will require that type being added to `ConfigurableForm`.

Right now when I select a `Chamber` the frontend is _merely_ using that to set `numberOfDistricts` - we should include `chamber` in our POST data as well.

2021-07-19 18:16 UTC, kevinearldenny commented on src/client/screens/ImportProjectScreen.tsx
> +    : { numberOfDistricts, regionConfig, districtsDefinition, populationDeviation, valid: false };
Chamber should now be saved with an imported project, and popDeviation of 0 should be handled properly

2021-07-21 16:32 UTC, maurizi approved these changes
Working great 👍

2021-07-21 16:56 UTC, merged