Add button to competitiveness page for uploading a plan to PlanScore
PublicMapping/districtbuilder pull request #847
Opened 2021-07-12 20:50 UTC by kevinearldenny

## Overview

- Add button to competitiveness page for uploading a plan to PlanScore
- Add new endpoint to upload to PlanScore API from backend
- Open PlanScore in new window when API response received

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

![image](https://user-images.githubusercontent.com/66973361/125352792-b2f06880-e32f-11eb-97ff-45c8e386ea46.png)
![image](https://user-images.githubusercontent.com/66973361/125352862-cd2a4680-e32f-11eb-97bb-c2bcd6004dd7.png)
![image](https://user-images.githubusercontent.com/66973361/125353469-9a348280-e330-11eb-9ac2-54535ccce3d7.png)

### Notes

- The "Open in new tab" suggestion feels a bit clunky to me. By default, Chrome seems to block the popup for me on localhost unless I explicitly allow it. Personally, I might prefer a link to be displayed in the sidebar or in a new modal allowing the user to open the PlanScore result in a new tab at their leisure.

- it seems like bad etiquette for us to allow users to ping PlanScore's API multiple times for a district plan that has not changed. One potential idea I had to rectify this would be to store the `plan_score_url` received from the API and the `plan_score_last_updated_dt` of when the PlanScore was last computed, and to disable the 'Send to PlanScore' button unless the Project's `updatedDt` is more recent than the last time PlanScore was checked. 

- It might also be nice to add some feedback that the PlanScore API is processing the request - we could use the existing spinner from the project, but I'm curious to see if @jfrankl has any other ideas

## Testing Instructions

- `./scripts/update`
- Open a finished project and navigate to the Competitiveness metric page
- Click the `Send to PlanScore API` button and wait for a new window to appear. Note that you may need to enable popups on localhost for the popup to appear
- Expect: A new window indicating successful upload to PlanScore appears
- Wait a minute and refresh the PlanScore window - expect the PlanScore report for the district to be computed

Closes #838

2021-07-19 13:40 UTC, maurizi requested changes
> The "Open in new tab" suggestion feels a bit clunky to me. By default, Chrome seems to block the popup for me on localhost unless I explicitly allow it. Personally, I might prefer a link to be displayed in the sidebar or in a new modal allowing the user to open the PlanScore result in a new tab at their leisure.

Yeah - based on how their API works I agree that I think we'll want the user to do two clicks - one to initiate uploading to PlanScore, and a second to open the results in a new tab - triggering the popup-blocker seems like the wrong way to go about this to me.

@jfrankl what do you think of the following:
 - Users clicks "Send to PlanScore" button
 - Buttons changes to "Sending to PlanScore 🔃" w/ a built-in spinner
 - When ready button changes to "View on PlanScore"
 
 If that is too subtle I'd say we should go w/ a new modal as Kevin suggested.

2021-07-19 13:40 UTC, maurizi commented on src/server/src/projects/controllers/projects.controller.ts
> +    const planScoreToken = "Hrnt68Zy";
Um... by posting this on a public repository we're going to need to ask PlanScore retire this API key and provide us w/ a new one (I'm assuming it's not meant to be public since it is being used in a server-side API).

As for how we _should_ handle this - https://github.com/PublicMapping/districtbuilder/pull/338 shows a good example of how to add a new secret to the application - look for how `rollbar_access_token` / `ROLLBAR_ACCESS_TOKEN` get threaded through the application. Note also that you'll need to add the new environment to the Terraform configs in AWS - they're located in these buckets:
https://github.com/PublicMapping/districtbuilder/blob/e38c66bb6f079c69670d782a3a50910df5f85d67/Jenkinsfile.release#L43
https://github.com/PublicMapping/districtbuilder/blob/e38c66bb6f079c69670d782a3a50910df5f85d67/Jenkinsfile#L14

Additionally we should add something in the README on setting up the PlanScore API key locally for dev/testing - likely by using a `.env` file we hide via our `.gitignore`, like we do for [Treetective](https://github.com/azavea/treetective#setup) (maybe with a `.env.sample` file for documentation purposes?)

2021-07-20 16:29 UTC, jfrankl commented
> * Users clicks "Send to PlanScore" button
> * Button is disabled, & changes to "Sending to PlanScore 🔃" w/ a built-in spinner
> * When ready button is re-enabled & changes to "View on PlanScore", and remains this way until the user makes changes to their plan

@maurizi this is great. One change I'd make: on that third step, instead of re-enabling the button, let's replace it with a link that reads "View on PlanScore". I think the change from a button to a link will make it extra clear to the user that something has changed and now a link is ready for them to click.

2021-07-20 18:39 UTC, kevinearldenny commented
> > * Users clicks "Send to PlanScore" button
> > * Button is disabled, & changes to "Sending to PlanScore 🔃" w/ a built-in spinner
> > * When ready button is re-enabled & changes to "View on PlanScore", and remains this way until the user makes changes to their plan
> 
> @maurizi this is great. One change I'd make: on that third step, instead of re-enabling the button, let's replace it with a link that reads "View on PlanScore". I think the change from a button to a link will make it extra clear to the user that something has changed and now a link is ready for them to click.

Okay, I have implemented this now. The spinner is a bit hard to see on the button currently, though so we could possibly use a style pass here although I'm not sure how necessary this is.

2021-07-21 17:22 UTC, maurizi requested changes
Looking good, just a few small changes needed

2021-07-21 17:22 UTC, maurizi commented on src/client/components/evaluate/detail/Competitiveness.tsx
> +            onClick={() => sendToPlanScore()}
We should disable the button while the request is pending to avoid duplicate requests
```suggestion
            onClick={() => sendToPlanScore()}
            disabled={planScoreLoaded === false}
```

2021-07-21 17:22 UTC, maurizi commented on docker-compose.ci.yml
> +      - DB_PLAN_SCORE_API_TOKEN
I don't think this is needed
```suggestion
```

2021-07-21 17:22 UTC, maurizi commented on src/server/.env.sample
> +PLAN_SCORE_TOKEN=<YOUR KEY HERE>
```suggestion
PLAN_SCORE_API_TOKEN=<YOUR KEY HERE>
```

2021-07-21 17:22 UTC, maurizi commented on src/client/components/evaluate/detail/Competitiveness.tsx
> +  };
```suggestion
```

2021-07-22 15:51 UTC, maurizi approved these changes
👍

2021-07-22 17:29 UTC, merged