Add maps to list of user projects on home screen
PublicMapping/districtbuilder pull request #850
Opened 2021-07-14 21:15 UTC by kevinearldenny

## Overview

Add maps to user project cards on home screen

- Add pagination to `/api/projects` endpoint

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

![image](https://user-images.githubusercontent.com/66973361/125693683-2b6bd225-88d6-482c-ad16-71c40d51e6e8.png)

### Notes

The CSS is a bit wonky currently, this might need a style pass.

Additionally, I'm not totally sold on my direction of editing the `/api/projects` endpoint - it seems like it might have been a better idea to refactor the `globalProjects` endpoint to support filtering to only the user's projects. Extrapolating this further - could we possibly combine both of these screens into a single screen, with an option to view user projects or global projects? It seems like there is a lot of redundancy here, and especially if we want to support filtering in global projects (#833 ) it would be nice to have this in user projects as well .

## Testing Instructions

- `./scripts/server`
- With more than 4 projects, expect to see pagination and maps displayed for each project

Closes #790

2021-07-20 17:34 UTC, kevinearldenny commented on src/server/src/projects/services/projects.service.ts
> +  }
Refactor this + `findAllProjectsPaginated` into a single function with helper functions to apply the where clauses for `user` and `published`

2021-07-22 16:04 UTC, maurizi requested changes
Overall working and looking good - I left some comments inline on suggested changes.

2021-07-22 16:04 UTC, maurizi commented on src/server/src/projects/services/projects.service.ts
> +    const builder = this.getProjectsBase().andWhere("user.id = :userId", { userId });
This _also_ needs to filter out `archived` projects.
```suggestion
    const builder = this.getProjectsBase().andWhere(
      "project.archived = FALSE AND user.id = :userId",
      { userId }
    );
```

2021-07-22 18:16 UTC, kevinearldenny commented on src/client/components/HomeScreenProjectCard.tsx
> +export default HomeScreenProjectCard;
Good idea. Implemented now with a new `ProjectDistrictsMap` component

2021-07-23 14:44 UTC, maurizi requested changes
Just a few small changes needed.

2021-07-23 14:44 UTC, maurizi commented on src/client/components/map/ProjectDistrictsMap.tsx
> +    });
React is showing a warning in the console re: this handler:
![image](https://user-images.githubusercontent.com/4432106/126794707-276ecfc2-27d1-4417-9436-3c05c66f08a9.png)

We need to turn off the `load` event handler if/when the React component gets unloaded - otherwise as the warning indicates we'll have a memory leak. In this case that includes the Mapbboxgl map, so this could potentially be a large performance concern

```suggestion
    function onLoad() {
      districts &&
        map.addSource("districts", {
          type: "geojson",
          data: districts
        });
      map.addLayer({
        id: "districts",
        type: "fill",
        source: "districts",
        layout: {},
        paint: {
          "fill-color": { type: "identity", property: "color" }
        }
      });
      map.resize();

      setMapLoaded(true);
    }
    map.on("load", onLoad);
    return () => {
      map.off("load", onLoad);
    };
```

2021-07-23 14:44 UTC, maurizi commented on src/client/components/map/ProjectDistrictsMap.tsx
> +    p: "15px"
I assume you had this at some point and lost it?
All of the flyout menus were hiding up in the upper-right corner of the screen w/o this.
```suggestion
    p: "15px",
    position: "relative"
```

2021-07-23 20:05 UTC, maurizi approved these changes
👍

2021-07-26 15:50 UTC, merged