Fix overlap between keyboard shortcuts and paintbrush slider
PublicMapping/districtbuilder pull request #874
Opened 2021-07-27 19:27 UTC by kevinearldenny

## Overview

- Fixes the bug identified in #860 where the paintbrush slider rendered over top of the keyboard shortcuts modal
- Finalizes the UX improvements to paintbrush slider that were began in #871 . It was never explicitly spec'd out when the paintbrush size slider should be displayed, and it previously was not displaying the paintbrush slider if a user selected the paintbrush tool via keyboard shortcuts
- Adds new keyboard shortcuts for incrementing / decrementing the size of the paintbrush tool

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

![image](https://user-images.githubusercontent.com/66973361/127215142-a51a9ceb-d6d0-410a-8083-3e19539e021e.png)

![image](https://user-images.githubusercontent.com/66973361/127215108-0c755ccb-2449-41f8-9005-40492453ecad.png)

### Notes

Keyboard shortcuts weren't explicitly asked for around the paintbrush size slider, but they certainly are fun to use 😀 

I kind of randomly went with `B` and `M` for the increment / decrement functionality - perhaps there might be better choices here, @jfrankl ? 

## Testing Instructions

- Go to a project, select the paintbrush tool and then type `?` to open the shortcuts modal
- Expect: Shortcuts modal is rendered above the paintbrush slider
- Click `B` or `M` while the paintbrush tool is selected.
- Expect: Paintbrush is incremented / decremented

Closes #860

2021-07-30 14:39 UTC, maurizi requested changes
Left a few comments that need to be addressed - but did verify the new keyboard shortcuts are working.

2021-07-30 14:39 UTC, maurizi commented on src/client/components/MapHeader.tsx
> +                  value={paintBrushSize}
This line is causing a console error (https://fb.me/react-controlled-components):
![image](https://user-images.githubusercontent.com/4432106/127668728-fb703cbc-9187-413f-8366-9fac609ff42f.png)

```suggestion
                  value={paintBrushSize}
```

2021-07-30 14:39 UTC, maurizi commented on src/client/components/MapHeader.tsx
> +    zIndex: 999,
This is still too large - in general, try and keep your `z-index` values as low as you can afford to; in this case just a `z-index` of `1` was sufficient to get this to appear above the map

![image](https://user-images.githubusercontent.com/4432106/127669379-7fb46fc5-1ec4-4923-8cb7-c1d774ba95c1.png)


```suggestion
    zIndex: 1,
```

2021-07-30 21:23 UTC, jfrankl commented
In terms of what the shortcuts should be, I was trying to stick with keys on the left hand in QWERTY, with the idea that a user could have one hand on the keyboard and the other hand on the mouse. That's not perfect because not everyone is right handed or uses QWERTY.

2021-08-02 15:49 UTC, maurizi commented on src/client/components/MapHeader.tsx
>                        );
I don't think we want this behavior - we want the menu to be open so long as you have the paint brush tool selected, right?
```suggestion
                      // Open slider on click if not already open
                      setPaintBrushSizeSliderVisibility(tool === SelectionTool.PaintBrush);
```

2021-08-02 18:14 UTC, kevinearldenny commented on src/client/components/MapHeader.tsx
>                        );
Hmm, I personally like the ability to toggle the paintbrush slider visibility by clicking on the icon - when you're not using it it's nice to not have it taking up screen real estate. What are your thoughts, @jfrankl ?

2021-08-05 16:50 UTC, maurizi approved these changes
👍

2021-08-05 19:51 UTC, merged