Feature/mvm/convert to 2020
PublicMapping/districtbuilder pull request #878
Opened 2021-07-29 13:40 UTC by maurizi

## Overview

Brief description of what this PR does, and why it is needed.

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

Optional. Screenshots, examples, etc.

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

- How to test this PR
- Prefer bulleted description
- Start after checking out this branch
- Include any setup required, such as bundling scripts, restarting services, etc.
- Include test case, and expected output

Closes #XXX

2021-07-29 13:54 UTC, maurizi commented on src/server/src/projects/controllers/projects.controller.ts
> +    // CSV export contains every block<->district pair
This was an assumption on my part when I started that I'm no longer sure is true.

2021-07-29 15:37 UTC, ddohler commented on src/server/src/projects/controllers/projects.controller.ts
> +    // CSV export contains every block<->district pair
If this were true then you'd expect that `csvRows.length === Object.keys(crosswalk).length` , right? Is that actually true? Or am I misunderstanding?

2021-07-30 20:51 UTC, maurizi commented on src/server/src/projects/controllers/projects.controller.ts
> +    // Written in non-functional style for higher perf.
I originally had this written using `.reduce(...)` which was *surprisingly* slow compared to this

2021-07-30 20:53 UTC, maurizi commented on src/server/src/region-configs/services/region-configs.service.ts
> -  }
We now _can't_ have multiple `region_config`s that aren't hidden/archived, making this override not necessary

2021-08-02 16:10 UTC, kevinearldenny commented on src/server/src/region-configs/services/region-configs.service.ts
> -  }
One tangentially related thing here - not sure if it's totally necessary, but having a `census_year` field on a RegionConfig denoting whether it contains census data from 2010 or 2020 would definitely have been nice to have during testing.

2021-08-02 16:12 UTC, kevinearldenny commented on src/client/components/ConvertMapModal.tsx
> +                </Button>
It would be nice to have a spinner to let the user know that a project is being converted. The process took nearly a minute for me testing NC locally, so it seems important to let the user know that the conversion process is active and prevent them from clicking the button again to convert

2021-08-02 16:15 UTC, kevinearldenny requested changes
This worked perfectly for NC! All of the blocks appear to have been mapped successfully to their 2020 equivalents:

![image](https://user-images.githubusercontent.com/66973361/127892129-95ba6ab5-f741-472f-8026-82abca19fc61.png)

That being said, I did leave two comments of things that would be nice to have here. The spinner when conversion is taking place seems like it's probably important, but perhaps we could address this in a follow on issue

2021-08-02 17:27 UTC, maurizi commented on src/client/components/ConvertMapModal.tsx
> +                </Button>
Added a spinner in https://github.com/PublicMapping/districtbuilder/pull/878/commits/8bf022c82cf4b0750cc376423b5127a3c6e0e683

2021-08-02 17:37 UTC, maurizi commented on src/server/src/region-configs/services/region-configs.service.ts
> -  }
I think I came to the same conclusion myself partway though this PR, but in practice going forward `archived` and `census_year === "2010"` are going to be synonymous I think, so doing the refactor now didn't seem worth it.

I think we'll definitely want to do that if/when we acquire different kinds of archived regions besides our soon-to-be outdated '10 ones.

2021-08-02 19:26 UTC, kevinearldenny approved these changes
Okay, spinner looks good 👍  I also tested with MN and it worked perfectly as well, so I think we should be good to go here

2021-08-03 13:37 UTC, merged