Allow adding reference layers to project
PublicMapping/districtbuilder pull request #902
Opened 2021-08-09 20:39 UTC by kevinearldenny

## Overview

- Add modal to support uploading a new reference layer
- Add `ReferenceLayer` entity to backend
- Add a new endpoint to parse and validate a geojson or csv upload
- Add new endpoint to save a `reference_layer` for a project
- Display all uploaded reference layers in a new pane in the project sidebar

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

![image](https://user-images.githubusercontent.com/66973361/128770983-e06ae4cb-54fc-4c95-a7a9-3e39527e7bbe.png)
![image](https://user-images.githubusercontent.com/66973361/128771012-a05d5410-0988-4069-9e58-66e3bab1262d.png)
![image](https://user-images.githubusercontent.com/66973361/128771058-a6e83379-c8f9-4df2-9924-a4b405825286.png)

### Notes

Still need a bit of polish on the validation and csv support here, but figured I'd get a draft PR up here to begin reviewing since there is a lot here to look at.

## Testing Instructions

- `./scripts/update`
- Open a project, and click the + button in the bottom of the project sidebar on the left hand side to open the reference layer modal
- Attempt to upload the two attached geojson files; expect them to be saved to DB and record displayed in project sidebar

Closes #861

2021-08-10 22:56 UTC, kevinearldenny commented on src/client/actions/projectData.ts
> +
I can't remember if we prefer having a boolean explicitly passed in here or not

2021-08-10 22:57 UTC, kevinearldenny commented on src/server/migrations/1628539609169-project_reference_layers.ts
> +        await queryRunner.query(`ALTER TABLE "project_template" ALTER COLUMN "pinned_metric_fields" SET DEFAULT ARRAY['population','populationDeviation','raceChart','pvi','compactness']`);
For some reason `./scripts/migration generate` keeps adding these for me - any idea what's up here?

2021-08-10 22:59 UTC, kevinearldenny commented on src/server/src/reference-layers/controllers/reference-layers.controller.ts
> +    }
It seems like there might be a cleaner way to do this?

2021-08-10 23:03 UTC, kevinearldenny commented on src/shared/entities.d.ts
> +}
Am wondering what the best type for this is, since we don't have access to `geojson` in `/shared`

2021-08-18 22:05 UTC, maurizi requested changes
Wow there's a lot here 🐋 

I left a number of comments, mostly focused on the backend.

Since my suggestions of moving some of the backend functionality into the frontend will necessarily require refactoring the frontend code, I didn't dig too heavily into that side of things.

2021-08-18 22:05 UTC, maurizi commented on src/client/components/AddReferenceLayerModal.tsx
> +                //eslint-disable-next-line
There's no lint?
```suggestion
```

2021-08-18 22:05 UTC, maurizi commented on src/client/components/AddReferenceLayerModal.tsx
> +                  // accept={".csv" || ".geojson"}
According to MDN this takes a comma separated list of values https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept
```suggestion
                  accept={".csv,.geojson"}
```

2021-08-18 22:05 UTC, maurizi commented on src/client/components/ProjectReferenceLayers.tsx
> +// import Tooltip from "./Tooltip";
```suggestion
```

2021-08-20 18:48 UTC, maurizi requested changes
Tested and working well 🎉 

Left a lot of comments for code cleanups, and there are some tweaks I think we want to make to the modal UI to match the wireframes better, but I think the basic functionality is in place and makes sense.

2021-08-20 18:48 UTC, maurizi commented on src/client/components/AddReferenceLayerModal.tsx
> +      ) {
```suggestion
      const header = lines[0].replace("\r", "").split(",").map(s => s.toLowerCase());
      if (
        (header.includes("lat") || header.includes("latitude") || header.includes("y")) &&
        (header.includes("lon") || header.includes("longitude") || header.includes("x"))
      ) {
```

2021-08-20 18:48 UTC, maurizi commented on src/client/components/AddReferenceLayerModal.tsx
> +                    <Flex>Layer type: {createLayerResource.data.layer_type}</Flex>
Let's match what is in the wireframes here, as well as in the label names below:
![image](https://user-images.githubusercontent.com/4432106/130276632-3feca2c4-8da1-42ca-a72f-db438654cfec.png)

```suggestion
                    <Box>
                      Upload successful with {createLayerResource.data.numberOfFeatures}  {createLayerResource.data.layer_type.toLowerCase()}s. Give your layer a name and choose which property to use for labels.
                    </Box>
```

2021-08-20 18:48 UTC, maurizi commented on src/client/components/AddReferenceLayerModal.tsx
> +                            label="Reference layer name"
```suggestion
                            label="Layer name"
```

2021-08-20 18:48 UTC, maurizi commented on src/client/components/AddReferenceLayerModal.tsx
> +                            Label field:
```suggestion
                            Label property:
```

2021-08-20 18:48 UTC, maurizi commented on src/client/components/AddReferenceLayerModal.tsx
> +                            <option>Select label field...</option>
```suggestion
                            <option>Select label property...</option>
```

2021-08-20 18:48 UTC, maurizi commented on src/client/components/AddReferenceLayerModal.tsx
> +                </Button>
In the [wireframes](https://app.abstract.com/projects/9f988240-1dad-11e8-9a40-cba930331af7/branches/master/commits/a50633705d8b0acd77ce29ddfc84a181abdcb4a4/files/DCA38482-FC7F-4F48-BECD-44E07D9F7443/layers/1BD78006-02AB-4BF5-B5B5-40988BB8D19A) this "Redo" button is shown near where you have the "Cancel" button as a "Back" button, and there is no "Cancel" button, once the modal is in this state.

2021-08-20 18:48 UTC, maurizi commented on src/client/components/AddReferenceLayerModal.tsx
> +    geojson && setImportResponse(geojson);
Let's transform the headers to be in lowercase. Based on my brief search for sample data to test this feature with, it seems like ALL_UPPERCASE is a real favorite of Open Data Portal ™️  data sources, so it would be nicer to be case-insensitive here.
```suggestion
    const csvText = event.target?.result && event.target.result.toString();
    const results = csvText && readString(csvText, { header: true, transformHeader: s => s.toLowerCase() }); ,
    const geojson = results && convertCsvToGeojson(results);
    geojson && setImportResponse(geojson);
```

2021-08-20 21:16 UTC, kevinearldenny commented
I started addressing the issue you identified with permissions, but got hung up on a weird 400 error with the endpoint. The text of the error I'm getting is: `Invalid param option in Crud`. I'm pretty confused by this, since the configuration seems more or less identical to [/projects/id/export/geojson](https://github.com/PublicMapping/districtbuilder/blob/2a76d57e5e424df52c033fa9f57ecdd83921972d/src/server/src/projects/controllers/projects.controller.ts#L432)

2021-09-01 20:42 UTC, maurizi commented
I updated this to fix the remaining PR comments I had left as well as update the styling to match the wireframes:

Reference layer section now starts collapsed:
![image](https://user-images.githubusercontent.com/4432106/131741931-067bf41a-63b8-4f34-915a-87b17ce276e4.png)
Upload button is shown once section is expanded:
![Capture1](https://user-images.githubusercontent.com/4432106/131741805-2d7676d2-adcf-470b-bf2f-d9e5d3b02338.PNG)
![Capture2](https://user-images.githubusercontent.com/4432106/131741808-89530073-b022-4cbf-a21a-7a56559a2ca8.PNG)
![Capture2 5](https://user-images.githubusercontent.com/4432106/131741807-873eabb5-4132-40a3-8611-e6621649317c.PNG)
![Capture3](https://user-images.githubusercontent.com/4432106/131741809-7e07fa55-2318-4c74-b840-fb5a42d89811.PNG)
![Capture4](https://user-images.githubusercontent.com/4432106/131741811-9f668e46-ca8d-4307-b552-413af6a574e5.PNG)

2021-09-01 20:43 UTC, maurizi approved these changes

2021-09-01 21:16 UTC, merged