Show / remove reference layers
PublicMapping/districtbuilder pull request #999
Opened 2021-09-03 20:54 UTC by maurizi

## Overview

This has two main features:
 - Shows reference layers that have been added on the map (
 - Allows deleting existing reference layers

Also includes some tweaks to what was added in #902
 - Allows not setting the label field when adding a reference layer
 - Hides the reference layer section when the metrics are expanded

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

Showing point/polygon layers:
![Toggle](https://user-images.githubusercontent.com/4432106/132064371-a91d9b27-90a7-49b4-bca0-30fbb6b02b81.gif)

Deleting layers:
![Delete](https://user-images.githubusercontent.com/4432106/132064383-3ce21f6c-9af2-4af2-bb18-179f0901168e.gif)

Label option no longer required:
![NoLabels](https://user-images.githubusercontent.com/4432106/132064420-70d7bd32-25e5-4626-971c-691f082f8509.gif)

## Testing Instructions

- `scripts/update`
- Expand the reference layers section & add some CSV / geojson reference layers (I found state open data portals to be helpful resources when testing)
- Toggle the layers on/off using the checkboxes
- Try removing a reference layer using the "..." menu
- Reference layers should be visible when looking at another users map, but the "..." menu should not be

Closes #862 
Closes #863

2021-09-03 20:59 UTC, maurizi commented on src/client/components/map/Map.tsx
> +                "text-optional": true,
@jfrankl Wanted to note I made a conscious choice here to let point layer icons overlap (not the text) to prevent MapboxGL from collapsing adjacent icons together.

One of the main use cases for point reference layers we've discussed is incumbent locations, for which it seems quite important to show all the icons, so you know if you have more than 1 incumbent in the district you're drawing, even if they're quite close together.

2021-09-07 15:24 UTC, kevinearldenny commented on src/client/components/ProjectReferenceLayers.tsx
> +  showReferenceLayers
Does it make sense to set `isExpanded` to true whenever there is at least one reference layer included on the map? When opening a map with reference layers, it's not particularly obvious that there are reference layers included:

![image](https://user-images.githubusercontent.com/66973361/132370530-d1e03e7c-3491-4845-a71f-6ad74b6dee3c.png)

Alternatively, perhaps switching the icon from a plus symbol (which I would associate with "adding a new layer" moreso than expanding the box) to something more traditionally associated with the idea of expandable content might make this more intuitive here.

@jfrankl , any thoughts here?

2021-09-07 15:35 UTC, kevinearldenny requested changes
The core functionality looks good here 👍 

The only outstanding item I see here is making the UI more apparent that reference layers exist for a project when the reference layers box is not expanded. Perhaps we could switch out the `+` icon for something more appropriate here, or display the total count of reference layers next to the Reference Layers heading? Up to you whether we address this here or in a new issue.

2021-09-07 20:40 UTC, jfrankl commented on src/client/components/map/Map.tsx
> +                "text-optional": true,
Great idea, this makes sense to me.

2021-09-07 20:43 UTC, jfrankl commented on src/client/components/ProjectReferenceLayers.tsx
> +  showReferenceLayers
I think this is a good idea, to have the panel expanded by default when there are layers. Makes the feature much more discoverable, and it's easy to hide if needed.

2021-09-07 21:36 UTC, maurizi commented on src/client/components/ProjectReferenceLayers.tsx
> +  showReferenceLayers
@kevinearldenny fixed in https://github.com/PublicMapping/districtbuilder/pull/999/commits/b306aa3143e5e01d72117a1e08de02cb647fe21c

2021-09-14 18:53 UTC, kevinearldenny approved these changes
LGTM 👍

2021-09-14 19:59 UTC, merged